### ISSUE TITLE
Show server info in GUI before joining

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1099]
Currently, the GUI shows a list of available servers in an adress book. I think it would be nice to get a bit more information before joining.

One option would be to convert the server list into a table:

| Server | Online | No. Players | Game Type | WorldGen |
| --- | --- | --- | --- | --- |
| mb.net | yes | 7 / 256 | Light & Shadow | Perlin |
| localhost | no | - | - | - |

Another option would be to display info on the currently selected server in an info box below (or as a popup?). This wouldn't involve creating a UITable element and could provide more details (player names, list of modules, etc).

This is a rather low-prio item, but I want to keep it on my ToDo-List anyway.
##

**Comment by Cervator** [comment]
Bump - this is almost complete and ready to close, just need to add player count sometime :-)

**Comment by Cervator** [comment]
Finally closing this old issue. I think everything has pretty much been done by now, I submitted #2864 to cover the player count entry as this issue is probably hard to find & parse at this point. So closing as complete within updated scope some time ago (not directly associating with a specific release)
