### ISSUE TITLE
Easy option to export player identity

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1433]
Currently the game generates an identity for the player so in a client-server setting the server knows who is who. If you clear your local game config you lose said identity and cannot get it back.

We should add a simple "Export Identity" to the player settings menu that'll write out some simple player identity stuff, along with an "Import Identity" to overwrite current with a saved version.

Later we could probably get into outright profiles, but for now this would be a nice little usability win
##

**Comment by Cervator** [comment]
Pinging @flo on this one for awareness - thought it might be somewhat related to your user identity work for ownership and such. Would be nice if when players can "own" or protect blocks that they'd also be able to safeguard their identity somewhat :-)

**Comment by Cervator** [comment]
Bump - thanks to @gianluca-nitti we now have an option to run a central identity server that can let you use your identity from different places (like multiple PCs) and log in to a game server as the same player.

That's more or less this issue taken to the next step beyond it, but I suppose some might still like the manual option. Probably wouldn't be hard to add at this point.

**Comment by gianluca-nitti** [comment]
> I suppose some might still like the manual option. Probably wouldn't be hard to add at this point.

I think I could implement this, however I'm not sure what exactly is desired.
Do you mean that a file picker dialog should open when clicking export/import so that the user can choose the location of the file (sorry if it's obvious, I just want to make sure)? This could be done with the Swing file chooser or by implementing a custom NUI file picker (which might become useful for other purposes too in the future).

Also, the identities on each server the client has joined are just a part of the configuration. Maybe we could reconsider what exactly should be exported. I see some options:
* Identity certificates only (probably what was meant when this issue was opened)
* Whole config (which wouldn't even be a real data export, just a file copy from the data directory to the user-specified location)
* Identities + Player config (+ keybindings? not sure), similar to first option but we also include player name and color; IMO an advantage over the whole config is that we exclude the video settings, which a user may want to keep different between two clients on different computers with different graphic capabilities
* Have a list of checkboxes to let the user choose what to export, and possibly what to import from an exported config, with reasonable defaults (probably the best option for "power users" but may confuse beginners).

Any comments?

PS. I probably won't be able to do it right now because I have a university exam in mid September which I'm revising a lot for, but I'll be happy to contribute on this issue after it.

**Comment by Cervator** [comment]
Forgot to close this - it was completed by #3123
