### ISSUE TITLE
Support different water levels in a world

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1466]
World generators that create lakes currently have to do this at sea level in order to have them rendered correctly. It would be nice if lakes could be at different height levels.

The SeaLevel / WaterLevel facet already support height information per (chunk) region. This could be used to update the water height shader parameter accordingly.

One difficulty is that this information is accessed for all chunks for every rendered frame.Currently, this is not even stored permanently and needs to be regenerated over and over.

**Comment by Cervator** [comment]
I put some further comments in #1476 - I think we were both pointing at different correct assertions :-)

I do believe the original intent of this issue is now fixed - water can look nice away from the old hard coded sea level height. But something somewhere is still likely only reflecting from one single height level.
