### ISSUE TITLE
Preview image for save games (logo, template placeholder or player-taken screenshots)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1487]
This is a pretty low priority but pretty cool idea suggested over in #1480

Enhance the current load game screen (which in the future could be reused for "scenarios" - premade worlds) with an image component showing a logo / template placeholder / screenshot the player has taken in that world.

Since currently screenshots are "global" (placed in /screenshots regardless of what world it was taken in) there'd need to be an added association of some sort. Symlinks and shortcuts could work, but sound like a messy OS-specific approach. We could just put screenshots into world save dirs instead. If that's done maybe a shortcut to each world save dir with screenshots could perhaps go in the global dir.

Modules and in particular gameplay template modules could include a logo or general screenshot from the world you play in. If such an image is available in a module it could be presented for a saved world based on that module template, if the player hasn't taken any screenshots yet. You could possibly even have said image component on the create game world showing if the template is selected. Or for individual modules on the module selection screen.

Ultimately any such logo could be used on a module tracking site too.

Might even be enough potential for a GSOC item - that time of year is coming up soon.

Edit Nov 2017: This item is still valid and relates somewhat to #2774 as reordering the stages of preparing a game would heavily impact this since new screens would become available. Another new concept since last that's very similar to this is making an outright module details screen. In both cases you're viewing enhanced details on either a save game (which in turn has modules) or a given module.

**Comment by kgriff12** [comment]
@Cervator Hello and it is a pleasure speaking with you. My name is Kelso Griffin and if you wish to get to know me a little better, you can find my introduction in the forums under the same profile name kgriff12 [here](http://forum.terasology.org/threads/contributor-intro-gsoc.1520/). Although I have already submitted my proposal for a different for standalone NUI and mobile server management utility issues for GSOC I just happened to stumble across this issue. While I feel that I might be of better use with the other more difficult issues, I also wish to work on this issue as well. This issue is still open, correct?

**Comment by msteiger** [comment]
Hello @kgriff12 - the issue is still open. Let us know if you need assistance. You can jump right in!

**Comment by lcalona** [comment]
@Cervator Hello again :) I would like to work on this project and am currently working on a proposal for GSoC. I have an idea of one way this could be implemented but I am not sure if it is the most effective or feasible. My idea is instead of trying to fit in an image on the Create Game or Modules Screen or even creating an entirely new tab or detail screen which the user would have to go through an additional step in order to see the preview image, I was wondering if we could preview the world or module on the background image that is persistent throughout the UI. I believe this would be more effective since that background image is always present and can provide the user with a real-time preview of the world or module without an additional step to access that screen. Of course, there should be a dedicated "preview mode" that works with #2074 with the option to show the image full screen as the UI gets in the way. However, if we want to keep the original background image the same throughout, then a dedicated tab or screen for the preview image would work fine. I would appreciate any feedback so I can center my proposal around the better idea. I'm excited to possibly work with all the great people of Terasology in order to help improve the user experience of this awesome game! :)

P.S. Sorry for being so last minute with this. I only recently started to really dive into GSoC and Terasology last week when I went on break, but I greatly appreciate the welcoming community!

**Comment by Cervator** [comment]
Closing this as completed some time ago - not really sure if there was anything left. can't remember the GSOC project well enough (hi @ar0ne! Hope you've been well). But we do have preview screenshots on the load game page, and also have a module details screen nowdays.
