### ISSUE TITLE
Support multiple languages (simple language switching)

### ISSUE THREAD

**Issue by getsmp** [MovingBlocks/Terasology#1515]
Now Terasology definetly needs API for adding another languages in the game. E.g. translating item names, GUI labels etc. It would be nice if the game structure supported this by default. For example, every module has folder "lang" and there are many language files containing item names and so on which are accessed via API. I don't know much how this part of game works, but it should be something like that. I would be able translate Terasology to Russian then, and other people would contribute, surely.

Thanks for replying.

**Comment by msteiger** [comment]
Good point. This has been on our internal TODO list for quite a while already. [TerasologyLauncher](https://github.com/MovingBlocks/TerasologyLauncher) and [CrashReporter](https://github.com/MovingBlocks/CrashReporter) have already been translated into many different languages.

Maybe it's time to start a translation project, even if the infrastructure is not 100% ready yet. You can find it at: 

http://translate.terasology.org

**Comment by Cervator** [comment]
Yup, this is on our list. But we haven't entirely sorted out how to deal with translating actual in-game content. While you can sort out stuff in a main menu in a size of a limited app like the launcher or crash reporter pretty easily digging into prefab files and other assets is a much bigger challenge :-)

For example, should an "Axe" have its display name translated, and if so should you be able to request an axe via the console using the translated name? Not the best example since the console is for debug, but you get the idea :D

This is on the topic list for the next dev meeting

Also: already entered with #1343 :-)
