### ISSUE TITLE
Refactor ChunkConstants

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1536]
If you access the `ChunkConstants` class, it will trigger the initialization of all constants. 

The `VERTICAL_SEGMENTS` constant is being read from the config file. Thus, If any constant is read before the config file is read, it will either have the default value or crash with an `ExceptionInInitializerError`, if the config doesn't exist.

This value should probably not be a public constant as it has dependencies reaching out of the class. It is currently also used in `ChunkImpl.getSubMeshAABB()` only. The calling method `WorldRendererLwjgl.renderChunk()` also relies on the fact that this constant equals the length of the `chunk.getMesh()` array. 

*Sidenote:* I think that this should return an (unmodifiable) list rather than the raw array.

I believe this could be refactored and improved significantly with little effort. Maybe @emanuele3d is up for it?

**Comment by emanuele3d** [comment]
I'm just having a first look at this.

I agree with your reasoning that VERTICAL_SEGMENTS just shouldn't be initialized this way. I can remove it altogether from ChunkConstants and refactor ChunkImpl.getSubMeshAABB() accordingly. Is that what you intended or did you have more refactoring in mind for ChunkConstants?

Concerning WorldRendererLwjgl.renderChunk(), I'm not familiar with many of the aspects regarding chunks and their underlying geometry. What are the vertical mesh segments? Can the renderer just iterate over the array returned by chunk.getMesh() instead? Is the array guaranteed to have no null items?

Concerning returning an unmodifiable list rather than the array, what's your specific concern?

**Comment by msteiger** [comment]
About the constant:
This is exactly what I meant, yes. This should already fix this issue. Maybe `ChunkImpl` doesn't even need to know if the value is always equal to `getMesh().length()`. 

About the renderChunk() method:
I think that is reasonable(no. meshes == no. sub-mesh AABBs), but maybe @immortius or @Josharias can give more profound feedback.

About returning an array:
This gives away a lot of control. The caller can modify the array at any time (by accident). There is no need to allow this. It could be either wrapped in an ArrayList or even an ImmutableList (including setters).

**Comment by immortius** [comment]
There's probably not much reason to even have veritcal chunk segments anymore, or at least the way they are implemented. All they do is divide a chunk into horizontal slices stacked on top of each other, and generates a mesh for each. It defaults to 1, so a single mesh per chunk. Don't think there is any reason to mess with it generally. I would suggest it could actually be a constant, or simply dropped as a feature.

In theory we should actually generate a number of mesh per chunk based on the number of vertices involved - there is a maximum number of vertices per chunk resulting from the maximum size of an index. But that number is probably Integer.MAX so not a real concern.

**Comment by emanuele3d** [comment]
I just had a quick look at what happens if vertical segments are eradicated completely. It all looks good,  but I wondered if there still is a reason to have multiple meshes per chunk then, i.e. should getMesh() and getPendingMesh() NOT return an array anymore?

**Comment by immortius** [comment]
I believe those should only return the one ChunkMesh then, yes.

**Comment by msteiger** [comment]
Fixed by #1567
