### ISSUE TITLE
help

### ISSUE THREAD

**Issue by paulanne** [MovingBlocks/Terasology#1548]
java.lang.RuntimeException: Your GPU driver is not supporting the mandatory versions or extensions of OpenGL. Considered updating your GPU drivers? Exiting...
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.checkOpenGL(LwjglGraphics.java:270)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initOpenGL(LwjglGraphics.java:191)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:105)
	at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:266)
	at org.terasology.engine.TerasologyEngine.<init>(TerasologyEngine.java:169)
	at org.terasology.engine.Terasology.main(Terasology.java:116)

**Comment by immortius** [comment]
What video card do you have?

As the error says, either your video card is too low spec to run Terasology, or you need to update your drivers.

**Comment by emanuele3d** [comment]
I'm going to look into the code generating this message, it always bothered me and it happens frequently enough. The user shouldn't have to provide separately the graphic card nor the driver numbers (although he/she should have the freedom to edit those details away from the log if desired). 

I also think the error should be a bit more specific, i.e. which mandatory versions/extentions are failing? And return a complete list rather than the first that fails. I stumbled in the code once (LwjglGraphics.checkOpenGL()) and it shouldn't be too hard to make it more informative and focused from a user perspective.

Can you assign this issue to me and keep it open @immortius?

**Comment by emanuele3d** [comment]
Thank you @msteiger!

**Comment by msteiger** [comment]
You're welcome. I think that your suggestions would be quite an improvement.

**Comment by Cervator** [comment]
The logging has been improved: https://github.com/MovingBlocks/Terasology/pull/1549

Since there isn't anything we can do to fix this I'm closing it :-(

Sorry @paulanne ! Please come back when you get a chance on a different computer :-)

**Comment by emanuele3d** [comment]
Actually, ideally we find a way to give @paulanne a dev build with the new feature, so that at least we can find out what failed in his case. Would that be possible?

**Comment by Cervator** [comment]
Sure, just try out http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
