### ISSUE TITLE
add a way to unbind keybindings

### ISSUE THREAD

**Issue by 4rz0** [MovingBlocks/Terasology#1568]
Most games allow it to unbind keys, for when you don't need their function and don't want them to use space on your keyboard.
I suggest using *Escape* for that, at the moment, *Escape* just gets mapped as the keybind.

**Comment by 4rz0** [comment]
Seeing that the ingame menu, which is usually hardmapped to escape in most games, is actually a mappable function, it'd be a bad idea to use it to unbind keys.
What about having a button somewhere in the UI that you have to click to unbind keys?
Either one that unbinds the key that's active for mapping, or a button next to every function.

**Comment by Cervator** [comment]
Another possible thought: If the user left clicks a button to make a key, start the mapping process and accept *any* valid input with no exception for unmapping. If the user *right* clicks a button reset its mapping and don't enter the mapping process at all?

**Comment by Sk0ut** [comment]
@Cervator 
My group has taken interest in this issue, so I would like to solve some doubts before starting.
I already thinkered with the keybinds menu and found that this issue is still on.
So, my question is, should we not allow the right click to be mapped and use it as a cancel for the mapping, add a button to cancel the mapping (this one would make the UI bigger, because there's no space for a reset button next to each keybing) or clicking anywhere outside the keybing box cancel the mapping?

**Comment by Sk0ut** [comment]
I realized right now that using the right click to cancel it's not a good idea, since the right click is associated with the action "Use Held Item", so right click should also be mappable

**Comment by msteiger** [comment]
I think that `ESC` would be appropriate to cancel the process.

In any case, I suggest creating a new modal dialog that opens when the key is clicked on to indicate that the game is waiting for a new button binding. Pressing `ESC` will close the dialog so that would be in line with cancelling the binding. Maybe the dialog could also have additional options such as "reset default" or just a text label that states the default binding.

Side-note: Maybe also #1511 is of interest to you.

**Comment by sceptross** [comment]
I also thought about that alternative, and I think it's the best way to do it, through implementing an additional button, instead of using the Esc key (because of what 4rzo previously said).

We'll also check out issue https://github.com/MovingBlocks/Terasology/issues/1511 and decide if we'll solve it after working on this one.

**Comment by skaldarnar** [comment]
Instead of thinking of "mapable" buttons you could _activate_ the binding process with left mouse, and _remove_ an existing binding with right mouse. The binding process could then accept any key/button. 

The modal dialog looks like another good option.

**Comment by Cervator** [comment]
@skaldarnar hit on what I meant earlier :-) Not using right mouse or esc as a way to escape from the binding process, just right mouse on a button instead of left would mean "reset this binding"

And yup, modal dialog would work too. I guess the question ultimately is: do we want to support *any* key being magical to where it'll cancel binding instead of being a valid choice? `ESC` seems pretty standard there and I wouldn't mind making it "special" for that reason. 

Or we could just add right mouse to reset and leave no key magical at all (no way to escape binding without entering a key - you can always just reset it again). Easy, but might be a little confusing/annoying in some cases.

And I would love to see support for #1511 later as well!

**Comment by Sk0ut** [comment]
We've developed a mockup of the modal window to show how we thought about implementing it.

![keybindings modal window](https://cloud.githubusercontent.com/assets/8569628/11527122/f7f8428a-98d6-11e5-874a-9d65a4599712.PNG)

The new keybinding box would start with the ??? and by pressing a key, scrolling or clicking on the box with any mouse button would change its text to the selected binding.
Pressing the remove button would clear the box text (no binding) and the default button would replace the box text with the default binding.
To confirm the new binding one would press the apply button and to cancel it one would press the cancel button. Both of them would take the player back to the input setting screen.

**Comment by Cervator** [comment]
Looks good to me :-)

It might be more than is needed, but it doesn't really hurt to be more thorough, especially since it is a separate window. You don't often get the option to cancel back out of a choice like that after you've picked a new key. I like it

One suggestion: Change "Apply" to "Save" - it has a bit more of a final quality to it ("Apply" sometimes just does a save-in-place and doesn't return/continue)

Bonus: Would it make sense to offer *both* binding options on that page rather than have the user go through it twice to also set the secondary option? As in, we support using two different keys for the same binding, should we have primary + secondary fields on this single screen? I don't know if that's a better or worse option.

**Comment by Cervator** [comment]
Closing as complete! :-)
