### ISSUE TITLE
Logging improvements for better 24/7 headless support

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1574]
So we have another user interested in doing a 24/7 server to help test, which revealed a fun little issue: the log file never rolls and we have a few scenarios that can trigger log spam. So we need a bit more usability there :-)

- [x] Move the log file to use a RollingFileAppender from logback - http://logback.qos.ch/manual/appenders.html#RollingFileAppender - maybe roll daily + in 5, 10, or 20 mb size chunks?
- [ ] Allow the user to easily configure logging, ideally in config.cfg. Maybe on initial run write the log settings from logback.groovy into a logging section in config.cfg and if it exists on future startups use the log settings from there?
- [x] Minimize log spam from the issue in #1503 in a clean fashion (might be out of scope to fix it, but maybe move to FINE or DEBUG?)
- [ ] Minimize log spam from "received too much input" in a multiplayer session
- [x] Minimize any other common log spam. Only one I can think of is a "brush" thing I vaguely remember from Cities
- [x] Tweak the CrashReporter if needed to deal with log file changes. Fancy: Could add back/forward buttons to load individual rolled log files

@msteiger might be taking a look :-)

**Comment by msteiger** [comment]
Changing the logging style to rolling logs is fairly easy: https://github.com/msteiger/Terasology/commit/849998fec2d9eb20cf59a7d61ef4d5a684d09edb. This will continue to write to the `Terasology.log` file (by setting both the file and archive fileNamePattern), but it has a few drawbacks:
* Appending to previous log files is mandatory :cry: We would need to delete old log files on startup first.
* It checks log file size (requires file read permissions) at every logging operation. This seems to be fairly fast though. Maybe @immortius can clarify if/how module permissions would have to be changed to make rolling logs work for modules? Why does writing to the log file even work? I saw that the `slf4j.Logger` interface was added in `ModuleManager` to the permission set, but there must be more to it.
* Rolling log files eventually throw out old log events. This is ok, but it would often be nice to retain the log of  the init phase.

Maybe we should just postpone the rolling log thing until it becomes a problem? Deal with the log spam and maybe activate zipping should keep log files reasonable small for a long time.

Having that said, I suggest configuring log file names and root log level through Java. This would lead to:
* Remove dependency to groovy entirely (smaller jar, yay!)
* Faster startup (no need to load groovy runtime and compile/run the logfile "code")
* Configuration of encoder / specific log levels, etc. in XML
* Have the option to write init phase logging to a different log file
* Adjust logging level through config file or even UI

**Comment by immortius** [comment]
Yeah, originally I wanted to start each session with a new log file and archive the previous one, but this didn't seem to be an option. So I settled for one log file rather than having new sessions start at the end of old log files.

There are a few parts to module permissions. Firstly, a module can only use a class if it is added to the permission set. So adding slf4j.Logger enables this. Secondly, if a class invokes a permission check, it only succeeds if either the permission is allowed to the module invoking the class, or if the permission is explicitly allowed for a class up the call chain before the module code, or if the permission check is set to use the security context of its own class. I haven't checked to see if slf4j/logback does the latter. So possibly it is only working now because the permission checks are all done by engine when it first logs, and no further permission checks are invoked. If the log can roll at any time, and if rolling the log invokes a permission check (file access permission of some flavor), this means that modules may be denied permission to the log randomly. The solution would be granting the permission to Logger.class a lower level class in the invocation chain.

**Comment by Cervator** [comment]
Bump - this is partially done now with #1609 merged. Left is the log spam and easy user log config. I am figuring we should consider logback out of scope for end-users to manage. What can we do to easily let them do some basic config? Command line arg? Config.cfg overrides?

**Comment by minnesotags** [comment]
Ping!

minnesotags

**Comment by msteiger** [comment]
About the config: we could add a drop down list in the settings GUI that adjusts the level for the root launcher (or maybe `org.terasology.*`).

About the log spill: I don't think that all of the invalid block access bugs are fixed soon. I liked the idea by @esapetri about filtering the log. We just need to find a smart way that does that without loss of info. Maybe based on chunks/arbitrary bounding-boxes?

**Comment by minnesotags** [comment]
I don't know how java programming works, but we have a similar situation with gps logging which we do just using a cron and rsync. We start a new file at 00:00:00 which has a header, then is named for the day, the rolling log file rsyncs to that file every minute. In your case, that could work really well, since it sounds like you alway need that rolling log file to have the same name. You don't need to save past data in that particular file, since it is rsynced to a different file. You just have to make sure that you don't erase the previous data's data via an rsync at the very end which wipes the file clean.

**Comment by Cervator** [comment]
Unfortunately we can't involve rsync since it all needs to happen inside the game and be portable across different OSes :-(

Anyway, I think that part was solved anyway :-) Now we just need to improve config and avoid some of the log spam

**Comment by Member1221** [comment]
I can look into that later. C:

**Comment by msteiger** [comment]
It should be fairly easy to override the default log level with an environment variable, either set through the command line or from within Terasology. Here's an example:

http://logback.qos.ch/faq.html#overrideFromCL

**Comment by msteiger** [comment]
The log level is `DEBUG` for file-based logs, which should be enough under all circumstances. I therefore suggest removing the user-customizable log level.

Maybe we can reduce the log level for the network input overflow so we can close this issue?

**Comment by Cervator** [comment]
We could probably just adjust the log level accordingly so the game doesn't overlog yeah. We'd need to be staying on top of that constantly and tweak it reactively when some new functionality turns on the log spigot on too high - we know it'll happen from time to time :-)

Since likely only tech-savvy users will want to tweak at the log level I'm fine leaving it out of the game UI, we should just document the alternative options somewhere then. And maybe the Launcher can later be made to include that option (set an environment variable in the game launch session)

So a quick doc snippet somewhere could close this.

**Comment by Cervator** [comment]
Closing this as done for now, mostly in favor of https://github.com/MovingBlocks/TerasologyLauncher/issues/349 and any general future work toward limiting log spam.
