### ISSUE TITLE
Further improvements of logging / handling of low-end video cards

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1616]
This one is for @emanuele3d who might be able to improve the user experience when the game encounters a low-end video card and produces obscure errors.

Recent pastebin: http://pastebin.com/KiMGmXvY
Recent error popup: http://www.myimg.de/?img=Desktop26022015093725a7060.png
Recent crash dump: http://pastebin.com/wHT4JpiR
Recent thread: http://forum.terasology.org/threads/error-beim-starten.1251

They might not all relate ..

Somewhat low priority since these errors are on edge case hardware (usually integrated video). But it is always nice to be able to produce more readable error messages.

**Comment by emanuele3d** [comment]
This issue was probably due to the user's system not providing support for GLSL 1.20 AND Terasology not testing for the system's support for OpenGL 2.1, which includes GLSL 1.20 as a requirement.

An additional check (for opengl 2.1) has been added to LwjglGraphics.checkOpenGL() through PR #1629. While this still won't allow the user to start Terasology, it will at least prevent the obscure shader compilation error and replace it with a simpler incompatibility message specifically pointing to the system's lack of support for OpenGL 2.1.

**Comment by Cervator** [comment]
Thanks @emanuele3d :-)

Closing as complete

**Comment by emanuele3d** [comment]
You are welcome!
