### ISSUE TITLE
Dupe bug in multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1625]
This one is kind of funny.

Start a headless server and connect to it. Like usual you start with a chest that's supposed to have another chest in it.

However, whenever you place the initial chest it isn't removed from your inventory - you place a dupe

Amusingly you can then actually somehow place the dupe chest inside itself and get some really far out behavior :D

**Comment by skaldarnar** [comment]
I encountered this dupe behavior on @minnesotags server some time ago, not for the chest but blocks and items in general. I could place the same block infinitely often or throw torches around without decreasing my stock...

**Comment by MarcinSc** [comment]
I was able to debug the problem, but don't know how to resolve it, as it involves unwrapping the events from the network.

The problem is, that the ActivateRequest received on the server has "null" instigator. As a result - when BlockItemSystem::onPlaceBlock is trying to send "PlaySoundEvent" to the instigator, it fails with NullPointerException, and the ActivateEvent is not sent to the ItemSystem (priority - trivial, where it would have been removed from the inventory.

**Comment by Cervator** [comment]
A quick addendum from the IRC discussion: There may be a spot here we can harden architecturally as a bug like that shouldn't be allowed to lead to duplication. Marcin suggested maybe the failed Event dispatch should continue dispatching to following listeners, rather than failing

**Comment by immortius** [comment]
I concur, the event dispatcher should catch, log, and continue.
