### ISSUE TITLE
CoreRegistry unable to resolve a class loaded by different ClassLoader for injection

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#1705]
Steps to reproduce:
1. Module B depends on module A.
2. Module B has "requiredPermissions": ["perm"]
3. Define interface with @API(permissionSet = "perm") and a system implementing it, make sure the system has @Share(InterfaceName.class)
4. In module B create a system that has a field of type InterfaceName with @In annotation.

Result:
The field is not set, InjectionHelper correctly gets the class, however CoreRegistry returns null for it, because it has in its map the same class but loaded by some other ClassLoader.

Expected result:
Field gets correctly injected.
##

**Comment by immortius** [comment]
Notes to self:
* Problem lives in gestalt-module
* When the class loader for B attempts to get the class, first tries to get it from A's classloader. This fails (no permission) so the class is reloaded in class loader B, when we need it to get the class from the root class loader.
* Believe the fix is an extra step of resolving from the root class loader if fails from parent class loader, before loading from the current class loader. Or maybe attempting load all the way up the chain?

**Comment by immortius** [comment]
I have fixed this issue in gestalt-module now and released as version 3.0.1, just needs Terasology to be updated to use the new version.

**Comment by Cervator** [comment]
Digging around in old issues - engine depends on `gestalt-module` at 5.1.2 right now, so I expect this is resolved (although unsure if anything stable actually uses the `permissionSet` stuff yet)

Closing as complete.
