### ISSUE TITLE
checkForSupportRemoved able to spin out of control

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1714]
I noticed this in TTA after chopping down a tree via the lowest trunk block, which is meant to have the rest of the tree collapse.

The game slowed to an utter crawl with less than 1 FPS, fans spinning madly, but I was able to enable debug metrics and note "StructuralCheck" higher than 1000ms. Took a screen capture with an external program and by the time I got it GrowingFlora was at 3300 ms and Temp Blocks Cleanup at 1408 ms. Maybe somehow the structural support went viral and infected other adjacent trees causing a massive cascade of broken blocks?

Probably the system needs some optimization somehow, and guards to avoid going too crazy. Wonder if there's anything we can do in the engine to throttle systems causing too much processing? It was still alive enough to put out the "Delta too great ... capping" messages

![terasology _ pre alpha_2015-05-03_21-58-42](https://cloud.githubusercontent.com/assets/1063833/7448165/898711de-f1e0-11e4-9e9f-914a16dc0912.png)
##

**Comment by MarcinSc** [comment]
Back when I was looking at it last time, the tree blocks never had the SideBlockSupportRequired component, and for a good reason. So, this system should not be invoked when chopping down the tree, unless someone came in and changed it. If so, for performance reasons, I'd suggest to increase the "dropDelay" in it. Also, the chopping down the tree could be probably done better - treating the whole tree as a structure and removing it in one go, rather than let it drop blocks all over - causing an entity lag.

**Comment by MarcinSc** [comment]
It also might be due to the System.out.println... in BlockStructuralSupportSystem, as outputting to console is rather slow.

**Comment by Cervator** [comment]
Thanks for the feedback.

Oddly I actually thought the whole tree insta-poofed some time back (months and months). Then it started coming down in more inconsistent pieces.

The growth system seems to swiss-cheese the trees somehow, maybe that was added later and the trees aren't in one piece anymore, so to say?

And yeah if we have some System.out then we should definitely take that out sometime.

**Comment by MarcinSc** [comment]
I already did (created the PR). Also, yeah the tree chopping doesn't work correctly, and I have no clue why, which is why I wanted to rewrite it, to simplify the generation.
