### ISSUE TITLE
Make leaves penetrable

### ISSUE THREAD

**Issue by t3hk0d3** [MovingBlocks/Terasology#172]
Subj.

But movement speed inside should be dramatically decreased: 0.1f horizontal, 0.5f vertical

**Comment by joseph-healy** [comment]
Hey, I was looking to help with this one. I'm not super familiar with the module system. Which one owuld I be working in if I wanted to help with this?

**Comment by Cervator** [comment]
@t3hk0d3 lives! Good to see a sign of life, how have you been? :-)

**Comment by t3hk0d3** [comment]
@Cervator W00t! I never died :D Work and Ruby world consumed me :P

I hesitated to close this issue, but its 4 years old already and probably non-relevant anymore :(
Glad to see Terasology is not abandoned, unlike most of projects in that field.

**Comment by Cervator** [comment]
We'll keep up the good fight! Tons of good improvements, even got into GSOC, which is a big deal :-)

As for this issue both @zriezenman and @Double-A-92 got it to work to some degree! I even still have @Double-A-92's branch with it in my mega-workspace. However, the rendering proved problematic, as when you were inside a tree almost none of the blocks would render since their faces were occluded by adjacent blocks.

Tweaking the rendering would likely take some work and we didn't have any 3d wizards handy up until recently, in fact one of the GSOC issues is about that :-)

Anyway, don't you just miss working on Terasology, eh? eh? Totally want to come back and write some cool modules, right? :D
