### ISSUE TITLE
Best practices + code rules for default methods

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1729]
So with Java 8 we have access to a powerful new tool: default interface methods.

A couple usages have snuck in so far but @msteiger rightfully pointed out there are some known pitfalls with a nice article: http://java.dzone.com/articles/java-8-default-methods-can

I figure we could probably come up with a best practice for our use of them + maybe a quick guideline page in the wiki with an example or two.

We could identify a few places where we can apply this pattern right away - for instance BaseComponentSystem could be entirely replaced with empty default methods in ComponentSystem

And I bet we could even write some (or find existing?) code scanning rules that would detect poor uses of default methods (such as overriding a default method from another interface, or getting too crazy with super calls)

Making this to remember - probably wouldn't be too hard for somebody with a bit of spare time to do a little research 
##

**Comment by prestidigitator** [comment]
I'm still trying to figure out exactly what to think of default methods.  On the one hand I'll certainly admit that they are convenient, and even make sense in many cases (e.g. the standard Collections library).  On the other hand, it is ironically a step back for Java; interfaces were a way to escape the kind of multiple-inheritance issues we had in C++ 20 years ago, and by introducing this feature those issues are cropping up for the language that, "fixed them."

**Comment by MarcinSc** [comment]
@prestidigitator That is true, but it's not a new problem that was introduced with the "default" keyword.

If for some reason your class was implementing two interfaces with the same method signature, you'd be in trouble anyway, because you would not have been able to provide two different implementations of that method (one for each interface to use). So, while the introduction of the "default" method implementation is indeed causing some trouble, it's not really a new trouble, but a trouble that already existed before, but due to it's scope (possibility of having two interfaces with the same method signature) - ignored. This change did not increase the scope of the problem, nor has it increased its complexity

Besides, you should always choose composition over inheritance anyway, for good programming practices. So, if you find yourself having a class implementing multiple interfaces - you should probably think twice...

**Comment by prestidigitator** [comment]
@MarcinSc - True.  If the interfaces have conflicting methods with different semantics it is definitely a good time to consider whether you should be implementing both of them.  In some cases when an object does fulfill multiple compatible roles I think implementing multiple interfaces is fine, but I agree that generally composition is the better option.

**Comment by jdrueckert** [comment]
We're at Java 11 now and decided that with the limited amount of actionable detail, this issue is not relevant anymore going forward.
