### ISSUE TITLE
Reminder for disposal strategies for new Context system when ready

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1737]
As discussed in #1727 - a reminder for when we're ready to work more specifically on disposal with the new Context concept. Possibility of contexts going out of scope - how to dispose what they reference, if at all? Maybe make an AutoCloseable of some sort available if desired?

Sort of related: #1296 & @emanuele3d has expressed interest in learning more later
##

**Comment by immortius** [comment]
In general Context can hold any sort of object, so there's no defined interface for it to hook off of for cleanup.

Possibly the Context could have special handling of anything registered that implements Closable (rather than Autoclosable which is a special case), disposing them when the context itself is disposed.

**Comment by pollend** [comment]
I think going forward I would like to adopt this: https://github.com/MovingBlocks/gestalt/tree/develop/gestalt-di
