### ISSUE TITLE
Crash on missing FBO for SSAO

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1755]
The game crashes with an NPE in [ShaderParametersSSAO.java Line 95](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/shader/ShaderParametersSSAO.java#L95).

Steps to reproduce:
* Start a new game
* Go back to main menu
* Enter video settings screen
* Click back
* NPE in `CoreRegistry.get(LwjglRenderingProcess.class).getFBO("sceneOpaque");`

It could be related to #1689.

This was discovered by @Cervator in #1732.

**Comment by Cervator** [comment]
Throwing this at @emanuele3d to see if it'll stick :D

**Comment by emanuele3d** [comment]
Gut reaction: oh, this is weird. 

So you are saying that this happens when there is no game actually in progress? I guess going back from the video setting screen triggers some shader-related activity/recompilation. It make sense that an error is generated because the FBOs are available only when a game is active. But there shouldn't be any shader-parameter injection if there is no active game.

In any case, it's up my alley. I should be able to fix it at some point.

**Comment by emanuele3d** [comment]
@msteiger: can you try to reproduce again? This should have been fixed with my latest PR, introducing the FrameBuffersManager.

**Comment by msteiger** [comment]
Sure, will try on Saturday, if possible.

**Comment by msteiger** [comment]
I haven't forgotten about this issue - will check as soon as possible.

**Comment by skaldarnar** [comment]
I'm not able to reproduce with latest develop (https://github.com/MovingBlocks/Terasology/commit/23855832fc103d1e3f2e30a4b9ad5a8362b4efee).

**Comment by msteiger** [comment]
Sorry for the delay - it does work now. Thanks for fixing, @emanuele3d !
