### ISSUE TITLE
Input settings UI scrambled a bit

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1759]
As noted in #1740 - the input settings screen has the way large-size buttons we've seen on occasion. Probably an easy fix. @immortius noted the likely culprit as https://github.com/MovingBlocks/Terasology/commit/a129b89007b16d06a571d919db761155571f0874 which maybe @MarcinSc can fix (or anybody else with a quick bit of interest in UI - come and get it!)

**Comment by msteiger** [comment]
I found the source of the problem:

* The column layout is inside a scrollable area, so the content height if often larger than the available height.
* As soon as the input entries take up more space than is available `ColumnLayout.getPreferredContentSize()` passes a negative `availableSize` hint to the contents.
* Then, `CanvasImpl.calculateRestrictedSize()` uses this size hint to create a `Rect2i` to define the subregion for each widget.
* Since the size is invalid (y is negative) `Rect2i` just returns the `EMPTY` rect.
* Most widget don't care, but `UILabel` does: since `width` is zero, every character of the label is pushed to a new line, leading to an overly large height requirement.

There are different ways to deal with this issue. One would be to change the implementation of `Rect2i` for invalid size arguments. Just clamp the invalid axis to zero while keeping the other. This might have a few implication at other places.

Sending a ping to @immortius for feedback.

**Comment by immortius** [comment]
None of those things changed in the commit that introduced the issue, and they all sound like they are working as intended to me. The real question is why the ColumnLayout is being told there is limited available size - if it is in a scrollable area it has infinite available size in the directions that can be scrolled.

**Comment by immortius** [comment]
Honestly the ScrollableArea probably still doesn't work correctly with this fix, but it addresses the immediate issue. The logic around which scrollbar(s) to display is a bit convoluted and I suspect it is still incorrect, or at least produced less than desirable results. I think the scrollable area should just let the content have as much space as it wants and add whatever scrollbars are needed given that - the current logic attempts to squish the content in one or the other dimension in order to reduce scrollbars, which could result in poor layouts. If I'm reading it correctly anyway.

**Comment by Cervator** [comment]
Fix appreciated :-)

I take it we can worry about the finer details of scrolling later. I messed with resizing the window all over and couldn't find any obvious issues other than when the window is unrealistically small (which isn't new)

**Comment by MarcinSc** [comment]
I believe that the way the ScrollableArea currently works is the way it works in any other UI framework I have encountered. It should most definitely (by default) pass the infinite in the side it can scroll. If it did, you'd never be able to draw any text in it, as you would always render everything in one really long line.

If there is a problem, the problem most likely is in the ColumnLayout, or how it is used (or the fact that it is being used at all). I'm not sure if ColumnLayout can produce "empty space", that's probably the problem.

**Comment by MarcinSc** [comment]
The best we could do, is make it configurable to pass some other values (infinite for the scrollbar direction), but that should not be the default to make it work like in other UI frameworks.

**Comment by immortius** [comment]
@MarcinSc The problem was ScrollableLayout didn't pass infinite in the side(s) it could scroll.

**Comment by immortius** [comment]
I don't know what the other UI frameworks are that you are referring to, but the way I've always seen them work is they contain some content of a particular size. Then scrollable area adds scrollbars if the content is larger than the actual available space for rendering.

In NUI this translates to letting the content have as much space as it wants to renderer. It is not the scrollable area's job to prevent that content being too large (such as your label example) - that should be controlled by the content (by nesting it in a layout) or by disabling scrolling in the direction that should be restrained. Otherwise it is up to the content to determine how it should be laid out. If the content is a label with a large amount of text, then yes it will be a single line - but if you are allowing horizontal scrolling and haven't provided any other layout information I would assume that is your intent.

**Comment by MarcinSc** [comment]
I'm pretty sure AWT ScrollPane and JScrollPane works that way, as well as Windows GUI classes. The reason is - imagine a browser you use everyday. If the HTML to display contains a huge image - minimal size horizontally is larger than browser width, then and only then will the horizontal scroll bar appear.

How this happens is that the html document communicates to the ScrollPane it's minimum size. Once the width is established by the scroll pane it just asks the document for preferred size based on the width and renders it with the preferred size.

That is because vertical scroll bar is preferred over horizontal, which can be a setting, as I stated, but this I think should be the default behavior in case of both scroll bars enabled.

**Comment by MarcinSc** [comment]
So, either way, somehow the child component displayed within the ScrollableArea has to be able to figure out the actual available size of the viewport to accommodate scenarios when sometimes both scrollbars have to be displayed, but the horizontal one should be done only if really needed.
