### ISSUE TITLE
Avoid using the Windows-specific Saved Games folder

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1783]
When run under Windows, Terasology searches for the special folder "Saved Games" and places user content there, if possible. Otherwise it tries to store the data in "My Documents". It is necessary to access Window native libraries to get the actual folder locations. This is done through the JNA library.

I believe that this is not appropriate, because ..
* It introduces a rather large and complex dependency for a trivial, but important task.
* The name "Saved Games" is misleading, since all kinds of user data is stored there.
* It works under Windows only and different folders must be checked to find the data.

.. and suggest using the home folder (one level above Saved Games) instead. This could include a preceding `.` and result in `~/.Terasology` for all platforms.

On my machine, there are 19 applications that use a foldername with preceding `.` on Windows.

**Comment by Cervator** [comment]
We used to do this, and yeah it is precious few applications that actually use Saved Games vs dot dirs, AppData, or My Docs. On my system I've got *one* other game in there (Elite Dangerous) and 16 dot dirs (admittedly every single one is development related, none for other games)

I've got 6 games inside My Documents, 8 games inside My Games inside My Documents, 7 inside AppData/Roaming.... Windows is a mess.

I figure this is so we can drop JNA with nothing else using it? I wonder if My Docs or App Data would be more appropriate and discoverable by a system convention of some sort rather than via JNA.

In any case: damned if we do, damned if we don't :-)

https://xkcd.com/927/

**Comment by immortius** [comment]
In what way is JNA a large and complex dependency? It is two JARs (jna itself and platform) about 1MB in size all up, and no further dependencies. Platform could probably be dropped by setting up code just for the small amount of it we use inside Terasology itself, so feel free to do that. JNA itself will likely be used anyway in the future if we end up switching to use the native version of bullet.

"Saved Games" is the standard under windows, regardless of what other apps do. I'm loathe to add by the problem by sticking it in other locations. The only way to find the correct Saved Games location is through windows APIs. 

Regardless it is important that it goes somewhere visible (so not AppData) so that mods can be managed easily. My fallback position would be My Documents/My Games, which is probably the next best de facto standard. I think we would still be best served using JNA to discover the My Documents location though, and the issue with that location is the lack of localization for "My Games".

We have other techniques for other OSes, and for each OS we are aiming for the standard location for such data.

**Comment by msteiger** [comment]
Alright - then let's stick with it.
