### ISSUE TITLE
.blocks using "basedon" get an appearance like the parent

### ISSUE THREAD

**Issue by Josharias** [MovingBlocks/Terasology#1790]
The following child.bock file will always show up as a cube.   Additionally, it will use the parent's block tile unless a tile is explicitly defined on the child.  The two symptoms may possibly be connected.

```
parent.block
{
}
```
```
child.block
{
  "basedOn": "parent"
  "shape": "engine:halfBlock"
}
```

**Comment by immortius** [comment]
There are likely some little inheritance issues like this as a result of the changes to how inheritance works recently.

For the shape, what was happening was that the block was inheriting the freeform block family factory from the parent, and thus wasn't using the shape. I will change this so that if the parent definition uses the freeform block factory it is removed and the block factory determined by the child.

The second is similar - if a tile is resolved for the parent block, the child will not use the implicit tile based on its name. I think I'll leave this alone - you can avoid this behavior by ensuring there isn't a block tile that shares the name of the block.

**Comment by Cervator** [comment]
Fix merged. Closing as complete :-)

Thanks @immortius ! Check it out @Josharias !
