### ISSUE TITLE
Artifactory requires authentification for some artifacts

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1793]
I got the following error on Artifactory (for meta-server) today:
    
> Could not resolve all dependencies for configuration ':compile'.
> Could not download javax.inject.jar (org.glassfish.hk2.external:javax.inject:2.4.0-b10)
   > Could not HEAD 'http://artifactory.terasology.org/artifactory/virtual-repo-live/org/glassfish/hk2/external/javax.inject/2.4.0-b10/javax.inject-2.4.0-b10.jar'. Received status code 401 from server: Unauthorized

I changed the artifact resolution order (Maven Central first, then Artifactory) to make it work. The Artifactory config looks fine, I wonder what causes this. Maybe the lookup of external artifacts?

**Comment by Cervator** [comment]
Huh, that's peculiar. I don't recall having set up authentication being required anywhere.

In the past on *publishing* artifacts I've got errors that sound authentication related (permission denied) but that has been when trying to publish a second identical version of a release artifact to a release-only repo (unlike snapshots those don't get accepted with additional version increments)

Occasionally if some repo is unavailable maybe we will have hit odd errors where a download of something not in our Artifactory is none the less attempted as it isn't available elsewhere (with something down). Could that be it and Maven Central just had a hiccup the first time, then worked the second time and the order change was just a distraction?

**Comment by msteiger** [comment]
I was able to reproduce the issue for several hours yesterday, but it seems to work today. Maybe Artifactory was just redirect the request to Maven Central, which - for some reason - requested authentication for that particular artifact. Closing until it happens again.

**Comment by alwaysthecritic** [comment]
Just ran into a very similar thing that could be the same underlying cause. I fired up a new Artifactory instance on a docker container (which just acts as a local caching passthrough to jcenter). Then our Jenkins server started up and ran a load of builds all at once. Some of them failed due to 401 errors. My best hunch is that they were all hitting Artifactory at the same time for the same dependencies and perhaps Artifactory clashed for the local cache files - i.e. it was downloading them from jcenter then trying to write into its cache, but perhaps finding that the file was locked because another request was doing the same thing. Just a theory, but interested to know if that would explain it.

The last thing my build system needs is spurious failures, so I'm keen to understand and eradicate this.

**Comment by Cervator** [comment]
Very good idea @alwaysthecritic ! Especially since we might end up with more and more builds hitting ours, although the listed error above was for a jar that wouldn't be getting updated in our instance - in this case it was probably just proxying forward to jcenter or Maven Central. Makes sense too, although I wonder if Artifactory itself should improve its handling in a case like that. Are you on the latest version?

It may well have been that this issue for us was just a hiccup, but always good to get more details and ideas for future notice.
