### ISSUE TITLE
Weird slowdown during initial world generation

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1850]
At least in Perlin and HeightMap. Throughout the Ages is different and has always been a performance hog during chunk generation which it still is. However this issue seems to only matter on *initial* loading of chunks around the player. After that batch of chunks is done the issue doesn't occur again even moving with `hspeed` to force generation of a large amount of chunks.

This happens on my fairly beefy system on the default `moderate` view distance and is fairly severe until over. Anybody else able to replicate? This wasn't an issue a few months back to the best of my knowledge.

**Comment by msteiger** [comment]
Maybe it's related to the changes made in dcf30076df ? I don't see how that could be possible, but it's the closest match I can think of. Would you mind trying again without these changes? 

The slowdown didn't come to my attention yet.

**Comment by Cervator** [comment]
Tried without, but am having trouble replicating now in either case (which is weird as I've noticed it occasionally for weeks). With that and it not happening for you I'm more favoring some issue with my setup. Closing as a non-issue unless somebody else can replicate :-)

Out of maybe 10 attempts I did sense the familiar lag somewhat once (it comes in waves, maybe a second apart) but that's not really enough to go on. I'll keep an eye out and consider that block if I can replicate more reliably again sometime.

Thanks for checking it out!

**Comment by Cervator** [comment]
Caught it again today with "Complete Chunk Update" spiking somewhat. Still keeping it in mind.

**Comment by Josharias** [comment]
I have noticed stuttering not too long ago when crossing chunk boundaries on my dual core system.  Crossing back and forth gets the stutter going pretty good.  Is it possible the chunk preparation threads are being too greedy and sucking up too much CPU? I was hesitant to say anything previously because we have some thread improvement stuff in a PR, hoping it would just go away.

**Comment by Cervator** [comment]
Does the player start at a chunk intersection or in the middle of one? Pretty sure what I'm getting is solely on initial chunk gen and even if I'm nearly still (just looking around a little and maybe taking a few steps)

**Comment by immortius** [comment]
There's a bunch of chunk completion stuff that has to happen on the main thread at the moment (due to entity interaction), so there is that. Possibly we need to review when chunks are being swapped in and out of use as well, and ensuring there is leeway so that small movements don't trigger chunk reloads.

Beyond that you could be hitting some sort of memory threshold I guess.

**Comment by Cervator** [comment]
Probably two separate issues. Mine goes away entirely and doesn't reoccur - it just happens while the initial chunks are loading.

Both seem vague enough or likely to get reorganized in the future anyway to not worry enough about it to reopen this. We'll probably find all kinds of optimization potential when we actually go looking :-)
