### ISSUE TITLE
Show dependency information of modules

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1890]
It would be nice to have a dependency listing in the description of modules. For example, when you download `FlightModeToggleButton` it won't work until `HUDToggleButtons` is present as well. This information should be communicated.

Taken from #1884.

**Comment by andrelago13** [comment]
Hi!

I would like to try to do this within the [SelectModulesScreen.java](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectModulesScreen.java) file. I was thinking the dependency information could be show in the same space as the module's description, but I don't know what you prefer.

**Comment by andrelago13** [comment]
Alright, since it was a quite simple task I just decided to go on and tweak around a bit and I got this done the way I suggested above. Simply put, it checks wether the module has any dependencies with help from ModuleMetadata methods, and print their names if they exist.

Do you think this is a good approach or were you expecting a better and more sophisticated solution?

Below is what my solution looks like:

![imagem1](https://cloud.githubusercontent.com/assets/9060644/11703708/4355699e-9ed9-11e5-9897-ddea3a8acdca.png)

**Comment by Cervator** [comment]
Hey @andrelago13 and sorry for not getting back to you sooner, I sometimes only get time to respond to these things in the evening US East time :-)

That's a great improvement! I think that covers this issue well enough to consider it complete.

Bonus points for:

* Color the text of dependencies based on what's available, not of the right version, not present, etc, like the modules on the left would.
* Make the description panel into a tabbed panel and show description on one tab and dependencies on another. I'm sure we can find something to use a third tab for like a preview graphic (#1487) or optional dependencies, whenever either of those two are actually implemented

But really those are optional, the change is sufficient as it is :-)

**Comment by msteiger** [comment]
I agree - I would leave it as is for now as it improves the situation significantly. A slightly more sophisticated solution could be adding a new row (below "Status"?) listing all dependencies.

The server list dialog does something very similar: it lists all modules on the server and color-code them in red/green whether they are present on the client(=local) machine.

**Comment by Cervator** [comment]
Adding a row to status would probably overflow the box on modules with bigger dependency lists though. No scrolling in there :-)

I think tabs will be the way forward but in the main description box at least we get scroll so that can support really long lists if needed.

And yeah good reference to the server list, nice thing to review.

**Comment by andrelago13** [comment]
I agree tabs are the best way to do this since there is no scrolling. I'm going to run check the style on my code as it is so that it matches the project's style, and then PR so that this can be present within the game. Then I'll get into the tabs within the next couple of days and see how that goes

**Comment by Cervator** [comment]
Sounds good!

A tabbed UI element exists on the multiplayer screen and a few other places already, so there should be good stuff to reference :-)

**Comment by andrelago13** [comment]
Just one more thing, where should the strings "This module has no dependencies" and "Module dependencies:" be stored and how should I access them? Right now they are hard-coded but shouldn't  they be somewhere in the asset files for translation issues?

**Comment by msteiger** [comment]
Yes, that would be ideal. You can add new IDs for them in the i18n asset files (in resources) and translate them later in different languages with the Weblate interface:

http://translate.terasology.org/

You can have a look at the other GUI dialogs or at usages of `TranslationSystem` to see how it works.

**Comment by andrelago13** [comment]
Thanks @msteiger, I'll take a look into that

**Comment by andrelago13** [comment]
If one of the admins could revise the PR #2049 it would be great! I think it's better now. I made it get the text translations using TranslationSystem (thanks again for the tip @msteiger). I still intend to replace the panel by a tabbed panel, but since I can't predict when I'll get that done this might be enough to close this issue :)

**Comment by Cervator** [comment]
PR reviewed and merged. Thanks :-)

Closing this as complete. Would be thrilled to see the tabbing added later, no rush!

**Comment by andrelago13** [comment]
That's great :) that's the next goal for me :)
