### ISSUE TITLE
Asset license clarification

### ISSUE THREAD

**Issue by kozross** [MovingBlocks/Terasology#1895]
Are your assets licensed the same way as your code, or differently?

**Comment by Cervator** [comment]
Currently they're technically covered by our use of Apache v2.0 but that isn't really ideal for assets. We figure putting them under some sort of free use Creative Commons would be more appropriate, but haven't gotten around to it yet :-)

Somewhat ties into exactly how we organize modules. The engine + common foundation of modules surely will be under a very permissible setup while the further modules get from the "core" of the project the more variety we'll probably end up license-wise based on the desires of individual authors.

**Comment by kozross** [comment]
OK. I'll keep an eye on this if it changes. Thanks for getting back to me.

**Comment by Cervator** [comment]
Sure, I'll rename this and use it as a reminder.

Curiously, what's your interest? :-) Looking for assets in general for some other game or considering contributing to our little project here?

**Comment by kozross** [comment]
@Cervator Neither, actually - I'm working on an awesome list (like awesome-python et al) of free software and free culture resources for game development called [awesome-gamedev][1]. I included your game as an example, and wanted to ensure that both your software and your culture were free.

[1]: https://notabug.org/koz.ross/awesome-gamedev

**Comment by Cervator** [comment]
Ahh! Cool, and thank you :-)

**Comment by Cervator** [comment]
Going to consider this kinda-sorta resolved via https://github.com/MovingBlocks/Terasology/commit/4e0c6b0d9b0b77e4572de3decc18338bbfc2b48f - at least we have a note in the readme (and badges for both code and art!) along with a space for an exceptions list in the credit (at present just because a few icons are under CC BY 3.0 rather than 4.0)

There's more work to do for *individual* assets (and module readmes and such) as we still have some old ones that are poorly covered by licensing (we have to replace a few to be sure). One example issue pertaining to that would be #2407

@kozross: /wave! Hope you're still doing well.
