### ISSUE TITLE
Update Translation Server to Weblate 2.4

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1900]
Related: https://github.com/nijel/weblate/issues/814

**Comment by Cervator** [comment]
So I'm thinking we should try a manual upgrade to the very latest 2.4 build? Maybe we can try it this weekend

**Comment by msteiger** [comment]
I registered at https://sibbell.com to become notified when 2.4 gets out. I also found the password for the MySQL database, so maybe we can copy at least some config data.

It might even be worth creating a new droplet for it - Centos 6.5 is pretty old.

**Comment by Cervator** [comment]
New droplet is easy. I think the reason I picked CentOS 6.5 was because no 32-bit variant for 7 was available. Having crammed Weblate onto only a half gig droplet I thought maybe the 32-bit could give it an edge on the memory side.

No real reason it has to be CentOS though, just picked that as I'm the most familiar (or least unfamiliar, really) with that flavor :-)

Old droplet had been upgraded to 1 GB in trying to see if it would fix the warnings we get emails about, but it didn't help. Newer install has had fewer warnings until just recently, although those warnings I think are understandable (merge issues etc)

Speaking of I'm going to do a final snapshot of the old droplet and then get rid of it.

**Comment by msteiger** [comment]
I upgraded the translation system to Weblate 2.5, based on this Docker image: https://hub.docker.com/r/beevelop/weblate/

The following changes were necessary:

* Copy the auto-generated SSH key (private+public) from the old server to the new:  `/docker/weblate/data/ssh/` - the folder is mounted into the docker container
* Edit the `/usr/local/lib/python2.7/dist-packages/weblate/settings.py` inside the container: Activate GitHub OAuth, update server email address
* Manually create projects and components - quite a few things have changed, so automagic migration is hardly feasible
* Edit `docker-compose.yml` file: email SMTP server, Django port, admin name/pass

**Comment by msteiger** [comment]
Migration complete! Same admin credentials, same URL: http://translate.terasology.org
