### ISSUE TITLE
Convert some basic facet types into interfaces

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1904]
For the revamping of Cities, I'd like to have enormously (infinitely?) large, but sparse surface height facets. I could create a new type, but it would be more convenient if it was directly usable for Flora/Tree/etc. providers who explicitly expect a `SurfaceHeightFacet`.

I therefore suggest to convert it and maybe a few others (Density could be computed on demand in many cases I guess, etc.) into interfaces and convert the existing implementation to `BaseSurfaceHeightFacet` or something similar.

**Comment by immortius** [comment]
I'ld say you should keep the SparceSurfaceHeightFacet as a separate facet and then replace the standard producer for SurfaceHeightFacet to one that generates it from the SparceSurfaceHeightFacet. They seem to be addressing different concerns, and SurfaceHeightFacet is intended to be a high-resolution facet so that producers can affect small scale changes to surface height. SparceSurfaceHeightFacet wouldn't support that, I assume?

**Comment by msteiger** [comment]
Yes, that's correct. I'm copying the data, partly because it is not writable, so that makes sense. Closing until this becomes relevant again.
