### ISSUE TITLE
Include @Updates annotations in facet requirement chain

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1912]
I'm currently trying this configuration:
```java
@Produces(RoadFacet.class)
@Updates(@Facet(BlockedAreaFacet.class))
@Requires({@Facet(SettlementFacet.class), @Facet(BuildableTerrainFacet.class)})
```
Surprisingly, `BlockedAreaFacet` is `null`, because the `@Updates` annotation does not contribute to the chain of requirements. I think that this should be changed.

Adding the `BlockedAreaFacet` explicitly to the list of requirements looks wrong to me and also triggers an infinite loop, bypassing the cycle detection in `WorldBuilder`.

**Comment by immortius** [comment]
Suggested code change:

In determineProviderChainFor, change logic to
* gather all facets involved in producing the final facet (for each provider that produces or updates the final facet, the facets involved are those they require or update. Then recurse through those facets, producing a set of involved facets)
* produce the provider chain. It should be all producers that produce or update any of the involved facets, ordered such that
  - A provider that requires a facet must appear after a provider that produces it
  - A provider that updates a facet must appear after a provider that produces it
  - A provider that requires a facet should appear after a provider that updates it, unless that would conflict with the above.
  - If there is nothing else that affects the ordering, then it should be ordering in some deterministic manner (e.g. alphabetically).

The goal is to have as many providers that affect a facet run before the facet is used.

Potentially this approach draws too many facets into the provider chain though - specifically there is a difference between a provider that updates a facet without reading it to a provider that updates a facet and reads it (e.g. you might have a provider that marks areas blocked, but doesn't itself care if the area is blocked).  If this distinction was added, then a provider that only updates a facet but doesn't read it shouldn't bring in all the updaters, just the producer or even just have a dummy facet created for it, if the facet is not otherwise required.
