### ISSUE TITLE
Game not working

### ISSUE THREAD

**Issue by aerogers** [MovingBlocks/Terasology#1928]
i get to the world creation and I get close to the end of the world creation.  It gets stuck on awaiting character spawn

**Comment by msteiger** [comment]
Can you please post or upload the log file? Which world generator are you using?

**Comment by aerogers** [comment]
City module.  Will post log file when found

**Comment by Cervator** [comment]
I can replicate. Chunk generating threads all die so there's never enough world for the player to spawn.

Seems present in both latest release and latest dev build. I knew @msteiger was working on Cities and may have left the old version alone for last release. Next release I imagine we'll have the new Cities in which doesn't have this issue (I just flew around in the Cities world for quite a while no problem)

So I'd call this a known issue that should be fixed with the pending changes in the dev branch for Cities. @msteiger since it isn't working currently should we just merge Cities develop to master? It works well as I'm testing with the TeraMath update

**Comment by msteiger** [comment]
This should be fixed now. The preview screen is not yet supported, but this will come soon. Close?

**Comment by Cervator** [comment]
Oh, yes, I thought there was another item to follow-up on after the Cities fix, but had just been searching the forum. Thanks for pinging this :-)
