### ISSUE TITLE
Terasology was crush, if I load it with a some module.

### ISSUE THREAD

**Issue by Darktrader** [MovingBlocks/Terasology#2008]
My game always crushing, if I add some modules. Log file: http://pastebin.com/ndK15km4

**Comment by Cervator** [comment]
Hi @Darktrader - you are enabling too many modules :-)

The gameplay templates activate a set of compatible modules each. Sometimes you can add a few more, but not all modules are compatible with each other. Think of the gameplay templates as Minecraft-style  "mod packs" - you wouldn't enable more than one or add in a ton of additional mods on top.

Just try enabling a template with no additional modules selected and see if it works.

**Comment by Darktrader** [comment]
Thanks a lot, I understood my problems and try to run with only few additional module. It's work, but minimap didn't indicate in game enviroment (I saw only black screen in minimap window). 
And the last request for you about expanding comparably of modules. Is it possible to expand a comparably of those modules in future releases of Terasology? Can you, please, do this?

**Comment by Cervator** [comment]
Minimap being black on some systems is a known issue, yep, @msteiger worked on it and he gets a working map, a couple other of us get the black square instead. We'll figure it out :-)

Module compatibility: they'll never all be compatible since multiple different ways to play the game exist and you can't play two ways at once. That's what the gameplay templates provide - a focused way to play the game.

Eventually we'll have better stats and descriptions on which modules are incompatible with others and which are built to be compatible with just about anything :-)

I'll close this as resolved for now but feel free to report back with any further findings in the future!
