### ISSUE TITLE
org.terasology.registry.CoreRegistry get method inconsistency (possible software fault)

### ISSUE THREAD

**Issue by Sk0ut** [MovingBlocks/Terasology#2014]
Whilst working on another issue, I found that the [CoreRegistry class](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/registry/CoreRegistry.java) static method get has an if statement but calls the same method independently of it.

Although the call returns the expected value because of checking the same condition tested in the refered if statement, it makes the return value of the get method dependent on the [Context class](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/context/Context.java) implementation of the get method for the argument Context.class.

Should the CoreRegistry get method return its Context when the argument is Context.class or simply pass the argument to the get method of its Context?

After the answer, I'll create a PR with the fix according to it.

**Comment by Cervator** [comment]
@flo might know (ping!). It could be a temporary thing while Context is slowly phasing out CoreRegistry.

**Comment by flo** [comment]
@Sk0ut: good catch!

The original intention was to return the context field of the CoreRegistry when asked for the Context.class. However it is no longer necessary to do so since the Context implementation called ContextImpl is doing now a similar trick by itself. e.g. a calll of  context.get(Context.class) returns the context itself.

So the get method of CoreRegistry could be simplified to just 
`return context.get(type);`

**Comment by Sk0ut** [comment]
@flo
I thought about that alternative. However, if there was another class implementing the Context interface that didn't return itself when the argument was Context.class, wouldn't that break the functionality of the method get of the CoreRegistry class?

**Comment by Cervator** [comment]
Bump - any final feedback @flo?

I'm happy to merge it as-is if the difference is minor :-)

**Comment by flo** [comment]
well, the intention is to remove the CoreRegistry. It only exists for backward compability so that we have time to move from CoreRegistry to Context usage.

What we might want consider to do instead is merging the Context interface and Context implementation instead into a single class. I made them separate originally as I though Immoritus want it like that, but it turned out that Immoritus would have gone for a single class too.

**Comment by Cervator** [comment]
I read that as "Sure, can merge as-is then go further in the next cleanup PR" :-)

Let me know if I'm off, will merge soon otherwise

**Comment by Cervator** [comment]
Closing as completed by #2014 :-)

@flo if you're low on time yet have enough to help direct would it be something to keep our new friends engaged a bit longer with some architectural vision and ideas? And maybe a link or two to catch them up.

Should we perhaps submit another issue or two that describes the way forward, some nice little chunks that are easier to do? I know some related issues already exist, like #1818, #1770, and #1705. At the same time I realize this isn't necessarily the easiest area for new contributors to step into.
