### ISSUE TITLE
Game log files for server play lack a world name component

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2030]
If you play a local game the log file for game/world stuff will be named something like `Terasology-world1.log`

If you join a server you'll get `Terasology-.log` - we probably should give that some alternative name (could just use a placeholder "world" unless we have a local world with a name)

Should be easy.

**Comment by msteiger** [comment]
Maybe we could use the seed string?

**Comment by Cervator** [comment]
Are clients actually sent that? I thought sharing the seed could potentially be a cheating issue. It could also be long or controversial if players use *creative* seed values ;-)

Could we use the server name / address in some fashion? With a sequence number at the end if a user repeatedly joins the same server in one session.

**Comment by papeixoto** [comment]
@Cervator @msteiger  Hi. I'm also a student from Porto, we are a lot i know :). For this deliverable we're supposed to implement a feature and document it. So, in order to start, my group would greatly appreciate some explanation about the packages/modules related with this feature and the the main steps to implement it.

**Comment by Cervator** [comment]
You're all most definitely welcome, the more the merrier! :-)

This one should be pretty easy. It is an engine / config feature, no (game) modules involved. Although, I'm realizing our logback.xml (in `Terasology/facades/PC/src/main/resources`) is referring to a `${phase}` I have no idea where it is getting from :D @msteiger probably knows.

In this kind of case CTRL-SHIFT-F is your best friend in IntelliJ. Search for a related keyword, like "phase" and see what hits you get. Likely you can deduce which is the relevant one then see if that brings you to the code we need tweaked, or if you'll find a new keyword to go for.

Find Usages on method names or even simply CTRL-left mouse to navigate between things also helps a lot :-)

**Comment by msteiger** [comment]
The phase and the other parts of the log filename are configured in [LoggingContext](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/LoggingContext.java).

I assume you can get the game name from the [GameManifest](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/game/GameManifest.java). If that does not work you might want to check this spot here: [JoinServer L84](https://github.com/MovingBlocks/Terasology/blob/fadf43ec1cb321a6cd34ed29a656d025df70d98c/engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java#L84). This is where the client get the game name from the server.

**Comment by arkka** [comment]
@Cervator @msteiger Hi, based on your comments I try to solve this issue with my solution https://github.com/delftswa2016/Terasology/commit/2bd720b30051a66dfeef0346f73c04b09ffe8d89. As @msteiger mentioned before, I made the implementation on [JoinServer](https://github.com/MovingBlocks/Terasology/blob/fadf43ec1cb321a6cd34ed29a656d025df70d98c/engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java)  class. 

In order to get the remote host address, I need to create new methods on [Server class L138](https://github.com/delftswa2016/Terasology/blob/e2979d40dcc74ffd99902fc1350b165a869675ca/engine/src/main/java/org/terasology/network/internal/ServerImpl.java#L138) . Is this the most effective way to achieve this?
