### ISSUE TITLE
Rendering issue causing minimap to go all-black for some users [$25]

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2076]
Proxy issue for https://github.com/Terasology/Minimap/issues/4 to put the bounty here for now. We don't have all the Terasology (the org) repos enabled for Bountysource yet due to some config issue. Minimap actually is enabled but might need to reconfigure some stuff and what not :-)

In short some users get a black square instead of a working minimap. Myself and @skaldarnar see it that way while it works fine for @msteiger. This makes it more tricky to troubleshoot.

One potential suspect is the use of subRegionFBO at [MinimapGrid L195-L210](https://github.com/Terasology/Minimap/blob/master/src/main/java/org/terasology/minimap/rendering/nui/layers/MinimapGrid.java#L195-L210) which is [Canvas L232-L250](https://github.com/MovingBlocks/Terasology/blob/d83a141927b476df8fa52c0673feed3fbb746a34/engine/src/main/java/org/terasology/rendering/nui/Canvas.java#L232-L250)

Seems to me like it might be interesting to see what happened if we implemented an alternative way to draw the minimap, somehow? If that makes any sense at all.

In any way we can add more clues and discussion here (or in the Minimap issue, really)

**Comment by msteiger** [comment]
It works on my Windows 7 machine with an ATI Radeon card, but it does not work on a similar Windows 7 machine with a GeForce card, so maybe it's related to that.

However, the preview generation always works. The main difference is that the pixels are manually drawn in a texture rather than rendered using a FBO - so I assume it's related to the FBO creation/rendering.

Even though it renders all black, the FBO seems to be created fine in all cases. The check passes:
[LwjglFrameBufferObject.java#L50-L73](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/opengl/LwjglFrameBufferObject.java#L50-L73).

**Comment by msteiger** [comment]
The easiest way to reproduce is to download the [latest stable release](https://github.com/MovingBlocks/Terasology/releases), activate the Minimap module and start a new singleplayer game.

**Comment by Cervator** [comment]
@msteiger: feel free to claim the bounty, keep it, or roll it forward :-)

**Comment by msteiger** [comment]
The money should be in the MovingBlocks BountySource account now.

**Comment by Cervator** [comment]
Cool. Feel free to attach it to something else sometime :-)

I'll do another round of bounties later, will include that then if still there.
