### ISSUE TITLE
Jumping to my death gives me a NullPointerException

### ISSUE THREAD

**Issue by tasgoon** [MovingBlocks/Terasology#2112]
Playing around on a Joshiarias Survival, I got bored and decided to jump off of the mountain I was on. When I died, however, instead of getting a respawn screen, I got [this](http://pastebin.com/0TdDtuM0) crash. Any ideas as to what happened?

**Comment by Cervator** [comment]
That's an interesting one. Haven't had any crashes on death for a long time.

The NPE is linked directly to some of the functionality in JoshariasSurvival, so it is probably a pretty straight forward bug. Sending it @Josharias' way :-)

**Comment by Josharias** [comment]
Fixed in the latest build.  Thanks @tasgoon!

http://jenkins.movingblocks.net/view/Modules/job/IRLCorp/

**Comment by tasgoon** [comment]
You're welcome.

**Comment by Cervator** [comment]
Thanks @Josharias :-)

Any thoughts on how we can harden the engine to not crash in case a module misbehaves like this? Should we be throwing some exception catching on the engine side (in this case in the WorldRendererImpl I suppose) so a failure to render just ends up skipping something then moving on to the next thing?

**Comment by tasgoon** [comment]
How are module exceptions currently being handled? Are they being handled at all? I'm not that far into the code yet.

**Comment by MarcinSc** [comment]
This topic comes up over and over again. I'd recommend crashing, as we are now. IMO, it's better for the user to restart from last save, rather than have a corrupted world.

**Comment by Josharias** [comment]
We did recently put in gracefully handling exceptions that happen in event handlers.  There may be some other performance considerations for code in the render loop.  Also not sure what the right answer is.

**Comment by Cervator** [comment]
Well, akin to the CrashReporter catching outermost exceptions/throwables, which would not be a thing for headless servers (yet?), we could add in catching for any crash that would be caused by a module then process it somehow.

You could ignore it and potentially risk worse damage than an immediate crash. Or you could halt the server, make a backup of the previous saved state, then attempt an emergency save + notify the user(s)/admin. Then leave it up to review for whether to accept the emergency save or last safe safe.

In this situation it was a failure to render an overlay (WorldRendererImpl.renderOverlays). That doesn't sound terrible, You *probably* could log a nice warning about that but then continue. We can treat each interaction point between the modules and the engine individually and determine the best action case by case.
