### ISSUE TITLE
BlackScreen (xOne controller)

### ISSUE THREAD

**Issue by Semedi** [MovingBlocks/Terasology#2200]
### What you were trying to do

Run the game (./gradlew game)
### What actually happened

Black Screen at the start
### How to reproduce

Only you need to do is try  run the game with a xbone controller plugged in your pc (Windows 10).
### Log details and game version

```
16:33:16.598 [ERROR] [system.err] mar 04, 2016 4:33:16 PM net.java.games.input.DefaultControllerEnvironment getControllers
16:33:16.598 [ERROR] [system.err] ADVERTENCIA: Found unknown Windows version: Windows 10
16:33:16.598 [ERROR] [system.err] mar 04, 2016 4:33:16 PM net.java.games.input.DefaultControllerEnvironment getControllers
16:33:16.598 [ERROR] [system.err] INFORMACI▒N: Attempting to use default windows plug-in.
16:33:16.598 [ERROR] [system.err] mar 04, 2016 4:33:16 PM net.java.games.input.DefaultControllerEnvironment getControllers
16:33:16.598 [ERROR] [system.err] INFORMACI▒N: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
```
### Computer details

Windows 10 (64 bits)
Gtx 970
##

**Comment by Cervator** [comment]
Thanks for the report :-)

Hopefully with this discovery we can reproduce this with another Win10 + controller scenario. I've been meaning to update my tablet to Win10 eventually so that'd be an option at some point.

By the way were you interested in GSOC or just general enthusiasm for open source? I don't see a contributor intro thread for you yet so I'm unsure :-)

**Comment by Semedi** [comment]
both things, i didn't know nothing about the presentations topics hehe:

http://forum.terasology.org/threads/hey.1460/

**Comment by skaldarnar** [comment]
Closing as likely fixed or not reproducible anymore.
