### ISSUE TITLE
Borders in FacetProvider `@Updates` have no effect

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#2260]
Currently, `WorldBuilder` does only compute the borders for updated facets when the updating facet is required somewhere else. I was wondering if this behavior is intended or not. 

To get a border for updated facets am I required to write a (dummy) provider that requires the updated facet?

@CptCrispyCrunchy encountered problems when trying to update the SurfaceHeightFacet with several filtering passes which require borders.  See https://github.com/Terasology/ShatteredPlanes/blob/master/src/main/java/org/terasology/CanyonWorld/GaussFilter.java#L40
The implementation for computing borders was last touched by @MarcinSc: https://github.com/MovingBlocks/Terasology/blame/develop/engine/src/main/java/org/terasology/world/generation/WorldBuilder.java#L113

Pinging @Josharias and @immortius for additional feedback...

**Comment by CptCrispyCrunchy** [comment]
I fiddled with the code a bit and my conclusion so far is that the current architecture won't allow this.
The problem with the loop is, that you can't ensure that the border for this particular facet is calculated because you would just request the exact same loop again with all variables staying the same. 
As I figured, the order of calculation is defined by @requires, so you can't make sure that you first calculate the "small" border and afterwards with annotated border as you would always come back to the same loop. Its hard to explain especially to this time so maybe I could have missed something entirely. 
inserted after the if(requires != null) bracket closes in ensureBorderCalculatedForFacet 
`else if (updates != null) {
                    for (Facet producedFacetAnnotation : updates.value()) {
                        if (producedFacetAnnotation.value() == facet) {

                            Class<? extends WorldFacet> updatesFacet = producedFacetAnnotation.value();
                            FacetBorder borderForFacetAnnotation = producedFacetAnnotation.border();
                            Border3D updatesBorder = borders.get(updatesFacet);

                            border = border.maxWith(
                                    updatesBorder.getTop() + borderForFacetAnnotation.top(),
                                    updatesBorder.getBottom() + borderForFacetAnnotation.bottom(),
                                    updatesBorder.getSides() + borderForFacetAnnotation.sides());

                        }
                    }`
this is what i came up with so far. As you can see you need to make sure somehow that the small border is already calculated so that borders.get(updatesFacet) wont get an nullpointer exception

**Comment by CptCrispyCrunchy** [comment]
So my proposal is to add something similar to the code above with a check if borders for this facet are null , then set them to default Region bounds (is there a method?) and then  continue with the rest. I'll try it out tomorrow.

**Comment by Cervator** [comment]
Just by chance I ran across #1912 which seemed somewhat related. Not border related but it has a bit of info that might be useful.

**Comment by msteiger** [comment]
Thanks for your suggestions, @CptCrispyCrunchy - I've updated your comments fixing the code formatting. Click on the edit pencil to see how the java-style format works.

I added the `@Updates` annotation to the requirements chain in the fix for issue that @Cervator mentioned. And yes, it does not include border updates. As I understand it, the `borders` area and its values are for input only, you should not write to them. Thus, it doesn't make to much sense in the `@Updates` annotation, imho, but I might be missing something.

What is the exact problem you're having?

**Comment by CptCrispyCrunchy** [comment]
Thanks for the code formatting @msteiger
Ah I see, it does make sense to explciitly  use the border area only as Input. If thats not the case Concurreny problems will likely occur. Didnt thought of that earlier.

However, the problem is that I need Information about adjacent blocks to determine a new block Position for the one in the center. That means I need a border area to see the position of blocks in adjacent regions. So I dont have to write to the border area but still need to request it in the @Updates.
For a further description and a picture, see the third picture in this thread:
http://forum.terasology.org/threads/canyons-updated.1492/

**Comment by skaldarnar** [comment]
@msteiger what about requiring a bigger (read-only) input to determine how to update the original area. What would be best practice for doing something like this? Adding a new facet for (each) processing (e.g., smothing, eroding, ...)?

```Java
@Requires(@Facet(value = SurfaceHeightFacet.class, border = @FacetBorder(sides = 8))
@Updates(@Facet(value = SurfaceHeightFacet.class)
```

**Comment by msteiger** [comment]
I think that this should work, yes. However, I'd prefer to properly integrate the `@Updates` annotation in the border calculation like @CptCrispyCrunchy suggests. Can you transform this into a PR?

**Comment by CptCrispyCrunchy** [comment]
Yes sure @msteiger, should be done this night. 
Even though it does not work currently? And do you have an idea how to solve the concurrency problem with this one?

**Comment by msteiger** [comment]
The concurrency problem is probably not due to usage from different threads, but rather from modifying the collection while iterating over it. The recursive method modifies the passed parameter.

**Comment by msteiger** [comment]
Why do you actually need this? The cliff-style terrain should be feasible entirely without the `@Updates` annotation. In similar terrain generators I used the original noise generator to look up values on a global scale.

**Comment by CptCrispyCrunchy** [comment]
Hm, this will quickly become a mess when you have several different providers which update the same facet. This would limit my style of terrain generation tremendously as you'd have to backtrack through several noisegenerators with different conditions.

Concerning the collection, I reversed my modification afterwards. So it should be the same or is the order of adding the pairs to the multimap important? 
The recursion itself shouldn't actively notice the modification from before.

**Comment by CptCrispyCrunchy** [comment]
I gathered some ideas and created a new issue in the shattered planes module 
->[here](https://github.com/Terasology/ShatteredPlanes/issues/3)
