### ISSUE TITLE
Potentially unify the giveBlock and giveItem commands

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2293]
After the work in #2290 and what came before it we might be able to just combine `giveBlock` and `giveItem` into a single `give` command with variants to accept only shapes for blocks, give a sensible warning if you asked for an item that can't be shaped, and so on.

There is a fair bit of overlap between the two commands, hopefully at least we can cut down on the duplication and in the best case completely unify them both.

Main trick is probably still supporting the different method variants based on parameters. Still probably not too hard to do.
##

**Comment by MaxBorsch** [comment]
@Cervator If they were to be completely unified, in which Commands.java file should the new `give` command be? ItemCommands, CoreCommands?

**Comment by skaldarnar** [comment]
@MaxBorsch I think `ItemCommands` fits the purpose better. Maybe we'll find a better name for it, the `giveItem` command seems to be the only thing implemented there. One could argue that the hand-held blocks are items of sort, so that should be fine.
There's always the option to change things later 😉

**Comment by Cervator** [comment]
Closing as completed by #2613! Thanks @MaxBorsch :-)
