### ISSUE TITLE
Add toggle / option to improve visibility of chat

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2376]
As suggested last multiplayer test session: the chat window (either in its full version or even the mini single line version) could have its visibility improved. At present it'll tend to be suppressed (even the one-line mini chat) when any other UI is up, and there's no way to leave it persistently visible (probably should be a toggle of some sort)

Probably not terribly difficult when used to our UI a little bit, although I'm not sure exactly how the ideal design would look / work. Open for ideas! :-)
##

**Comment by iojw** [comment]
@Cervator: Interesting issue 🙂. Not sure if I understood this issue correctly, but are you referring to how the chat is invisible unless you are typing something? From my tests alone, I did notice that you only see the chat history when you are typing in chat, which could annoying for some.

If that's the case, I think an possible idea to consider would be the leave the chat visible after anyone types something in chat for a period of time before fading away (maybe around 10 seconds). I managed to find an example of this in TF2 here - [https://youtu.be/VSKGX6yBWgQ?t=52 ](https://youtu.be/VSKGX6yBWgQ?t=52 )- you just need to watch it for a few seconds. We could also add a toggle button to toggle the visibility as you said if some prefer to hide the chat.

I'm not sure what you mean by the mini single-line chat though. How do you make it show up?

**Comment by Cervator** [comment]
That is exactly it yes. The window is only visible when you are actively interacting with it *or* briefly (as the mini single line chat) when somebody else sends a message. But that fades pretty quick and is only one line of text :-)

**Comment by iojw** [comment]
@Cervator : Hmm, would it then be better to keep the current behaviour and add a button to toggle the chat history or make the chat history fade out after a certain amount of inactivity (eg: https://youtu.be/VSKGX6yBWgQ?t=15)? Also, it seems the fade out times for the mini chat are hardcoded integers so it should be simple to change those values.

**Comment by iojw** [comment]
@Cervator: I attempted to address this issue in #2667 which got merged a while back, adding a few tiny features to bring the chat more in line with other games. 

I'm wondering if there are any additional features you guys would like to see on top of the changes already made or any other thoughts you might have.

As @oniatus mentioned, there's currently an issue whereby too much text might overrun the screen on the mini overlay, since it shows up to the last 6 messages with no char limit on individual messages. I'm leaning towards a line limit for the mini overlay to tackle this since I feel that the mini overlay is something that the player should not have to interact much with. I could fix this together with any new features you guys would like to see in the chat.

Looking forward to hear what you guys think! 🙂

**Comment by Cervator** [comment]
I'm pretty much happy with #2667 myself, could close this just with that done. For the line length could the overlay truncate at a certain line length, while a bigger chat panel of some sort would line-wrap instead, with scrolling?

Pretty rare you'd need to go back to catch a long message.

**Comment by iojw** [comment]
@Cervator: Scrolling is already present in the active chat overlay (what appears when you press T). The mini overlay is what appears when you're not in the active chat window and you receive a message from someone else (it has a translucent background, as opposed to the solid background of the active chat overlay). 

I'll submit a PR for truncation in the mini chat overlay soon, replacing the end with ellipses. I'm thinking that if players want to view the whole message, they can just open the active chat window instead.

**Comment by Cervator** [comment]
Yep exactly. I think this is pretty much done :-)

**Comment by Cervator** [comment]
Closing as completed by #2759
