### ISSUE TITLE
cant start with intel gpu hd5500 

### ISSUE THREAD

**Issue by chriscamacho** [MovingBlocks/Terasology#2393]
- Step 1
  run game
- Step 2
  fail to get graphics initialisation

running stable version

log
http://pastebin.com/KnNqAKbw
##

**Comment by Cervator** [comment]
Hi @chriscamacho :-)

Thanks for the extra comments in the paste. Do you have experience with upgrading LWJGL 2 -> 3? Do you think that would matter in this case? We often hit issues with Intel HD chips but usually on older hardware.

The full but quiet crash during initialization is more rare though, usually we get a cleaner complaint about the gpu missing features or outright visible graphic artifacts. Probably the 5500 being far newer indicates a different problem.

@emanuele3d and @tdgunes are at present working on a rendering overhaul. It doesn't involve upgrading LWJGL so far, and we're considering going directly to a LWJGL-3 based LibGDX instead. I haven't kept good track of the completeness of LWJGL 3, last I knew some of the extras were still being upgraded. If it can serve as an almost drop-in replacement that would be interesting, especially if that could show an improvement on this issue.

There are some more details on LWJGL 3 / LibGDX in #2099 although there it looks like the changes from LWJGL 2 to 3 are more substantial.

**Comment by chriscamacho** [comment]
I wouldn't just be a "drop in" sorry if I gave that impression, for 
example there is NO Display class

Instead you must open a "window" for yourself using glfw - however this 
shouldn't be an really that much of an issue....

lwjgl2 is substantially out of date and afaict no longer maintained

lwjgl3 works really nicely on my intel GPU well worth the effort

lwjgl3 has reached v3.0 and is stable and a sight easier to use.

libgdx while excellent for what it is does rather bring the kitchen sink 
+ lwjgl - I could see a lot of libgdx not being used, unless you're 
going to rewrite all the 3d stuff to use gdx's engine - which if you're 
already doing it with OpenGL alone seems counter productive...

**Comment by emanuele3d** [comment]
Hi @chriscamacho, unfortunately the very last line of the log you provided hints to an unsupported GPU. Specifically, integrated GPUs are known to cause problems as they do not support all the OpenGL features Terasology takes advantage of. Which is peculiar though as this particular card supports OpenGL 4.3 while we use ancient OpenGL 2.1 plus a few extensions that have later been included in OpenGL 3.0. My suspicion is that it might be these extensions to cause the failure: they probably haven't been implemented because they are provided by the 3.0+ implementation.

In the medium term the rendering engine is being opened up to have an extendable architecture that, in the longer term, might lead to alternative rendering engines, i.e. taking advantage of the latest OpenGL features or providing support for older platforms.

In the short term I'm afraid your best bet is to play Terasology on a system with a discrete GPU. 
Sorry I can't be more helpful at this point.

Thank you for your assessment of LWJGL 3 and LibGDX. It's good to know.
