### ISSUE TITLE
OpenGL unit test suite

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#241]
I think we need to find or write a suite of simple unit test exercising some of the OpenGL features we use, per graphic detail level. Wouldn't it be sweet (pun intended) to be able to have users run a command to get back exactly what level (if any) their system will be able to support? Might also help catch some of our tweaks to deep 3d wizard code.

I figure there's a way to write unit tests like that you could both run during development (and during builds, tho those will be specific to the build server and might be tricky if they need to open a graphic window to test), then expose the same functionality via command-line switch to the game executable, or alternatively as a separate downloadable utility?

**Comment by emanuele3d** [comment]
So, am I understanding correctly that with this issue you'd like to have a number of visual tests, in the form of immutable scenes that get rendered into screenshots every build, to be compared pixel for pixel with previous builds to make sure no unwanted visual changes are introduced?

It's not a bad idea, I wouldn't necessarily close the issue just because LwjglGraphics.checkOpenGL() now is a bit more specific. It's a bit of work as we'd need (at least):

* to be able to load a specific saved game via command line
* to be able to automatically render (bypassing menus and all things interactive) said saved games into one screenshot at a specific resolution, presumably from the position of the player saved in the file (speaking of which, right now only the position is saved, not the camera's orientation, I think). This code should also ensure that game time is frozen, or things such as water surfaces and skysphere will show different things.
* write a comparison software that checks things pixel per pixel or whatever other criteria
* ideally also write a per-pixel diff generator
* come up with a way to quickly inspect side-by-side and diffs of the images
* come up with a list of what should be tested

Is this somehow in the direction you were thinking?

**Comment by Cervator** [comment]
That sounds about like what younger more naive me was dreaming about, yep, but that was a long time ago. Now there is more cynical seasoned me who doesn't even get my own pun from 2012, and would be ready to close this in return for game start logging saying which OpenGL feature a user's system doesn't support, haha :-)

I figure we can probably still close this simply from better logging, since we're getting very exact about that now. I would hugely enjoy seeing more progress here, but it is probably more of a long-term WIBNIF, like the big acceptance test world and headless clients. Which could probably also support this sort of testing - rather than a save game that'll go out of date at a technical level a world meant to generate the same way every time should also be able to take the same screenshots each time.

**Comment by msteiger** [comment]
Maybe a simple version of what @emanuele3d envisioned could be realized with TeraEd. I can't even launch it, so it might need some brushing up first.

**Comment by emanuele3d** [comment]
Are you calling me young and naive @Cervator? Because I'm definitely naive, but YOUNG!!! Absolutely not. =D

I'm happy to go with your judgement about closing this issue. It's not something I'd want to get into. There's plenty to decrypt and do for me already. =)

**Comment by Cervator** [comment]
Haha, naive can be good, it gives you dreams!

I'm closing this as adequately addressed considering the constraints. I've put some pie-in-the-sky notes for the future in the fancy test world thread: http://forum.terasology.org/threads/the-world-of-varied-and-noteworthy-achievements.1209/#post-11230
