### ISSUE TITLE
Graphic artifacts possible after changing video settings in-game

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2418]
Found this while testing #2399 but confirmed as pre-existing in Omega build 510 (July 19th 2016)

Appears to only activate with animated water _and something else_ enabled. I didn't narrow down the other factor but if I set graphic detail to Ultra and enable everything else it showed up. Disabling animated water made it go away again. Leaving graphic settings on default + animated water however did _not_ provoke the issue.

Considering this low priority as the animated (waving) water is somewhat tricky on its own, see  #1477

Screenie demonstrating the artifacts - curious if anybody else seems them as well (Radeon line of GPU here):

![terasology-160725235702-1152x720](https://cloud.githubusercontent.com/assets/1063833/17125863/632bcda8-52c5-11e6-837b-4902f734a9a5.jpg)
##

**Comment by tdgunes** [comment]
Thanks for reporting this one @Cervator. I'll look into this.

**Comment by Cervator** [comment]
Cool, keep an eye out if you like but don't worry about it vs. more important stuff for now :-)

**Comment by Cervator** [comment]
Another observation: parallax mapping is likely related (another immature option that may have never been fully finished or broke after it was). Found a combination where I could disable animated water yet still get the artifacts, disabling parallax mapping after that then removed the artifacts.

**Comment by emanuele3d** [comment]
Managed to reproduce it on an nVidia GPU (860M). It's quite erratic though: it's not always straightforward to reproduce. It seems to be a more general problem though. Many settings when changed seem to display problems. For example, disabling motion blur made the screen go black at one point. I managed to reproduce it multiple times and then I couldn't anymore. Also, the animated grass settings seems to be ineffective: the grass remains always animated.

So, perhaps we should rename this issue to something more general, like Graphic Artifacts and video-settings problems.

**Comment by Cervator** [comment]
Renamed!

**Comment by 4Denthusiast** [comment]
It looks like this is caused by the default bump-map texture being all 0, which when interpreted with an offset of -0.05 leads to everything having an offset, which with parallax-mapping enabled leads to it attempting to fetch textures from beyond the edge of the correct one, hence the bands of different colours near the edges of blocks. For some reason the minimal settings I can reproduce this on are Parallax mapping + Extra lighting, which makes me suspect that parallax mapping doesn't work without extra lighting.

The most sensible way I can think of to fix this would be to set the default (flat) bump-map to the correct level, then require that all custom bump-maps take are flat around their edges, or clamp the texture coordinate in the shader to the correct square (that way it can render more nicely in one direction at least).

As this issue makes the parallax-mapping very obvious, it also makes it clear that there's something wrong with the calculations involved.

In trying to explain the cause, I seem to have convinced myself of the solution, so I'll go and try to implement that now.
