### ISSUE TITLE
Auto-select of picked up items with full quick access slots

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#2422]
Picking up a new block or item when your quick access slots are all occupied will put the new block/item in your hands nonetheless. 

I guess that the player is autoselecting the newly picked up stuff, regardless of the access slots. Probably easy to fix, was working in the past.

### How to reproduce

* fill your quick access inventory slots (e.g., repeating `giveBlock stone 99` ten times)
* pick up a block or item that's not already in your inventory (e.g., pick a flower or dig dirt)
* you are now holding the new block/item in hand, although the quick slots are all full.

**Comment by Harshil7924** [comment]
Hey...I want to contribute to this project. I am a newbie in Open Source world. Can you please help me to get going?

**Comment by Harshil7924** [comment]
Can you please elaborate more on the issue? I am a newbie in OpenSource and want to contribute to the issue.
Thanks.

**Comment by skaldarnar** [comment]
Hey @Harshil7924 and welcome!

Have a look at our [Quick Start Guide](https://github.com/MovingBlocks/Terasology/wiki/Dev-Setup). In particular, you should familiarize with our [Entity System](https://github.com/MovingBlocks/Terasology/wiki/Entity-System-Architecture).

For this issue you might start investigating at `org.terasology.logic.inventory.ItemPickupAuthoritySystem#onBumpGiveItemToEntity` which handles the item pickup.

**Comment by Cervator** [comment]
Hi @Harshil7924 and welcome to the project :-)

Are you using IntelliJ? You're already set up pretty well if you're running from source. For one way of narrowing down where the code related to this is I did as follows:

* Searched for "giveBlock" in IntelliJ, found my way to `BlockCommands.giveBlock`
* Figured `GiveItemEvent` was involved (the event that happens when a player gets an item/block)
* Ran a "Find Usages" in IntelliJ on `GiveItemEvent`, found `CharacterInventorySystem.onGiveItemToEntity`
* Noticed `inventoryManager.giveItem` and found two implementation classes for `InventoryManager`
* Looked around in those two versions for a bit for something that seemed related. One is server side management, the other client side. Eventually I found a `InventoryUtils.putItemIntoSlot` in `InventoryAuthoritySystem.giveItemToSlots` that seemed promising
* That method triggered a `InventorySlotChangedEvent` which led to another round of hunting event handling, leading me back to `CharacterInventorySystem` specifically `syncSelectedSlotWithHeldItem` - aha! Now we're getting somewhere interesting
* The little bit of logic in that method seems to compare slots and if equal switches the held item. So *something* is probably missing or broken about that condition. Either the equals is bugged or we need to add a new condition.

I'm not sure beyond that, would have to start running the game in debug mode or add some logging to find out what's going on in that method. I'm not super familiar with our inventory code but the kind of detective work above I can do and that'll serve you well pretty much anywhere. Good luck and let us know if you have any more questions! :-)

One thing to watch out for if you aren't used to IntelliJ: "Find Usages" will try to be smart about inferring what you're looking for. So if you highlight the name of a class being constructed it'll only show you places where that class is being constructed, not just used in general. Alternatively you could simply do a plain text search (CTRL-SHIFT-F) and look for stuff that way.

**Comment by mtjvankuik** [comment]
I seem to be unable to reproduce this issue. I'm running on the latest Terasology version build from source, java JDK8 and followed instructions with and without inventory space. All 1-10 quickslots were filled with 99 blocks. 

Is it possible to provide a more detailed description of the bug? Or it is possible that this issue is already fixed?

**Comment by Cervator** [comment]
I just tried and yeah I can't actually replicate either. Tried both single player and multiplayer. @skaldarnar did you have any particular modules enabled, or any chance something was acting up in your workspace?

**Comment by skaldarnar** [comment]
Cannot reproduce it either :confused: Closing for now, can still reopen if it happens again.

**Comment by Cervator** [comment]
@Harshil7924 let us know if you find something else that looks interesting for you, or would like some guidance on anything :-)
