### ISSUE TITLE
giveblock command with quantity not working on a local secondary client 

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2430]
Wonder if somebody can confirm this:
- Start two instances of the game locally, like with the regular and 2nd client run configs in IntelliJ
- Host a Core + CheatsForAll game with one
- Join with the second client
- `giveblock stone` should work fine for both clients
- `giveblock stone 99` for me only worked on the host player, 2nd client player got no blocks and no output?

That seems an oddly simple command variant to not have working in multiplayer. Maybe something simple.
##

**Comment by nitram509** [comment]
Hi,

I'm trying to reproduce this issue, but unfortunately it behaves differently than described.
After activating the cheating mode, only the player who exec 'giveBlock stone' receives the stone, but nobody else.

What's the expected behavior?

### Background Information

I'm starting the processes like this:

1. start "TerasologyPC (headless)" run configuration in IntelliJ
2. start "TerasologyPC" run configuration in IntelliJ -- a.k.a. Player 1
3. start "TerasologyPC (2nd client)" run configuration in IntelliJ -- a.k.a. Player 2

My workspace I've prepared like this:

1. gradlew fetchModuleCheatsForAll
2. rename folder "modules/CheatsForAll/overrides/engine/..." to "modules/CheatsForAll/overrides/assets/..." to match core clientInfo.prefab file path
3. Cheats still don't work 
4. manually copied content from clientInfo.prefab from CheatsForAll to core/engine file

**Comment by Cervator** [comment]
Hi @nitram509 and thanks for checking into this, was really curious if somebody else could replicate :-)

To be clear `giveblock stone` *should* only give the player who executes the command the stone blocks, nobody else. Same with the quantity version. But the oddity came about when `giveblock stone 99` solely worked as a host player (client+server). If a secondary connected client attempted it then nothing would happen - yet the `giveblock stone` worked fine.

In your setup you're using headless + two standalone players (just plain clients), meaning *neither* player is a "host player" (which means you'd be running as authority/server as well, with all cheats and debug commands live by default). So in that case I expect you wouldn't see the difference - the two players would see identical behavior.

I just re-tested the host player + secondary player and it remains the same. The bug described might as well be "Quantity-based versions of `giveblock` do not work in multiplayer" - it was only by chance that I noticed that if the multiplayer game is hosted by a regular player running the game (rather than headless) then it *does* work for that player, indicating it is likely an issue about how the command is being run (works on an "authority" client, but not elsewhere). If the headless server could issue its own commands it would work there too, in theory.

Likely there are more cases like this than just the quantity based `giveBlock` - see #1942, #1690, #1619, or #1208 (some may be obsolete by now). Even PR #2217 attempted a similar fix, resulting in some discussion of how to better handle it. Right now the topic has just sort of gone quiet, but with somebody willing to spend a little effort on it I'm sure we can sort out a bunch of these issues in one fell swoop :-)

As for `CheatsForAll` you just need it enabled. I don't know of any need to copy/move/rename things around. Might have just come from not catching the subtleties of the bug? When you use a player to host you can enable the module on the create game screen ([enabling it for a headless server is a bit more involved](https://github.com/MovingBlocks/Terasology/blob/develop/docs/Playing.md#configuring-a-server))

**Comment by portokaliu** [comment]
I've discovered the issue with this one.

When processing the client's command on the server, in the `ConsoleSystem` (through which all commands that have "`runOnServer = true`" go), if the command doesn't meet the specific number of parameters `requiredParameterCount` (default 1), the command will not be run at all. 

My opinion would be that we should have a min and max number of parameters for obvious reasons (runOnserver commands might have variable argument numbers, as is the case in point). I'm not exactly sure how an error is returned to the client (if any) .... (something really should tell the client he's ignored), but that's not what this issue is about :)

**Comment by Cervator** [comment]
Closed as fixed by #2600 :-)
