### ISSUE TITLE
"title" font does not support non-ASCII characters

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2446]
The custom font used in popup titles ([title_0.png](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/fonts/title_0.png) & [title.fnt](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/fonts/title.fnt)) only supports ASCII characters, causing issues with several internationalized strings. Since it appears identical to the `NotoSans` font family, replacing it by a medium-sized `NotoSans` would be one potential fix.

### How to reproduce

Go to Main Menu → Join Game → Custom → Add New and view the popup's title (normally "Add/Edit Server") with different locales on:
- Japanese/Russian/Ukrainian - the title is blank.
- Czech/Romanian/Swedish - some special characters from the internationalized strings are missing from the title.

**Comment by Cervator** [comment]
Thanks for the observation, the prescribed fix sounds fine. Are you intending to do it since you applied the Alpha4 milestone? I usually only throw that on there when a thing has already been done or will be in the very near future :-)

**Comment by rzats** [comment]
@Cervator: yep, I'll submit it in #2438 along with various other features.
Though maybe the font should be removed altogether, if it's not used by any module other than `engine`? #2036/#2042 appear to suggest that it should have been removed already.

**Comment by Cervator** [comment]
A plain search for `"title"` (including the quotes since otherwise you'd find all kinds of stuff) still gets 72 hits in my mega-workspace.  Some of those are just the actual *key* in a JSON file, not the value though.

Looks like the `Equipment` module has two legit hits in `CharacterScreen.skin` and `CraftingStation.skin`

`StructureTemplates` has two hits in `StructurePlacementFailureScreen.ui` but I guess that's something else. `"family": "title"` is probably not directly font related, right? That bit is all over the place.

`deathScreen.skin` uses it for sure, like `popup.skin`. As do `messageBox.skin`, `onlinePlayersOverlay.skin`, and `pauseMenu.skin` - I think those are it. Am guessing the few other places can have the same fix applied.

**Comment by rzats** [comment]
@Cervator: thanks for the search! `"family": "title"` is fine since it's just a pointer to a family in the skin.

Changing the font in `Equipment` might be a bit of a problem if the font is deleted from `engine` - AFAIK, several modules depend on `Equipment`, so removing the font might break the entire dependency tree. How would I handle this?

**Comment by Cervator** [comment]
Equipment is one of @xrtariq2594's with @flo being the one other user in GooeysQuests. Pretty minimal impact so I would just include the font change here then update Equipment. I don't think GQ would even need to be rebuilt.

**Comment by xrtariq2594** [comment]
Sure @Cervator . A simple font change shouldn't cause too much of an issue. Just make sure the new font isn't too big though.

**Comment by msteiger** [comment]
Actually, `NotoSans-Regular-Large` can/should be used for large text. The old "title" and "default" fonts are still around for compatibility reasons. Maybe this is a good point in time to update modules and remove them.

**Comment by Cervator** [comment]
Bump. I think we covered this issue as written, so it could be closed and considered part of Alpha 4. But we haven't deleted the obsolete fonts yet, or made tweaks. So I figure we should make a new issue for that then close this one?

@rzats could you confirm?

**Comment by rzats** [comment]
@Cervator: the original issue is indeed fixed, so closing this issue :smile:
