### ISSUE TITLE
"title"/"default" fonts should be removed from the module lineup

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2472]
Several modules still use the old `title` and `default` fonts in their skin files. These fonts have issues with non-ASCII characters (see #2029, #2446) and have been replaced by NotoSans fonts for a while now, so they should be removed from the game altogether.
- [ ] Remove the uses of the font in [Terasology/Equipment](https://github.com/Terasology/Equipment) (`CharacterScreen.skin` and `CraftingStation.skin`), replacing `title` with NotoSans-Regular-Large and `default` with NotoSans-Regular-Medium.
- [ ] Verify that the fonts aren't used in other modules. If they are, also replace them.
- [ ] Remove the font files from engine!
##

**Comment by Cervator** [comment]
Linking to https://github.com/Terasology/Equipment/pull/2 which catches the two hits there.

`deathScreen.skin` in the engine ~~appears~~ appeared to be the only other usage of the old font. I tried a RegEx search for `"font.*title"` but am still not entirely confident in my RegEx skills ...

Actually without quotes that found a few more candidates outside of prefabs:

![find in path_2016-10-03_16-15-37](https://cloud.githubusercontent.com/assets/1063833/19052420/b59f5898-8984-11e6-9096-b74d2531c0b7.png)

Checking for `engine:title` then got 8 hits instead of 7, mostly overlap:

![find in path_2016-10-03_16-17-10](https://cloud.githubusercontent.com/assets/1063833/19052481/fe4627ac-8984-11e6-8921-8616c70dca09.png)

So that gets us more module hits again :(

- [ ] Journal
- [ ] Tasks
- [ ] InGameHelp
- [ ] WoodAndStone
- [ ] ModularComputers
- [ ] WorkstationCrafting
- [ ] Potions

Also worth noting is that "title" is sized in between regular and medium.

**Comment by n4n0byte** [comment]
Just finished removing the old font from the epuipment module, and will start on the rest of the modules soon (I need to download them). Is there a way to download all of the modules for to check? Also how would do you submit changes? (pushing gives a 503 error). Sorry for all of the questions i'm still kind of new to this.

**Comment by skaldarnar** [comment]
Hey @n4n0byte, sorry for the late answer. Quite some things to do with GSOC right at the start.

This repository is protected from arbitrary pushes, that's why you cannot push directly. Instead, you push to your _fork_ (`github.com/<username>/Terasology`), and create a Pull Request (PR) from there against this repository (`github.com/MovingBlocks/Terasology`).

Read through the [starter guide](https://github.com/MovingBlocks/Terasology/wiki/Dev-Setup) and some basic information on git itself to get a better understanding of how all this works: https://git-scm.com/book/en/v2/Getting-Started-Git-Basics

**Comment by jellysnake** [comment]
Was going though and testing all the PR's related to this issue before I merged them as well as making fixes to other modules.

Is there actually a particular reason why we don't name the new fonts `engine:default`, `engine:medium`, `engine:large` and `engine:title`.
The NotoSans font `NotoSans-Regular` is the same size as the existing `engine:default` and `NotoSans-Regular-Title` is the same as `engine:title`
