### ISSUE TITLE
Download/File Transfer API

### ISSUE THREAD

**Issue by SoniEx2** [MovingBlocks/Terasology#2483]
An API for downloading/uploading/transferring files would be nice. It'd allow for fully-featured programs to run inside terasology.

Possible programs include:

- A music tracker/sequencer. (Minecraft Note Block Studio clones?)
- A modeling program. (VoxelShop?)
- A file transfer program, to transfer files between users.

**Comment by Cervator** [comment]
Please use suggestion threads for such substantial enhancements, especially when they are nice extras rather than critical for something central (file transfer seems like a very rarely needed thing in modules). It isn't likely to happen in the near future unless we have a volunteer, so these kinds of issues clog up the issue tracker :-)

http://forum.terasology.org/forum/suggestions.21/

You can also check out our asset system, as that would likely be involved or could even satisfy some requirements. The idea there is that modules can access assets, and some asset types might be offered special recognition by the engine to do things like being linked to a file on the user's system that's considered safe in some fashion (limited chunk of storage in a specific game directory, no direct file system access)

https://github.com/Terasology/TutorialAssetSystem/wiki
