### ISSUE TITLE
`giveBlock air` crashes the game

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#2524]
### How to reproduce
- Start a game
- Type `giveBlock air` in console

Game should crash and loading the saved game should crash the game again.

Perhaps an easy fix. There is a need to filter out the "engine:air" block in console command `giveBlock` as suggested by @Cervator.
##

**Comment by MercuryHunter** [comment]
Hi, I was unable to reproduce the issue, could it be platform specific? I'm running this on Mac OS Sierra.

When I tried giveBlock air, it just responded with "You received 16 blocks of Air" and continued but with an empty hand.

**Comment by pollend** [comment]
It happens when you pick up an air block. #2466

**Comment by Cervator** [comment]
Thanks for chiming in @MercuryHunter and appreciate the reminder @pollend - I do remember that issue coming up.

We could treat this issue as just covering the ability to get an air block via console, and still approach a better fix for #2466 - maybe we can catch that one where it attempts to use a mesh for any air block or perhaps other weird/meshless things?

**Comment by portokaliu** [comment]
Interesting bit of information : I tried the command while having the hotbar full, it just gave me 16 blocks of air. I tried to look in the inventory to look at them and only then did it crash.

**Comment by portokaliu** [comment]
Alright, I've managed to find the reason for this specific block having problems.

The block itself can't get a mesh event though the game tries to give it one because the block family doesn't have a meshGenerator, and that in turn is because the it's "invisible". I mean, it makes sense for the "invisible" value to be there ( could be used for other purposes as well [maybe AI?] ), but preventing invisible blocks from having a meshGenerator... dunno
