### ISSUE TITLE
After changing windowed/fullscreen mode the window can no longer be resized

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2532]
When back in windowed mode, naturally.

So in other words: Change the game to fullscreen, switch back to windowed, try to resize the window (the maximize button also goes inactive). Works fine _before_ switching the mode.

Discovered while testing #2519 but not caused by it, just coincidentally was an obvious test case there.

As per research by @coty91 this appears to be an LWJGL issue that is fixed in a later (v3+) version, but that's probably a bit much effort solely to fix this bug. Although we may well want to go there - may be easier to first jump to a newer LWJGL rather than aim for LibGDX immediately.
##

**Comment by AfterRebelion** [comment]
Did some testing, and the problem seems to only show if you change from windowed mode to fullscreen, and then again to windowed. If you launch the game in fullscreen, and then go to windowed, it lets you resize the window just fine.

After some searching, the only site I found that list this error is [the Minecraft Bugtracker](https://bugs.mojang.com/browse/MC-68754)
On the [LWJGL bugtracker](https://github.com/LWJGL/lwjgl/issues) doesn't seem to be any related bug listed.
Also tried with the latest [LWJGL2 snapshot](http://ci.newdawnsoftware.com/job/LWJGL-git-dist/lastBuild/artifact/dist/), with the same result as above.

**Comment by Cervator** [comment]
Thanks for the extra note @AfterRebelion  :-)

@coty91 just mentioned having done the research, but am unsure what he found via Google where. 

Keep in mind LWJGL 3 switched to a new repo / issue tracker, so there's no guarantee it'll be tracked in the legacy version. And yeah I wouldn't expect the latest from 2 to make a difference, yet hooking up 3 would likely be some serious work.

**Comment by jdrueckert** [comment]
Cannot reproduce anymore. We upgraded to LWJGL3 in the meantime, so I guess that fixed it.
