### ISSUE TITLE
Add a button to display the CrashReporter in the main menu

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2577]
### Description

When Terasology encounters a fatal exception, a lightweight Crash Reporter application is launched, allowing users to report the error using various methods - upload the crash log to Pastebin or Google Drive, file a GitHub issue and so on.

![Crash Reporter screenshot](https://raw.githubusercontent.com/MovingBlocks/CrashReporter/develop/images/2015-02-05-wizard-page1.png)

However, non-fatal errors and bugs cannot be easily reported using the Crash Reporter interface - the user will have to manually locate the game log then report it using whatever method they can think of. A button that'll open the Crash Reporter under normal working conditions would help report these non-critical issues.

### Definition of 'Done'

- A button is added to the game's pause menu that opens the Crash Reporter interface, showing the game's current log.
- _[Optional but nice to have]_ The Crash Reporter itself is reworked to have a "non-critical" mode that changes several strings and interface elements to remove any mentions of a crash having occurred (e.g. in the screenshot above, "A fatal error occurred" is changed to "Current game log" and the red warning icon is changed to something more neutral). This mode should be used when the Crash Reporter is launched manually.

### Required skills

The issue involves working with the game's codebase and requires intermediate level Java skills.

### Where to start?

- The crash reporter can be launched using `CrashReporter.report(Throwable throwable, Path logPath);`.
  - The exception being thrown should be a dummy, since no critical exception actually occurs.
  - The path to the game log can be retrieved via `LoggingContext.getLoggingPath()`.
- Adding the button to the pause menu requires modifying its asset file ([pauseMenu.ui](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/ui/ingame/pauseMenu.ui)), as well as the code-behind class ([`PauseMenu`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java)). For a quick overview on working with interface screens, check out the [NUI Quick Start](https://github.com/Terasology/TutorialNui/wiki/Quick-Start) tutorial!
- The optional item will require working on the Crash Reporter itself, which is located in an auxiliary repository: https://github.com/MovingBlocks/CrashReporter.

**Comment by segfault802** [comment]
I'd like to work on this over the weekend, seems pretty straightforward.

**Comment by segfault802** [comment]
I've got the main part of this working.  I put the button to the left of the dev tools button on the pause menu.  Should I add a button to the main menu also?  That was the original goal of #1120 before it was closed in favor of this one.

I did run into an issue with the dependencies which I'd appreciate some input on.  Adding the crash reporter dependency (back) to the engine using the same stanza as the PC facade causes the game to crash if the crash reporter is built from source, I think due to two google libs defining the same namespace:

    guava-19.0.jar
    guava-jdk5-13.0.jar

I'm not sure where the second one is coming from, but in any case the game runs fine if the engine build.grade pulls in the crash reporter binary like it did before.

I haven't looked at the crash reporter itself yet for the optional item.

**Comment by skaldarnar** [comment]
You can use `./gradlew dependencies` to get a dependency tree, e.g., `./gradlew :facades:PC:dependencies`. Maybe that helps to find out where the second lib comes into play.

**Comment by Cervator** [comment]
This is completed simply pending time to go and merge #2584 which might involve some tweaking of dependency stuff - been having a hard time even staying on top of that much with the hectic chaos GCI brought us :-)

I wanted to add a note here about https://github.com/MovingBlocks/TerasologyLauncher/pull/392 by @iojw bringing something related to the Launcher, where the main menu ends up holding a little caution icon that can list warnings. It would be great to have something similar in the main game - whether that should be handled by the CR button or something like the log listing in the launcher (could they be merged together?) is an open question that needs a bit more thought.

That would also relate to #1402 which is about actually detecting more issues we could then list in-game.

**Comment by iojw** [comment]
@Cervator: Bringing attention back to #2584 as I've managed to fix the dependency issue pending a PR in the CrashReporter repo. It should then be ready to merge once the engine build.gradle has been updated as well to use the "fancier" method. 🙂 

Might be worth leaving this issue open since I feel that the "optional" feature mentioned in the main post would be a good thing to add for the user to differentiate between fatal and non-fatal errors. I also agree that it's important to increase the visbility of warnings and errors thrown by the game since they can be often overlooked. I really like the idea of expanding the log listing in the launcher so that it includes the game logs as well. The caution icon could then be updated to show game warnings/errors on hover as well.

**Comment by Cervator** [comment]
@iojw I went ahead and split out the optional feature here to https://github.com/MovingBlocks/CrashReporter/issues/35 but also mentioned more in https://github.com/MovingBlocks/Terasology/issues/2765 including stealing your fix from https://github.com/MovingBlocks/TerasologyLauncher/pull/392 - wee!

This issue auto-closed as fixed, which is fine since that way we can keep this as a completed feature as part of Alpha 7.

Probably I didn't describe all the details in the best way possible so feedback is appreciated!
