### ISSUE TITLE
Host Items at (0,0,0)

### ISSUE THREAD

**Issue by portokaliu** [MovingBlocks/Terasology#2605]
What you were trying to do:
I was investigating physics on a client.

What actually happened:
While working on said physics (and items going through the ground), I saw an entity really low in the ground (with the client). After getting there, I saw it was an axe that I tried to collect and couldn't. I changed the item on the host to a torch to also go down and investigate, and now the client saw a torch (host doesn't see anything)

How to reproduce:
1. Join a local server (not headless) with a client. 
2. Go to (0,0,0). 
3. Observe the host wielded item.

Details:
I only had Core+CheatsForAll active

**Comment by Tropid** [comment]
I'd be interested in working on this.

**Comment by Tropid** [comment]
As far as I can tell the wielded items are not visible to other players at the moment?

So the host wielded item is incorrectly replicated to the clients.

**Comment by Tropid** [comment]
I found the reason for this:

As soon as a player picks up an item, the host removes some components from the item and adds the entity reference to the authority inventory. The location component is removed, but not the mesh component. That's why the block is displayed at (0, 0, 0).

The host uses the entity for the `FirstPersonClientSystem`. So just removing the mesh component is not a solution. A possible solution could be making the mesh only visible to the inventory owner (add the mesh component in the `FirstPersonClientSystem`).

**Comment by Cervator** [comment]
Re-opening this as reverted by #2806 - see it for details. In short this ended up causing some other problems, although it still may be a viable fix. The Components filtered *may* just need some adjustment, but it will need some more thorough testing to make sure it is a clean fix :-)

May also be of interest to @iojw or even @xrtariq2594 since it is about networking and may somewhat relate to similar oddities about synchronized entity state (like the crash on trying to upgrade a wood workstation in NeoTTA)

Hi @Tropid! Hoping you're still around and might be interested in looking at the added challenges within this fix :-)

**Comment by Cervator** [comment]
Screenie to help explain the issue for those having a hard time visualizing it (like me at first):

![2017-03-05 00_14_01-terasology - c__dev_terasology_git_terasology - engine - _engine_src_main](https://cloud.githubusercontent.com/assets/1063833/23584915/6aff6874-013d-11e7-8ce7-6056d97e56ca.png)

**Comment by Tropid** [comment]
That was some time ago, but as far as I remember this is what I did:

Previous State:

* An entity which can be picked up will be added to the inventory of the player
* Depending on whether it is selected in the toolbar it will be shown or hidden by adding/removing the MeshComponent (not quite sure, maybe it's also the RenderComponent)
* Somehow the location component was removed on the clients (or only added on the host? I can't remember)
* Overall it was rather complex and difficult to understand in my opinion

Therefore I applied the following changes:

* When an item is picked up it is added to the inventory like before
* Additionally a client-only copy of it will be created which is responsible for client-side display
* Components which are not needed for display will be removed from the copy (this includes the components which are responsible for emitting light, see #2788)
* When the item is selected the client-side entity will be attached to the player and shown to the client only

I suggest following changes, which I will submit as a PR soon (I'm sorry I can't spend a lot of my time as I'm currently writing my master's thesis):

* Same approach as before, but instead of only keeping the components responsible for rendering (whitelist), I will only remove the unneeded components (blacklist)
* This applies to:
  - NetworkComponent: Prohibit replication of client-side entity
  - RigidBodyComponent: Prohibit held item dropping to the ground after selection

I still prefer copying the held item, as I think it makes reasoning about it a lot easier. Otherwise the entity in the inventory is the same entity which is shown to the player and there are a lot of different things affecting the behavior.

Maybe PR #2789 is also interesting in this context, as it overhauls the inventory system.

**Comment by Cervator** [comment]
Thanks for the response @Tropid ! I was wondering if switching to a blacklist might help, just didn't have the time to try it out. Would be happy to see a follow-up PR :-)
