### ISSUE TITLE
Improve Weblate translation

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#2621]
As pointed out by @tdgunes the English _placeholder_ strings copied over from the default language files suggest a finished translation to weblate. Even if all strings are marked as **fuzzy** it is presented as a complete, but fuzzy translation.

### Definition of Done

- A newly added language shows up as 0% translated in Weblate
- Adding a language should be possible through the weblate interface (preferably, without additional manual interaction by devs)

### Where to start?

- Weblate doc on language files (we use JSON for the game and plain properties for the Launcher)
- Weblate doc creating new language files from a templates

**Comment by Cervator** [comment]
This might be great timing for http://weblate-testing.terasology.net/ to be floating around, since we can test in a different branch and on a different Weblate, just so we don't bowl anything over or get any sort of mess in the main history :-)

@qwc might be playing with that server at times, but he's usually around on IRC or Slack to coordinate with.

**Comment by qwc** [comment]
"might be playing". Yep, currently down. :P

**Comment by skaldarnar** [comment]
We are no longer using weblate. 
Closing as outdated.
