### ISSUE TITLE
NullPointerException of some kind. I'm new, sorry.

### ISSUE THREAD

**Issue by RepComm** [MovingBlocks/Terasology#2663]
### What you were trying to do
Hitting a Pine tree log attempting to obtain it in all of its woody greatness...
### What actually happened
The end of the stack trace said NullPointerException, so.. (Again, I'm new. I just submitted incase it helps!)
### How to reproduce

* Step 1
Login to 'official Stable' server
* Step 2
Hit some random pine trees
* Step 3
Make it crash on purpose if that didn't do it, so I don't look like a newb. kthxbye

### Log details and game version
https://drive.google.com/uc?id=0B5l2RT_UOCXRclQ4RmZSTHNMVlU&export=download
This is what you need right?

### Computer details
Win. 8 Hp Laptop 4g ram, 4g gpu.. Not sure what you want here really. I don't do this often..

If this isn't at all helpful, I'm sorry. I just vaguely wanted to participate in helping devs if at all possible.

**Comment by Metatricity** [comment]
Looks like an issue with the rendering system. I'm not super advanced with OpenGL or anything, but there is a vague description for you.

**Comment by emanuele3d** [comment]
Hmmm... no, although it's true this is connected to the rendering engine, this is not an OpenGL thing, so it shouldn't be a matter of GPUs.

It appears the (non-rendering) engine is passing a null object when it should pass a chunk, a chunk being the data structure holding the information regarding a 32x64x32 (blocks) chunk of the world.

I think this is a problem that has come up already and there might be an open issue about it. @Cervator ?

**Comment by Cervator** [comment]
Heya @RepComm - yep this is a known issue, documented primarily in #2590

It happens while the rendering system is active, but has something to do with duplicate chunk loading. Like something that normally happens only once gets queued up twice and then processing is attempted the second time and something fails.

No current workaround is known, but it seems non-destructive - as in, you can join again and everything seems fine (since chunks at that point reload). We need to identify this problem more closely when somebody is available to dive deeper into the chunk loading process.

**Comment by Metatricity** [comment]
I agree. I'll see what I can do to help fix the problem in the meantime.

**Comment by RepComm** [comment]
In the mean time it may be useful to add a try-catch at the point in code that it fails (where expecting a chunk, but getting null) and simply cancel that loading attempt. I may have a look later.

**Comment by keturn** [comment]
Closing as stale.
