### ISSUE TITLE
All graphics become white when switching from fullscreen to windowed

### ISSUE THREAD

**Issue by Metatricity** [MovingBlocks/Terasology#2744]
### What you were trying to do

Play on the Terasology event server

### What actually happened

I played for a little bit and looked around and switched from windowed to fullscreen. Then I realized that I liked it better windowed, on the computer I was on, and so I switched it back. When I clicked BACK, everything was white.

![image](https://cloud.githubusercontent.com/assets/16510596/21745691/f85b3a42-d4fe-11e6-823c-b3b339ff510f.png)

### How to reproduce

* Step 1
Join Terasology Event Server
* Step 2
Set display to Fullscreen
* Step 3
Set display to Windowed

### Log details and game version

**Game**:
https://gist.githubusercontent.com/Metatricity/3b7f8c6d1b008ca270d8a37b36c39de4/raw/706787d3c63ca6b42f74e675e9e580a4c5fd9d33/TerasologyLog.txt
**Init:**
https://gist.github.com/Metatricity/44e1f5403f57e4fe5f1ef43468cdfd91

### Computer details

Windows 7
Dell Latitude 3550, x64-bit
Intel Core i3-5005U @ 2.00GHZ, 2000 Mhz, 2 Cores, 4 Logical Processors
Intel HD Graphics 5500
7.64 GB of Physical Memory
15.3 GB of Virtual Memory

**Comment by Metatricity** [comment]
This might just be for my model of graphics card, but it is stil worthy of an issue :-1:

**Comment by iojw** [comment]
I believe that this issue related to display resizing and rendering is known and has already been mentioned a few times. 🙂 

See: #2528, #2659 and #2591

**Comment by emanuele3d** [comment]
Just wanting to confirm we are aware of the problem. 

Technically speaking this is most likely due to changes @tdgunes and I have done to the renderer, in particular in the area of FrameBufferObjects management. When resizing occurs the FBOs are regenerated, their id changes but most of the nodes in the renderer seems to be unaware of the new id and keep using the old FBOs which are no longer valid.

I can't tackle this just yet as I have some intermediate goals before I can take care of it, one of which is to simplify FBO management. But it will be taken care of. Soonish I hope.

**Comment by Metatricity** [comment]
Thank you for looking into this :)

**Comment by Metatricity** [comment]
@iojw However, there is no known record of there being a white screen rendered, there is only a black screen, or a water render change. #2528 and #2659

**Comment by iojw** [comment]
@Metatricity Sure, just listing a few related issues in the tracker and in general, issues related to resizing and the rendering are already known :)

**Comment by emanuele3d** [comment]
@Metatricity: we can keep this issue open until resolved, but it is likely to be a different manifestation of the same set of problems. Thank you for reporting it though.

**Comment by DPirate** [comment]
This maybe of some interest, it happened when I switched between windowed to fullscreen and then increased resolution parameter. While the 1 and 2 screen were responsive to player movements ,3 one remained frozen. Different FBOs perhaps?


![1](https://cloud.githubusercontent.com/assets/24975118/23740655/95f9eab4-04ca-11e7-9a4f-436a3fbf69cb.png)

**Comment by emanuele3d** [comment]
Rendering 3 (looks like ambient occlusions) most likely happens on a separate FBO. 
1 and 2 -may- happen on separate FBOs but... it's complicated.

The very next thing on my todolist is to work on WorldRendererImpl.initRenderGraph() to make it more explicit, so that it's easy(er) to see which render node use which FBO. 

After that I plan to change FBO management: right now FBO resizing/regeneration is done through an FBO manager. Eventually FBOs will be responsible for regenerating themselves when, say, screen size changes.

**Comment by Cervator** [comment]
Merging as fixed by #2844!
