### ISSUE TITLE
Optional module dependencies

### ISSUE THREAD

**Issue by oniatus** [MovingBlocks/Terasology#2754]
Modules can have optional dependencies by adding the flag `"optional" : true`.
However, this is not handled when component systems are registered and likely in some other places too.

I will take the [EquipmentSmithing](https://github.com/Terasology/EquipmentSmithing) module as example:

The module will register two systems: [RegisterEquipmentSmithingRecipes](https://github.com/Terasology/EquipmentSmithing/blob/master/src/main/java/org/terasology/equipmentSmithing/system/RegisterEquipmentSmithingRecipes.java) and [ForgingStationWindowSystem](https://github.com/Terasology/EquipmentSmithing/blob/master/src/main/java/org/terasology/equipmentSmithing/ui/ForgingStationWindowSystem.java) to wire the equipment module to the smithing module.

This could be integrated into smithing or equipment if we were able to register systems based on a condition, e.g. if a module is present on the classpath. I am __not__ saying that's the way we should structure our modules, the wiring modules have the benefit of keeping the original modules smaller.
But there may be other cases where the module integration is a 1-liner in one system, which would be too much for one module and could go in a single package like `org.terasology.smithing.optional.equipment.*`.

I'd like to write something like `@RegisterSystem(requiresOptional = {"ModuleA", "ModuleB"}))` which will only register the component system if the optional modules are present in the current environment.
As the component systems are the main entry points to wire modules together, this would allow us to loosely couple modules together and keep some adapter logic directly in the parent modules.

I think this can be achieved with very little code changes at `org.terasology.engine.ComponentSystemManager.loadSystems()`

Small test scenario:
- create two modules `TestA` and `TestB`. Create an interface in TestA, then create a componentsystem in TestA that implements the interface and use `@Share` to share the service.
- Add TestA as optional dependency to TestB
- Implement a System in TestB that injects the service from TestA with `@In` and log something from the service to the console after startup.
- Start the game with only TestB enabled -> Game crash with a NoClassDefFoundError.

**Comment by GabrielXia** [comment]
Hi I'm new here, can I try this problem ?

**Comment by Cervator** [comment]
Heya @GabrielXia :-)

You're welcome to give it a shot, but since this is architecture-centric you may want to try to spend a little time with the engine to understand how the involved concepts interact, like how the entity system itself works. There are some good pages in the wiki here and we have a few tutorials. So start by checking out:

https://github.com/MovingBlocks/Terasology/wiki/Entity-System-Architecture

I don't know how new you are to coding from your short message, but if you're comfortable with architecture and such you might be ready with just a bit of research. If not we just recently completed our involvement with Google Code-In which is aimed at new programmers with a lot of easy tasks - some of them can be done repeatedly (like adding new content) so if you're curious check out https://codein.withgoogle.com/tasks/?sp-organization=5452182442737664

**Comment by GabrielXia** [comment]
Hi @Cervator , thank you for replying me , I just submitted a PR #2767  for this issue, it's my first to work in the open project, thanks for letting me know where I have done wrong or where I could modify.


I want to take part in the GSOC, so now I'm trying to get familiar with Terasology. But It's also super cooooool to join Terasology even if I don't join in GSOC at last  :-)

**Comment by Cervator** [comment]
Appreciate the work! I left some comments in the PR :-)

Happy to see GSOC students here early, definitely a big factor in landing a successful proposal!
