### ISSUE TITLE
Remove guava from whitelist

### ISSUE THREAD

**Issue by SoniEx2** [MovingBlocks/Terasology#2791]
From: https://github.com/google/guava#important-warnings

"Our classes are not designed to protect against a malicious caller. You should not use them for communication between trusted and untrusted code."

I believe the sandbox should be reworked to allow the engine to use a separate guava from the module system, and then have a "guava" module that other modules can depend on.

Do not expose guava on sandbox API boundaries. The easiest way (and the way I'd recommend) to do that is to remove it from the whitelist.

**Comment by Cervator** [comment]
Consider me skeptical on this one, but maybe @engiValk would have a bit of fun looking at it.

I kinda get the feeling Guava just doesn't want to bother certifying itself safe vs just dlsclaiming "use at your own risk" - would be more interesting if there were any actual attack vector type examples.

**Comment by immortius** [comment]
Certainly having libraries in modules or as modules is something I've been thinking about a bit. No work has been done in this area yet though, and thought is particularly needed around potential version conflicts and the... wide variation in how version numbers and api compatibility are treated by different library developers. And other considerations.

To expand on the warning for everyone, it is warning about using guava classes in communications - this is a little more subtle than different to making guava classes available to modules. An example of the sort of problem they are warning against is this: https://github.com/google/guava/issues/2603 - if you pass around data in ByteArrayByteSource you are exposing yourself to untrusted code modifying the content in unexpected ways.

However, just allowing modules use a ByteArrayByteSource isn't dangerous in itself. A lot of the white listed guava classes are helpful utilities and classes that modules can just use inside their own workings. So having the guava classes in a module or exposed from engine is no different in that sense, as long as the code doesn't provide access to something like io or network communications or reflection. 

On the other end it should be noted the whitelist doesn't prevent the engine passing a ByteArrayByteSource to module code, as long it is presented as a ByteSource and ByteSource is whitelisted. It would prevent casting it to a ByteArrayByteSource of course.

Perhaps in the first instance we should review what guava (and other) classes are being exposed, why, and if any of them are being used for communication in a way that could be taken advantage of. We could also potentially introduce some static code analysis to detect what classes fall on the api boundaries - this should help give some oversight on the potential issues.

However I feel moving guava into a module without a more definitive issue is probably over-reacting. Firstly there are a bunch of guava classes that can be very safely exposed, such as DoubleMath. We can cut down to those and drop the types that might be used for communication. Secondly, again with the ByteArrayByteSource example - how bad is that? Can it result in arbitrary code execution or breaking permission boundaries? Or will it just mess up game functionality? Our goal, IMO, is to protect users from mods that may do malicious things to their PC. I want people to feel safe to connect to servers using mods and download them - and be properly informed what permissions they need. However the guava warning may just be addressing security issues which may allow breaking business logic - because guava is used very widely including in potentially business critical systems.

**Comment by SoniEx2** [comment]
To solve versioning issues is pretty easy: get a backwardsCompatible array.

`{"backwardsCompatible": ["1.1", "1.2", "2.0"], "version": "3.0"}`

(No idea if that's proper JSON)

**Comment by SoniEx2** [comment]
Imagine we get internet, and the internet whitelist is exposed through guava's unmodifiable stuff. Then suddenly malicious code somehow modifies that whitelist and gets access to someone's i2p console. That'd be bad.

**Comment by engiValk** [comment]
As @immortius said very succinctly, Guava is not a security risk in and of itself. It just isn't proven to be completely safe when communicating between two different bases of code. Containing Guava in a module is perfectly fine and removing it from the whitelist is pointless and would just cause more issues creating workarounds to us missing functions that it provides.
