### ISSUE TITLE
Fullscreen rendering issues on macOS

### ISSUE THREAD

**Issue by avikantz** [MovingBlocks/Terasology#2807]
### What you were trying to do

Play the game on fullscreen mode.

### What actually happened

The game entered full screen with output in a small frame, channels occupying separate layers.

![screen shot 2017-03-05 at 9 04 36 pm](https://cloud.githubusercontent.com/assets/7699509/23588724/afdc56a0-01e7-11e7-9b22-939a2238cc08.jpg)
![screen shot 2017-03-05 at 8 41 33 pm](https://cloud.githubusercontent.com/assets/7699509/23588726/b19a7314-01e7-11e7-8877-ff4b1b8704c2.jpg)

On exiting full screen, the rendering on window suffered channel blending issues.

![screen shot 2017-03-05 at 9 11 17 pm](https://cloud.githubusercontent.com/assets/7699509/23588779/8ab4375c-01e8-11e7-807a-40630807900b.jpg)
![screen shot 2017-03-05 at 9 05 35 pm](https://cloud.githubusercontent.com/assets/7699509/23588734/c35b37aa-01e7-11e7-80c0-d12d0d085704.jpg)

### How to reproduce

* Launch the game using `./gradlew game`
* Enter fullscreen

### Log details and game version

Version 1.3.0

No relevant to fullscreen log details.

### Computer details

MacBook Pro 15" Late 2015, i7 4770HQ, Iris Pro 5200. 

```
Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Mac OS X 10.12.3 x86_64
```

**Comment by Cervator** [comment]
Hi @avikantz and thanks for the detailed report!

This is a known issue with multiple previous reports and related problems surrounding fullscreen / resizing, such as #2744, #2659, #2591, #2532, #2528, #2490, #1747 .. wow they have really built up. I think I'll start closing new reports as duplicates since we have pretty good coverage from existing issues (some of which we should probably close as well)

@emanuele3d is aware of the issue and will probably hit the area at some point, or maybe some other 3D wizard will beat him to it. If you're curious to get notified of updates please subscribe to one or more of the existing issues :-)

**Comment by emanuele3d** [comment]
@avikantz: I confirm what cervator has said: I'm aware of the issue and I am proceeding toward fixing it but there are a number of steps to be taken before I can get there. Bear with us!
