### ISSUE TITLE
Rationalize swapping of gBuffers

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#2828]
Some of the nodes in the renderer swap the gBuffer FBOs, so that they can read from the gBuffer that was latest written to and write to the gBuffer with slightly outdated data.

This is a perfectly reasonable way of doing things but it is used inconsistently, with some nodes swapping the buffers -after- a rendering, which doesn't seem reasonable. (This is due to the refactoring that has taken place since begla's original code, and the fact that in some cases it was hard to understand where an operation such as the buffer swap belonged to).

We'll therefore need to verify all the instances of buffer swaps and see if we can move them before renderings that require the swap. We'll also need to verify if some renderings would require the swap but do not take advantage of it, generating subtle artifacts we might not even be aware of.

In this context, an option is to keep the buffer swap operations within the process() method of nodes. Another is to create a node class that only does the swap, so that it becomes quite explicit in the node graph.

**Comment by zeokav** [comment]
@emanuele3d I looked into the two classes where the read-only and write-only GBuffers are being swapped (PrePostCompositeNode and ApplyDeferredLightingNode). What is causing the problem here? Is there a race condition between the two nodes while reading and writing? 

> generating subtle artifacts we might not even be aware of

Is there any way to produce it? Because I haven't really come across any extra artifacts. 
Also, are there more nodes that require the gBuffer swapping in their process()?

**Comment by DPirate** [comment]
chunksRefractiveReflectiveNode (just after ApplyDeferredLightingNode) seems to require the swapping

**Comment by vampcat** [comment]
Sorry for arriving late to the party :D

Let's say we have two buffers, a primary buffer (the write buffer) which is used for almost all drawing operations, and a spare buffer (the read buffer) that is used to update the contents of the primary buffer by passing it through a shader, and swapping the primary and spare buffer via a ping-pong strategy.
(Not to confuse you, but the READONLY_GBUFFER is the write buffer, and the WRITEONLY_GBUFFER is the read buffer. Hopefully the next PR will fix this.)

For the afore-mentioned ping-pong strategy, our rendering pipeline (and the Nodes) can follow two approaches:
- The one that seems intuitive to you, because you like the names READONLY_GBUFFER and WRITEONLY_GBUFFER - every Node keeps writing to the write buffer, and when it needs to update the contents of the write buffer, it swaps the read and write buffers, reads from the read buffer (which was the write buffer so far) and writes to the new write buffer. This ensures that the writing is always done from the read buffer, to the write buffer.
- The second one, that seems more intuitive to me (and probably the original author of the pipeline, because he used the names SCENE_OPAQUE and SCENE_OPAQUE_PING_PONG - every Node keeps writing to the primary buffer, and when it needs to update the contents of the primary buffer, it reads from the primary buffer and writes to the spare buffer, and then swaps the two, ensuring that the primary buffer is the most updated one.

"with some nodes swapping the buffers -after- a rendering, which doesn't seem reasonable."
Just look at any one the uses of swap buffer, and think of READONLY_GBUFFER as the primary buffer and the WRITEONLY_GBUFFER as the spare buffer. Things should seem much more reasonable now :P

Just to clarify, we are using 2 swap operations in the entire pipeline atm. Both of these follow the primary-spare buffer logic.

"see if we can move them before renderings that require the swap"
We certainly can. If you want, I'll take care of this too. The steps involved are
- Moving the swap line to start of process()
- Instead of binding the spare and reading from primary, we read from READONLY and write to WRITEONLY.
That being said, I see no real reason to follow one approach or the other. Why not change the buffer names to PRIMARY_BUFFER and SPARE_BUFFER?
Although admittedly this comes down to personal preference.

"renderings would require the swap but do not take advantage of it, generating subtle artifacts we might not even be aware of"
This I haven't looked into so far, I'll post an update soon on this.

"Another is to create a node class that only does the swap, so that it becomes quite explicit in the node graph"
Another thing I'll take care of, in my next PR.

------------------------

One more problem, that you might have missed.
Swapping the readonly/writeonly buffers causes ALL the StateChanges and Nodes to recieve an update() call. This should not be the case, since this means update() is currently being called in every single frame. If we can remove it, we can save quite some processing every frame. So, how do we do it? I see three possibilities.
- Implementing subscibe functionality for FBOs, similar to how it's implemented for DRDFboMs.
- By treating this particular buffer swap as special, and not calling update() when swapping these buffers. This will however force us to create another method, subscribeToPrimaryBufferSwap() that is used only by the Nodes/StateChanges that use the RO/WO buffers.
- Making a new PingPongFbo class, that internally contains 2 FBOs. Instead of a global-ish method swapReadWriteBuffers in DRDFboM, we have a swap() in the PingPongFbo class. This will still require us to have a subscribe funcionality for PingPongFbo, but it'll be much more elegant, and will give us quite some extensibility for the future, since a lot of effects I want to implement in the future will also require buffer swapping.

Your thoughts?

**Comment by emanuele3d** [comment]
Thank you for the detailed analysis @vampcat. 

Regarding the read/write vs primary/spare:

The primary/spare doesn't describe the purpose of those buffers. You need to know the ping-pong aspect beforehand - although this could be explained in some javadoc or even a tutorial. Furthermore the term "primary" is a bit misleading given that eventually these gBuffers are abandoned in the "post-processing" section of the pipeline, in favor of a string of simpler FBOs for 2D processing.

By using read/write we know exactly what the intended use of each buffer is in a fairly unambiguous way and we can potentially add some javadoc/comment in a single, readily available place: the swapping method. So, unless we find something where this way of thinking breaks down, I'd stick to it.

Regarding the issue of the update() method: yes, I am aware of the problem.

Option 1 probably could be done anyway: doesn't feel incompatible with option 3.
Option 2 indeed adds another method and it's not necessary given the availability of option 1 and 3.
Option 3 did occur to me at some point. Indeed it would be elegant if consumers just had to deal with one FBO-like object rather than two and just needed to call its swap method when necessary. I guess we'd need to modify BindFbo and SetInputTextureFromFbo to be able to cope with PingPongFBOs. 

So, I'd say 3 keeping in mind 1 as a longer term goal?

**Comment by emanuele3d** [comment]
This is a note for myself.

Re-evaluate this issue in the context of the latest changes: are we happy with how we handle gBuffers swap? The stale vs lastUpdated gBuffer seems reasonable and easy enough to understand, but are there surrounding details that need to be ironed out?

**Comment by emanuele3d** [comment]
@vampcat: how to do you feel about this issue? I think we made considerable progress and I'm tempted of closing it. Are there outstanding aspects of it that warrant keeping the issue open? I.e. things we could do better on this front?

**Comment by vampcat** [comment]
I believe this issue is ready to be closed.

However, I also think that we need to open another issue and re-evaluate how the drawing is happening in the DefferedLightingNode and how things are working out without copying over some of the attachments (we dicussed this in depth on Slack).

**Comment by emanuele3d** [comment]
Agreed. Please go ahead and write the issue, so that we have a venue to discuss about it.
