### ISSUE TITLE
Taking a scaled screenshot briefly shows the game window partially rendered at the target size

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2863]
Pretty low priority as it doesn't seem to leave any ill effects. In short:

* Under video settings pick a screenshot size like half
* Take a screenie with `F12`
* Hear clicky noise and see the game window briefly only render the screenie size

Probably the screenshot process has to be made more independent from the main game rendering

Unsure if there may be other related issues around scaling or screenshots. We do have #1026 which relates to what a screenshot will actually include.

**Comment by vampcat** [comment]
@Cervator This *should* be fixed with #2879, but only partially. The reason is, taking a screenshot temporarily overrides the current scale, and shifting from full scale to half scale or something even for a frame can give a flicker like effect (not partially rendered though).

Test that PR, and update this bug accordingly (or don't, if you feel it's not good enough).

**Comment by Cervator** [comment]
Closing as complete - thanks for the reminder :-)
