### ISSUE TITLE
Refactor FBO class to have private GPU-side IDs

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#2902]
The FBO class currently has public fields such as fboId, which is an integer storing the opengl name. They should most likely be private, although this could/should be done in the context of a bigger refactoring of the FBO class.

**Comment by vampcat** [comment]
I feel like this is a nobel change, but since you created an issue for it, I assume you don't just want to convert fboId to private and provide an accessor for it?

If you do, I'll take care of this right after my current PR.
However, if you mean making it actually hidden from the world (no accessors), then there might be a slight problem for the BindFbo StateChange, which relies on the fboId to work. (Maybe shader parameters too?)

**Comment by emanuele3d** [comment]
Yes, private fields with read-only accessors would be enough. Depending on how we want to implement subscription to managers/regeneration (through FBO wrappers or right within the FBO class) you might want to use protected fields instead.

**Comment by vampcat** [comment]
@emanuele3d I believe we can close this now?

**Comment by emanuele3d** [comment]
Yup, doing it now!
