### ISSUE TITLE
Crash while loading (solo mode) world + modules

### ISSUE THREAD

**Issue by magali-demorangies** [MovingBlocks/Terasology#2905]
### What you were trying to do
After first launch of the game, for my first game I chose the solo game, and there the Sample something world. To customize this world I took several modules, as nothing was warning this could cause a trouble...
### What actually happened
When the game I selected started to load, it suddenly crashed.
### How to reproduce
The problem is I don't remind exactly which modules I selected to customize the world...
* Step 1 : take the first world from the list in Solo mode of the game, named "something Sample something"
* Step 2 : add modules, not all of them but several, and all the ones which were shown in yellow as I supposed they were needed by the modules I took (total around 20 certainly, maybe a little bit more)
* Step 3 : click on "play", the game showed the loading screen a short moment then crashed.

### Log details and game version
Terasology - Version
Jenkins:
  URL: http://jenkins.terasology.org/job/TerasologyStable/71/
  Build number: 71
GIT branch: origin/master
Created at: 2017-03-20T05:04:33Z
http://terasology.org
https://github.com/MovingBlocks/Terasology
### Computer details
Processor Intel Core i7 - 6700 CPU @ 3.40 GHz (x8)
Graphic Card NVIDIA GeForce GTX 1060 6 GB
RAM 8 G
Network : Eth, WiFi
OS : Windows 10
Log details : https://pastebin.com/cgTFuZvw

**Comment by gianluca-nitti** [comment]
That's an `OutOfMemoryError` so the Java Virtual Machine running the game ran out of memory while perfotming the task.
You could try to allow the JVM to use more of your machine's physical memory.

How do you run the game? If you use the launcher, go in its settings (by clicking on the gear icon) and tweak with the Max and Initial memory settings; since you have 8GB total I would set them to 6GB, provided you run the game without other programs in background.

Also you should ensure that you are using a 64-bit JVM (using a 32-bit JVM on a 64-bit CPU on Windows works due to [WOW64](https://en.wikipedia.org/wiki/WoW64), but with performance limits). Since you are on Windows, you can do it by going in Programs and Features in the Control Panel and searching for "Java". Look if you see something like `Java 8 Update 121 (64-bit)`. If you only have a `Java 8 Update 121` it's the 32-bit JRE; in this case, to get optimal performance you should download and install `jre-8u121-windows-x64.exe` from [here](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html).

**Comment by magali-demorangies** [comment]
First, thank you very much for your very quick answer, I'm really impressed (there is games I paid for whose devs made me wait more than several months before they "try" to get interest in my issues... And I send reports because I think that can help them to fix troubles, not to complaint !). Second, excuse me if this was not really a game or java bug, I must say I am not at all good with Windows OS (I am a Linux user forced by hardware troubles to use a friend's computer in place of mine, and I know nothing about Microbrain's Windows). I checked the JVM version and it was effectively a 32 bit one, then I installed the good one in place (thanks again, for the link). I tried the game since then and it runs nicely now, so I can tell you the case is solved. Have a nice day, and thanks a lot again !

**Comment by gianluca-nitti** [comment]
Glad you solved!

Your report is important, because it points out the game should warn the user in some way when it's running on a 32-bit JVM on a 64-bit system, to avoid people not taking advantage of their powerful hardware. The installer I'm developing for Windows shows a warning during installation if only a 32-bit JRE is found; however an in-game warning should probably be added for people which get the game through other distribution formats (e.g. zip, packages on Linux, etc).

**Comment by magali-demorangies** [comment]
Ok, happy I did not totally make you loose your time ! I installed the game from the zip package for Windows (I did not want to use the installer because it's not my computer, and I must be able to take off everything I added, without having to crawl through the register to erase traces...), then no warnings appear during "installation" (unzip + cut/paste folder...). Thanks for this game, and for the fact I will be able to play it under my Mageia Linux as soon as my own computer will be repaired ! By the way, if you ever need an english to french translator for any program, I did already several translations for Linux (gettext, KDE and Qt, and even text parts of scripts) and I would help with pleasure (my way to pay back the apps I use...). Thanks again and have a nice day !

**Comment by Cervator** [comment]
Closing as resolved :-)

Hi @magali-demorangies, thanks for the report, and I'm glad you were able to resolve it :-)
