### ISSUE TITLE
Consistent UI screen styles

### ISSUE THREAD

**Issue by Translator5** [MovingBlocks/Terasology#2927]
I would like to see a menu using a uniform!
Actually there are PopUps and Message boxes used in the main menu, as well as in-game.
This looks horrible if one screen is transparent and the second one is using a strict gray-tone!

change the background to **transparent** and **center the titles** as well as possible to **underline** them;
```
- engine:videoMenuScreen
- engine:inputSettingsScreen
- in-game skills screen
- in-game inventory/backpack screen
- (engine:previewWorldScreen) just the right part
- (engine:selectGameScreen) maybe
- core:inventoryHUD bar as well as the crosshair
```

change the background to **strict gray**;
```
- engine:midTestScreen
- engine:addServerPopup
```

create **border**ed screen for;
- `engine:enterTextPopup`   // if used at all, because `engine:enterUsernamePopup` looks better!

**fine** looking screen are;
```
- engine:joinGameScreen
- engine:createGameScreen
- engine:selectModsScreen
- engine:loadingScreen
- engine:creditsScreen
- engine:changeBindingPopup
- in-game journal
```

There are also some other issues
- screenshot size options are sorted in a not logical way
- screenshot format should be png by standard
- drop-down menu on "create game"-screen are not viewable in window-mode
- "Play" and "Back" button are also displaced in window-mode
- the title "experimental" on the "Player-Settings"-Screen is centered and do have a ":" at the end (whyever)
- there is no space between the right and left side of the text on "Select Modules..."-screen this cause failed space with other translations
- the text-field for the sound-settings is bit to short for some languages

**Comment by Cervator** [comment]
Hi @Translator5 thanks for the detailed suggestion :-)

Just to be totally sure, what you're saying here is to make the various UI screens look more _consistent_ right? So uniform in appearance.

Marking this bite-sized since it seems like some pieces would be easy to tweak at :-)

**Comment by Translator5** [comment]
You got it!

**Comment by Joseph5610** [comment]
Hi, @Cervator , is this issue still valid? If so, i would like to look into it

**Comment by jellysnake** [comment]
As far as I'm aware it is still valid. If a screen here still exists and still has the problems, then fixing it is indeed still something that needs to be done.

**Comment by Joseph5610** [comment]
Hi all,

I added transparent background  and centered titles to following screens:
- engine:videoMenuScreen
- engine:inputSettingsScreen
- in-game inventory/backpack screen

I changed background to strict grey to:  
- engine:addServerPopup

engine:enterTextPopup has already been bordered, now it has also a strict grey background.

I didn’t change other screens because it seems like they look fine now, and some of the listed screens are currently not used at all.

Regarding other topics:

- screenshot size options are now sorted from smallest to biggest
- default screenshot format is png
- removed “:” at the end of “experimental” title in Player-Settings screen

My question is about underlining the titles. The issue specifies the titles should be underlined, but there are no underlined titles in the whole game. 

Also, I cannot reproduce other points mentioned in the issue.

I would appreciate if someone could clarify and check if the other points which I couldn’t reproduce are still valid and needs to be fixed.	

You can check my changes in this branch:
https://github.com/Joseph5610/Terasology/commits/ui_screen_styles

**Comment by Cervator** [comment]
Hey @Joseph5610 - could you go ahead and submit your changes as a PR? That way we can add line comments and merge it when ready. It sounds like it might already be there :-)

Some of the affected screens have been changed since this issue. Anything you can't find or think is no longer valid is probably correct. My reading of the OP here seems to suggest underlining would be a possible nicety, but not something currently in place. We might want to skip that as underlining doesn't work in some character scripts.
