### ISSUE TITLE
Allow filtering out library modules from module list

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#2935]
The user currently gets all modules listed by default to select from. A lot of those modules are however only intended to be used as libraries by other modules. It does not make sense for the user to select library modules manually as they do nothing by themselfs. For this reason it does not make sense to list those module in the module list by default. e.g. the Pathfinding module is such a library module that is an important dependency for other modules but does not provide user usable features by its own.

So I suggest that we hide library modules by default in the module list and allow via a "show libraries" check box to show them in case someone is interested in just looking at the dependencies.

In order to identify library modules I propose that we add a isLibrary flag to the module.txt

**Comment by TheFlash98** [comment]
Is there a way to add a new field to the modules.txt of all the old modules? For the news ones I just edit the template one. For the old ones?

**Comment by Cervator** [comment]
Hey @TheFlash98 :-)

As mentioned on chat it may be doable to use a category string instead, and just default it to something appropriate so you don't need to update `module.txt` anywhere at first.

This issue is sort of a step two in the process as we don't have step one yet: actually categorizing modules (of which lib/framework is one such category). There is an old forum thread on the subject: http://forum.terasology.org/threads/module-categories.1068/

It may be as simple as just adding the new field to the _reader_ of `module.txt` then decorate the module screen accordingly. At first could simply add the category as a field that displays in the module info box, later we could make the buttons appear differently based on type or something, and allow filtering like this issue suggests.

One of our GSOC items for the year that did not get a slot somewhat relates: https://github.com/MovingBlocks/Terasology/wiki/GSOC#game--saved-world--module-preview-image-content - the module info box is already getting kinda crowded and improving that overall process would be nice, and maybe something to look into before adding even _more_ stuff to it. Although that's admittedly a lot more work :-)

**Comment by TheFlash98** [comment]
Hey @Cervator 😄!
For starters I think the modules should be categorised. However there's no issue which points towards or explains Step 1, right? Once that's done, we can make a dropdown like how issues can sorted label-wise etc(may be?). 

The idea of adding screenshots from the world is pretty good. It would be nice for a player to have sort of like a preview. However this may be need it's own separate window? May be a `More` button on the module info box?

**Comment by Cervator** [comment]
Correct on all counts and any idea that results in an improvement is fine by me. One potential GSOC student was looking at the preview item, but I forgot if the notes made it to the forum.

**Comment by TheFlash98** [comment]
Hey @Cervator 
I was just working on this. I made a `UIDropdownScrollable` instead of the checkbox. Now to display the list, I need to pass a `ArrayList` to it. Where do you want me to initialise the `ArrayList` with the types of modules possible?

**Comment by TheFlash98** [comment]
Okay so, on later speculations I thought that having multiple filters add the same time would be better. So I went ahead and created a new `CoreScreenLayer` which is linked by a "Advanced Filters" button on the SelectModulesScreen. That Screen lists down the different types of modules along with a `UICheckbox` to select and deselect them. 
I have the code to both the implementations (new Screen and dropdown) on separate branches. You can decide on one later! 😄

**Comment by Cervator** [comment]
That PR is now merged!

@TheFlash98 feel free to push ahead with multiple filters and such :-)

An advanced screen would be good for anything beyond a plain text filter or local only 👍

**Comment by TheFlash98** [comment]
@Cervator so far I've made the screen list some module types, and store the state of the check box in config. Gonna implement their actual functionality soon and send a PR.
