### ISSUE TITLE
Crash on first launch - stable release build alpha71

### ISSUE THREAD

**Issue by Germs2004** [MovingBlocks/Terasology#2977]
Run launcher, downloaded latest Release, ran game, clicked Single Player.  As world was loading, crash.  never got to world.

log:
https://pastebin.com/TNdJ4WFa

**Comment by skaldarnar** [comment]
Hi @Germs2004 and thank you for the report(s). For the one above, something went wrong with our reflection handling (which should not happen). 
Pinging @Josharias since it occurred in JS game mode. 

@Germs2004 could you try to download older versions of the stable game (through the launcher) and see if the same problem occurs?

**Comment by Germs2004** [comment]
Yesterday, I got the error on the latest stable, which was alpha 71.  Today, I tried alpha 70, and it worked.  I was able to load the map and see my surroundings, though it was super slow to load the textures (I gave up after 15 seconds of mostly gray screen).  The slow loading in v70 might be my weird software RAID setup.  I then exited and tried to load Alpha 71 again, and got the same error as yesterday.  So it seems like a regression from v70 to v71.

I noticed that the PasteBin button in the Crash Reporter tool only uploads the first file, "Terasology-Game_2.log".  I also see Terasology-menu.log and Terasology-init.log.  I would think that it's best for the Crash Reporter to include all 3 logs when uploading the paste to PasteBin.

Here are my latest crash logs from v71:

game log file:
https://pastebin.com/wGzjrh3b

menu log file:
22:57:49.705 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (14389), capping to 1000

init log file:
https://pastebin.com/Xmgnp7yt

**Comment by Cervator** [comment]
I put some more details in #2978 so lets use that one for the more complicated issue you face :-)

The bit where stable 71 failed but 70 worked is because we broke JoshariasSurvival, which is what you were trying to play, I believe. That's since been fixed and should be good again next stable build.

It is odd though that you could run the game at all with the JNA issue I describe a bit in #2978, but we can talk about that there. The unique crash here has been taken care of so I'm going to close this :-)

You should be able to confirm by simply running Core instead of JoshariasSurvival with a stable release.
