### ISSUE TITLE
Tutorial module request: Particle System

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2999]
With PR #2632 merged the initial implementation of #2208 is complete - we have a new particle system.

However, like noted in #2909 it still needs some additional polish and documentation. While I'm leaving that issue for general improvements including JavaDoc I wanted to split out a tutorial request separately, as it could be done in isolation (though some cross-pollination of doc improvements from anybody working either would be useful)

Might even be bite-sized for somebody willing to do some detective work and read through the linked issues.

Goal:

* New module: TutorialParticleSystem  - start locally with `gradlew createModuleTutorialParticleSystem` and either ask somebody to make the repo when ready or offer to transfer a copy from a personal repo in
* Code & prefabs as needed to demonstrate the base functionality and different kinds of particles
* Wiki pages in the new repo that cover a step-by-step introduction to the system

Review the https://github.com/Terasology/TutorialWorldGeneration module and its wiki https://github.com/Terasology/TutorialWorldGeneration/wiki for inspiration

Some persons of potential interest to potentially ping who have been poking at the system:

* @MaxBorsch (author)
* @niksoc (made a neat video with new effects)
* @skaldarnar & @portokaliu (figured out some updates for Light & Shadow)

**Comment by TheFlash98** [comment]
Hey @Cervator I could try making another tutorial. Any nice place to start with? 😄

**Comment by skaldarnar** [comment]
Here are some changes to the way block damage particles work: https://github.com/MovingBlocks/Terasology/pull/3001

There's also https://github.com/Terasology/LightAndShadow/pull/53 and https://github.com/Terasology/LightAndShadow/pull/54 in combination with https://github.com/Terasology/LightAndShadowResources/pull/19 to fix the particle effects in LightAndShadow. That might be a good start. 

Overall, you could try to implement particle effects like the ones described in the linked issues. Figure out how to use textures for the particles, how to create simple, colored particles, which components influence which behavior, ... 

I would go a ahead and try to implement as many fancy effects as I can imagine, and then document what I did in order to implement it. And some helping hand by @MaxBorsch would simplify it a lot :wink:

**Comment by jellysnake** [comment]
[Light & Shadows](https://github.com/Terasology/LightAndShadow) is one. I'm not aware of anything else at the moment.

**Comment by TheFlash98** [comment]
Thank you

**Comment by skaldarnar** [comment]
The particle system is an engine feature, so no specific module to link to. It is used sparely right now, but examples can be found all over the place. The "resurrection statues" also use them, block particle effects are implemented that way, and there are probably examples for smoke in modules like _Smithing_ or _Rails_.
Otherwise, a lot of trial and error with implementing your particle effects and documenting what you did.

**Comment by Cervator** [comment]
GooeysQuests also uses particles when Gooey spawns (usually always right after you spawn) or when Gooey spawns structures :-)

(Rez statues are in Lost)

**Comment by TheFlash98** [comment]
I guess this can be closed now 🙂 
https://github.com/Terasology/TutorialParticleSystem

**Comment by jellysnake** [comment]
Closing this as completed by @TheFlash98
