### ISSUE TITLE
Improve UI response when meta server unavailable / returning no content

### ISSUE THREAD

**Issue by metalim** [MovingBlocks/Terasology#3069]
### What you were trying to do
Get server list.

### What actually happened
Dear Terasology Developers and Support staff,
 
I have just started Terasology after update, and got this: https://puu.sh/xbnf1/82adfcc23d.png
First it showed "Downloading server list..." for a minute, then got "Server list complete" with no servers. What kind of UX sh* is this? What was it downloading then?
 
Until update, that makes game enjoyable,
Sincerely,
Maxim Litvinov.

### Log details and game version
ALPHA Terasology-2039 2017-08-14 Gamma Dash 51-OMEGA-07-does-it-need-moar-important-letters?

**Comment by Cervator** [comment]
Hi @metalim and thanks for the report :-)

I can confirm the issue, which must be very recent. We have been doing some work on infrastructure and module/server listing lately and it seems like something got shook loose somewhere.

Our meta server (shows module and server info) is meant to be optional so the game should work without, clearly that could be made more obvious. The meta server is coming back with no server listings right now so the game should indicate as much rather than just say the listing (of nothing) is complete.

As such we have two things to look into here

* Find out what's up with the meta server's listing of game servers
* Clarify UI when a faulty or empty response is returned

**Comment by msteiger** [comment]
I just rebooted the service. Please try again.

**Comment by msteiger** [comment]
The DB was updated during a maintenance operation. Everything should be back to normal now. Please confirm (and close ;-) )

**Comment by Cervator** [comment]
Can confirm it works now :-) Thanks @msteiger!

That completes 1 of 2. Leaving this issue open with a new name and bite-size since part 2 is pretty easy: update the "Server List Complete" to better indicate when the meta server is having problems. For instance:

* Detect if the lookup fails or times out. Show "Meta server lookup failure"
* Detect if there are no entries returned. Show "Lookup complete but no servers found"
* Else simply show "Server listing complete! `x` servers found"

Or maybe case 2 and 3 can be the same and just show "0" in that case.

Can break the meta server by changing `masterServer` in `config.cfg` (was recently renamed and may be turned back into meta)

**Comment by TheFlash98** [comment]
@Cervator on changing just the `masterServer` in `config.cfg`, the downloader tries to download from `defaultAddress` which has been set to meta.terasology.org in `NetworkConfig.java` and successfully downloads it. However when I changed that as well, as proper  message saying "Error Downloading Server List!" was displayed. How does one reproduce this?
