### ISSUE TITLE
A doubt about entity hierarchy and entity cache.

### ISSUE THREAD

**Issue by heLomaN** [MovingBlocks/Terasology#3375]
### What you were trying to do
Find some suggestion for implementing entity hierarchy and entity cache.

I'm struggling about ECS framework, and find this great project. So want get some help here.

Sometimes, we need create and destroy some kinds of entity, and the performance must be concerned, while a possible solution is enable/disable these entities other than destroy. But a lot of entities have parent and children relationships, which make enable and disable costly. How should we handle this case?

**Comment by Cervator** [comment]
Hi @heLomaN - could you let us know a bit more about what you're trying to do? Say what sort of gameplay you're trying to implement, what piece of system logic you're implementing, etc. Often it helps to know what your goal is so we can suggest if your approach to get there sounds right or if some better way exists.

If you're more trying to just investigate ECS as a concept then that's fine too, but it might be easier to discuss on one of our chat systems live sometime :-)

Hopefully you've read through some of the architecture pages in our wiki? There is more / better formatted documentation regarding the ECS at https://metaterasology.github.io/docs/concepts/entitySystem.html or  https://metaterasology.github.io/docs/developing/entitySystem/entitySystem.html

My impression is that generally entity parent/child relationships are used pretty rarely in our code. And there isn't a current way to enable/disable entities at all, although there's a desire to make it possible to enable/disable specific components on an entity.

On a related note the [v6 of our entity system code](https://github.com/MovingBlocks/gestalt/tree/develop/gestalt-entity-system) is a fairly substantial overhaul, having been extracted from Terasology's engine (this repo), but not yet been re-integrated as an external dependency. That may happen with https://github.com/MovingBlocks/DestinationSol first as re-integrating into Terasology is a very large piece of work. It also adds some new features like transactions, indexing, etc.

**Comment by heLomaN** [comment]
@Cervator Thank you! I have read some document about ECS, including Terasology's. I found parent-child relationship should be very common in a game. For example, a character in a car, and a gun in the character's hand.  

Actually I am trying to implement a mobile engine which take face data as input, and will spawn some decorations for each face. For example, we need a 3d ear ring model and a glasses model for each face. The face count may vary since what the phone camera sees varies. 

So we make the ear ring and glasses as two entities, and as a prefab. For each face we create one corresponding entity(named face entity), and attach the prefab(two entities) as children. Naturally, we support the entity hierarchy relationship in entity manager. 

The creating of 3d mesh costs, so we want to disable the face entity and its children when faces disappear, and enable them when appear. One choice is provide Entity.disable()/Entity.enable() interface, which disable/enable there children at the same time. But I found this makes the code hard to read and implement. Is it a good solution? Could you please give me some suggestion?

Here is [an old discussion](https://gamedev.stackexchange.com/questions/31888/in-an-entity-component-system-engine-how-do-i-deal-with-groups-of-dependent-ent) about a similar problem.

**Comment by Cervator** [comment]
Nice link - T-Machine was also one of our inspirations :-)

The first item in there does cover the family/child scenario, and I'll have to agree:

> Do I implement some kind of parent-child entity relationship (entities can have children)? This seems to contradict the methodology that Entities are just empty container and makes it feel more OOP.

We don't use parent-child approaches like that commonly if at all. Sure, it is a common concept in gaming, but somewhat goes against the spirit of ECS. One possible case where we use it might be for a player and their client instance or character avatar.

I've personally used parent/child in a Terasology module but that was _literally_ a parent/child relationship with in-game creatures, tracking the children of a queen creature so spawning more would eventually stop, and so they could all go off together to create a new village.

The closest example to yours might be our Equipment module. There we had the challenge of enchanting different pieces of equipment, and aggregating the effects on the player wearing the equipment. That was tricky as we don't allow duplicate components on a single entity, so you couldn't just attach two different `HpEnhancingComponent`s to the player entity.

In that case I believe we did end up using an entity per _part_ so you could attach the same sort of enchantment (for better reuse) on multiple pieces of equipment, then a system would aggregate the effects onto the player entity. But that's a sort of edge case and I'm still not sure if that's the ideal design.

Another example is a posable avatar, where you have two distinct meshes you need to be able to pose independently. Or if you as a player enter a vehicle and want to delegate your movement to the vehicle. In those cases I believe we link the entities in some way, but I'm not sure if that's necessarily a parent/child thing. More like synchronizing movement in one with the other.

If a character is wielding a gun depending on how meshes work out it might just be that you attach an associated single component that interacts with a system holding logic related to gun wielding, even rendering the additional artwork on the character model. The component could hold a reference to a graphic and the character's original mesh component could indicate relative positions to attach things to.

In no case do we use activation/deactivation since our ECS doesn't even support it. The Equipment example is close since an effect coming from a piece of example might be suppressed somehow (anti-magic / consumables / cooldown). But whatever parts are implemented make do without that functionality, so far.

For any case in which you don't *need* some sort of entity linkage or even multiple entities in the first place I'd think you're better off trying to come up with better ways to attach sensible components to a single entity.

**Comment by skaldarnar** [comment]
Closing this stale discussion ticket.
