### ISSUE TITLE
Game crashes using Lost template

### ISSUE THREAD

**Issue by dwumpus** [MovingBlocks/Terasology#3542]
Just started the game, looked around at settings, then came back, started a single player game selected the "Lost" template, and the game crashed.
https://pastebin.com/E3NrgHbi

**Comment by dwumpus** [comment]
Just started the game, looked around at settings, then came back, started a single player game selected the "Lost" template, and the game crashed.
https://pastebin.com/E3NrgHbi

**Comment by jellysnake** [comment]
So, looking through the log, the line `java.lang.OutOfMemoryError: Java heap space` indicates that this crash was caused by running out of memory.

If you try reducing settings like view distance as well as launching with more memory available it should fix your problem.  
If you still get this crash even with this then please re-open the issue as there is a possibility there could be a memory leak of some sort.
