### ISSUE TITLE
Allow UI text to be specified in an array

### ISSUE THREAD

**Issue by PS-Soundwave** [MovingBlocks/Terasology#3629]
Presently, multiline text has to be written in ui files on a single line, potentially resulting in absurdly long lines. The common work around to this is to specify text as an array of strings to be joined by newlines. This should be implemented for UIText, and potentially other widgets.

**Comment by shaunakdixit** [comment]
can you specify any particular file so that I can look into

**Comment by shaunakdixit** [comment]
what I know is we create a keyword then we specify text for that keyword in menu_en files

**Comment by darshan3** [comment]
Can you point out an example ui file where this issue occurs?

**Comment by shaunakdixit** [comment]
Yup In universeSetupScreen.ui there is a warning printed which is quite long.

**Comment by shaunakdixit** [comment]
And better idea to find more is go to menu_en file then look for long strings in that file. Search their identity in whole project by ctrl+shift+f and you will get ui files :-)

**Comment by eviltak** [comment]
The same result can be achieved in a different (and IMO more convenient) manner: if the extra text array attribute is not going to be used programmatically (which I don't think it should anyway) and is purely for convenience when describing UITexts in JSON, another alternative can be to simply add a new type handler for the `String` type to the JSON serializer that simply joins the string array to create a single string. In other words, if the serializer sees a String in a UI file  described as an array of strings, it'll treat the array as an array of lines and join them together to obtain the actual string to set. This has the added benefit of not involving any changes at all to `UIText` (and any code referencing it) while also being really easy to implement.

I do realize that this suggestion may have some unintentional consequences, the biggest one being that it will invalidate the work introduced in #3678. While I recognize and greatly appreciate the time and effort @profgrammer has put into #3678, I do think that this solution is a better way of achieving the goal. That said, I do not mind if we still elect to merge the contents of #3678 given the amount of effort already put into it. I'd love to hear your thoughts, especially @profgrammer since this will directly affect his contributions in #3678. By the way, we also have the slightly more time consuming option of letting @profgrammer or someone else implement the second solution and compare them side by side!

**Comment by profgrammer** [comment]
Hi @eviltak, I will be more than happy to try out your version of the solution. Can you help me understand what changes need to be made to the serializer? Thanks

**Comment by jellysnake** [comment]
Undoing the github autoclose as there is ongoing discussion. See my comment on the PR about what to do in terms of alternative implementations

**Comment by eviltak** [comment]
@profgrammer here is the alternative solution (as discussed on Discord):

Given that most if not all long pieces of text will be defined in a translation (`.lang`) file, the addition of a simple `JsonDeserializer<String>` implementation to the `Gson` object (via `GsonBuilder.registerTypeAdapter`) in `TranslationFormat` should suffice. The implementation will read a `JsonElement` as a `String` if it is either a) a string itself, or b) an array of strings, which are concatenated together to create one whole string. I took a quick look at a few of the longer strings in `menu_en.lang` which should ideally be broken up over multiple lines, and they do not have _any_ newlines in them. Keeping this in mind, I'd rather have the string array joined without a delimiter rather than resorting to a `\n` as the delimiter.
