### ISSUE TITLE
Terrible things happen when starting a _second_ game without a game restart

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3688]
### What you were trying to do

Test unrelated things! Which sometimes involve jumping into more than one world.

### What actually happened

Inconsistently would get warped worlds with messed up data, from broken chunks to entirely messed up block data (hills of torches, pure water world, etc)

### How to reproduce

This is the minimal use case I could consistently reproduce real quick

* Step 0: (Unsure if needed: start from a clean game, no saves or config)
* Step 1: Start the game from source, create a new game, pick Core, quick start
* Step 2: Verify all looks well, exit back to the main menu
* Step 3: Create a new game, pick Core, quick start - bad things happen

Similar issues have happened in the past (malformed block ids through some scenario), but I thought they were all long gone. Game state handling between multiple games in one game launch has remained a fragile area, however. Chances are something isn't being reset properly when leaving the first game world.

**Comment by darshan3** [comment]
I tried to test this, turns out that it also occurs on restart.  
### How to reproduce:  
1. Start from a clean game with no saves.
2. Start the game from source, create a new game, pick Core, quick start.
3. I tried both exit methods: 
  a. Exit to Main Menu -> Exit Terasology from Main Menu  
  b. Exit Terasology from Pause Menu
4. Start the game again from source, create a new game, pick Core, quick start.  
  
So, it turns out that you cannot create a new game when you already have a save game.
