### ISSUE TITLE
Unreachable translation platform

### ISSUE THREAD

**Issue by comradekingu** [MovingBlocks/Terasology#3830]
translate.terasology.org seems to be down.
It is also not easy to find on https://terasology.org/

**Comment by Cervator** [comment]
Hey @comradekingu and thanks for the report. Yeah our poor old Weblate instance is hard to keep online. Rather than go through the hassle of trying to salvage it then update and keep running I'm wondering if we could use Crowdin instead then not have to host anything at all. That's probably a bit of a project on its own and we need somebody to volunteer to help with that process. Should happen sooner or later :-)

In the meantime translations can still be contributed but by editing the language files manually with a local source workspace.

**Comment by comradekingu** [comment]
@Cervator Use https://hosted.weblate.org/ by clicking contact us at https://weblate.org/en/hosting
Crowdin is closed-source.

**Comment by skaldarnar** [comment]
We are no longer using weblate. 
Closing as outdated.
