### ISSUE TITLE
Under water effect too early

### ISSUE THREAD

**Issue by ahoehma** [MovingBlocks/Terasology#405]
The "under water" filter should start if the head of the player is under water. I guess is it hard (impossible) to apply the under water effect only for the "under water area" of the screen?

![under_water_effect_over_sea](https://f.cloud.github.com/assets/548214/44967/e26ea2c2-5727-11e2-9156-09d6087972dc.png)
##

**Comment by emanuele3d** [comment]
@skaldarnar just pointed me to this. It is not impossible. 

I guess what's needed is a mask (an opengl stencil buffer?) of the underwater part of the screen so that an underwater effect shader is applied only to those pixel. 

Then, the line representing the intersection between the camera's near plane and the liquid surface needs to drive an additional shader to blur or do some kind of other joining effect between the dry/wet portions of the rendering, like [this image](http://abduzeedo.com/files/originals/half.jpg).

That been said, while I know what probably needs to be done, my opengl/shader knowledge is just not yet there to implement this. Stay tuned!

**Comment by jdrueckert** [comment]
Cannot reproduce this anymore:
![image](https://github.com/user-attachments/assets/7452c3cc-cc06-4043-ae7c-19991d0cb5d1)
