### ISSUE TITLE
test: separate integration tests to their own gradle task

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4606]
Some tests are slow and flaky and not safe to run in parallel. We've [added tags](https://github.com/MovingBlocks/Terasology/pull/4605) to these tests and would like to use them to define a separate test run.

We have `TteTest` and `MteTest` tags for these tests. The remainder of the tests (hopefully less slow and flaky) remain untagged. We will be treating `TteTest` and `MteTest` as equivalent for this new test task.

We need one gradle task (possibly the default `test` task?) that **excludes** tests with either of these tags,  
and one gradle task that **includes** _only_ tests with either of these tags.

This needs to be done for
- [ ] `engine` and/or `engine-test` projects in the main repo
- [ ] modules, which are configured by `terasology-module` under `build-logic`

`engine-tests/build.gradle` is probably the easiest place to start.

### References

Terasology tests are written using JUnit 5 and run with the JUnit Platform.

* [Tagging and Filtering—JUnit 5 User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering)
* [Testing in Java Projects: Test Grouping—Gradle 6.8](https://docs.gradle.org/6.8.2/userguide/java_testing.html#test_grouping)

## Naming Questions

- Should we make new tasks for "tests with MTE" and "tests without MTE", and keep `test` in its current behavior of running all JUnit tests? **Or** should we change the default `test` task to be the "without MTE" one?
- What should the "tests with MTE" task be named? Could be less specific than "MTE" to include other implementations in this category. `integrationTest`, `simulationTest`, `flakyTest`?

**Comment by keturn** [comment]
pinging @jdrueckert for input on the naming of things and @mahela97 for implementation

feel free to ask questions here or in #logistics

**Comment by mahela97** [comment]
Sure.

**Comment by jdrueckert** [comment]
@keturn Thank you for writing this up :+1: and @mahela97 thank you for volunteering to implement this :+1: 

I believe we don't want to keep `test` in its current behavior of running all tests, but have two new tasks, one for the tagged tests, one for the non-tagged tests. I'd suggest going for the following naming:

* "unitTest" (or just "unit"?) - everything "MteTest" and "TteTest" tags
* "integrationTest" (or just "integration"?) - everything with "MteTest" and "TteTest" tags

IMO this makes sense because of the following expectations:
Proper unittests are expected to be many, but small in scope (testing a small aspect of the code), fast-running and parallelizable. Integration tests (including end-to-end (E2E) and scenario tests as well as tests combining a few units) on the contrary are expected to be fewer, but bigger in scope, slower-running and likely not parallelizable.

While it's possible that currently, our non-tagged (neither MTE nor TTE) tests are not pure unit tests but could also be categorized as integration tests, they are expected to be a lot quicker than MTE and TTE tests. If they turn out not to be, we can think about tagging them as well and grouping them with the MTE and TTE tests.

**Comment by keturn** [comment]
> I believe we don't want to keep `test` in its current behavior of running all tests

Hmm. The `test` task is provided by default and is expected to be there by convention. I can't think of a technical requirement that says we _must_ follow that convention, but I am reluctant to do away with it entirely.

For example, when you run `gradlew test` in our Terasology multiproject, it runs `test` in each of the subprojects. Including subsystems and facades as well as any modules you have present, etc.

Perhaps we should make it so `test` does not directly run tests itself, but it _depends on_ both `unit` and `integration` tasks.

**Comment by jdrueckert** [comment]
Oh I was already thinking about the stages in Jenkins when I said we want to have those two separate ones.
I would expect `gradlew test` to still run all of them.
