### ISSUE TITLE
Crash reporter fails to upload the logs

### ISSUE THREAD

**Issue by Hume2** [MovingBlocks/Terasology#4699]
### What you were trying to do
When the game crashes, the crash reporter appears. It asks me to choose where I want to upload the logs. None of Pastebin or Google Drive works.

### What actually happened
When I click Pastebin, it throws an error message saying: Failed to generate paste:

When I click Google Drive, it throws an error message saying: https://jenkins.terasology.org/userContent/GooeyDrive-24506b2f1f34.p12

Sometimes the crash reporter just closes without any apparent reason. I assume, it just crashes.

### How to reproduce

* Step 1: Make Terasology crash
* Step 2: Answer the dialogs until you get to the screen asking for uploading the logs.
* Step 3: Click Pastebin or Google Drive. In both cases, an error message appears.

### Log details and game version
I tested it in versions preview alpha-20+195 (20210519) and release alpha-19+2. It happens in both versions.
I think, the crash reporter is not logged, is it?

### Computer details
OS: Ubuntu 18.04

**Comment by skaldarnar** [comment]
Nargh, a crashing https://github.com/MovingBlocks/CrashReporter is indeed bad 🧐 Crash Reporter is a separate project that hasn't changed for quite some time, so we bundle the same version with our recent releases (thus, no difference between version).

@Cervator the issue about Google Drive seems to be caused by the shutdown of the Jenkins instance at `jenkins.terasology.org`. Maybe we can just move over some configuration and bend over the reference in the Crash Reporter?

First issue about Pastebin might be changed API or changed paths of logs or something like that. We need to investigate that.

**Comment by skaldarnar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix CrashReporter](https://trello.com/c/4arhlQws/117-fix-crashreporter)

**Comment by Cervator** [comment]
I'm pretty puzzled why the GDrive option would have anything to do with the old and now gone Jenkins, but sure, that'd do it. I didn't code that piece but surely we must be able to redo it real quick.

Pastebin likewise and at the same time, odds are the API changed ages ago and we didn't update. Looks like https://pastebin.com/doc_api would cover it and I have the credential for our Pro account handy if needed :-)

**Comment by skaldarnar** [comment]
@Cervator we reference the old Jenkins to retrieve a key for the Google Drive upload, see https://github.com/MovingBlocks/CrashReporter/blob/master/cr-core/src/main/java/org/terasology/crashreporter/logic/GoogleDriveConnector.java#L190-L199

I think this is related to the `gooey` account, so I hope you have access to that account and could look whether you find something that looks like a developer or API key...
