### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [MovingBlocks/Terasology#4983]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jdrueckert** [comment]
Hi @JamieSlome, @huntr-helper,
Thank you very much for opening this issue!
I created above-linked PR that will add a security policy file according to GitHub's recommendation. Kindly have a look at it and tell me whether it's what you were looking for or if there's anything missing.

We are looking forward to work with you and other people from open source security research communities in the future! :green_heart:

**Comment by JamieSlome** [comment]
Hello @jdrueckert - thank you for your amazingly swift response!

I can see that you have received the report to the mentioned e-mail, so let me know if you have any further questions or require further support. Just for clarity on some of your comments on the report, the researcher can help suggest and contribute fixes! ❤️

**Comment by Cervator** [comment]
Hi again @JamieSlome - I do have a follow-up question. I responded in detail on the report shortly after we got the link. There has been no replies and we just got a reminder email that the report hasn't yet been validated by us. Without some better context on the site it is not actually clear to me what the "Approve" vs "Reject" exactly mean.

The problem is: the "vulnerability" is a rather odd one, that it kinda seems like a scan of some sort found, maybe initiated by a human, but not really considered from the human aspect. In short: it is entirely a non-issue that isn't worth fixing, as it simply exposes no risk. But sure, it is _technically_ valid, as whatever scanning tool discovered.

Is that "Approve" but then close? Is it "Reject" ? It isn't worth fixing, and honestly if the site doesn't mix together robots and human intuition well enough then the quality of hits is likely to be low, even to the point of being junk/spam in this case. I love the initiative, but could see it go sideways if "vulnerabilities" such as this one gets reported blindly regardless of context. This has been a net loss on our behalf, from time taken to review a pointless report with an unresponsive reporter on a 3rd party site - although we did end up making the nice SECURITY.md file, at least.

If I don't hear back within a few days I'll reject the report and walk away sad.

**Comment by JamieSlome** [comment]
Hello @Cervator - thanks for sharing your feedback!

To give some clarity, approve signals to us that you believe the report to be a legitimate security concern against the code-base, that has potential security implications or impact. When rejecting, this indicates that it is not a security issue (i.e. a bug or some technical issue - which is what sounds like this case could be). 

We are constantly trying to improve the platform to ensure that quality reports are shared with maintainers, to save time for both the maintainer and researcher!

In my opinion, given your feedback here and on the report, I would recommend "Rejecting" the report as it does not appear to be a security concern with impact in your eyes.

Let me know if you have any more questions or feedback, and happy to help! ❤️

**Comment by Cervator** [comment]
Thanks for the details. I went ahead and rejected the report then, providing a relevant response as to the why.

I do appreciate the potential of that website, I would just make sure to have a more careful human review of a vulnerability plus more clarity on the website about how the process works as a maintainer. I checked the front page and the FAQ but they're still pretty slim on the details IMHO :-)

One particular confusing point, a bounty hunter can get paid for just _reporting_ a valid vulnerability, by _your_ community, and even _we_ can get a (smaller) bounty for fixing the vulnerability in our own project? That seems nice and all but I'm having trouble seeing the business plan to keep you running 😅 And the potential for abuse in just "fixing" things in lesser used repositories. By now I suppose we might be big enough. I guess this might just be the visibility gaining phase followed by a hope of getting sponsors and enterprise customers.

**Comment by JamieSlome** [comment]
@Cervator - thank you for updating the status of the report.

Thanks for your recommendations for the website, we will definitely take your ideas on board. If you have any things you would really love to see on the platform, I'd love to invite you to create a feature request on our public [repository](https://github.com/418sec/huntr/issues/new).

With regards to bounties, we reward maintainers as we understand that taking time from a maintainer is precious, where they could be contributing elsewhere, and we see the fixing of vulnerabilities as an important part of remediating a vulnerability.

Long term, we look to work closely with enterprises that depend so heavily on OSS to fund the security/vulnerability research. We are constantly on the watch for "abuse" behaviors, and without a doubt, they evolve as the platform grows. We have and continue to put various quality measures in place to prevent these abuses.

Let me know if you have any further questions - happy to discuss! ❤️
