### ISSUE TITLE
Is the game legal or not?? We need an answer from the developers

### ISSUE THREAD

**Issue by lightblue123** [MovingBlocks/Terasology#5265]
Hello,

Did you guys copied assets (Things: Zombie or world pictures-> Images.) from minecraft into your game?

Is your game legal or not

Thx.

For more better info for your website. Put this

"This game not copied from minecraft!, The game Assets are made by us)

**Comment by Cervator** [comment]
So this is a somewhat odd question to ask nearly _thirteen_ years since we began the project, I think - no offense intended :-)

In the very very beginning a few textures was used from a Minecraft _texture_ pack, released under a permissive enough license for us to use it (open source / creative commons type stuff). And obviously Terasology was inspired by Minecraft, among other things. It isn't impossible that a stray old texture might have originated from elsewhere and been copied around, and certainly it is an objective (although a low priority one) to further distinguish Terasology further away from how Minecraft does things, i.e. the floating hand in the one corner.

The game is entirely legal and there is no need for additional disclaimers. There are mentions here and there about the background if you go looking, various license files, attribution, etc 👍

**Comment by lightblue123** [comment]
My friend, you are a member and you have no source for what you said.


Frankly, the license you mentioned is (nothing).

If you are wondering why? Developers need a license from Mojang for the textures I mentioned
Who made those pictures? It's Mojang.
Images copied from Minecraft without a license from Mojang are (theft), and for use it is against the right to use.

If you say: This is just a game, my friend, no matter how stolen or legal it is, we do not care.

My friend, you do not know the penalty for using stolen materials.

Don't think I'm talking about cops

**Comment by lightblue123** [comment]
> So this is a somewhat odd question to ask nearly _thirteen_ years since we began the project, I think - no offense intended :-)
> 
> In the very very beginning a few textures was used from a Minecraft _texture_ pack, released under a permissive enough license for us to use it (open source / creative commons type stuff). And obviously Terasology was inspired by Minecraft, among other things. It isn't impossible that a stray old texture might have originated from elsewhere and been copied around, and certainly it is an objective (although a low priority one) to further distinguish Terasology further away from how Minecraft does things, i.e. the floating hand in the one corner.
> 
> The game is entirely legal and there is no need for additional disclaimers. There are mentions here and there about the background if you go looking, various license files, attribution, etc 👍

If you want to help me, ask the developers to answer my question. only an answer from developers

**Comment by BenjaminAmos** [comment]
To clarify things, Cervator is probably the most qualified person to answer your question. He has been with the project since its conception and still listed as its most prolific contributor to this day: https://github.com/MovingBlocks/Terasology/graphs/contributors. The "Member" tag is actually a fairly good indication that a person is directly involved with a project (although people can choose to not show it, as I do). People are usually invited to become members of the GitHub organisation when they become one of the project's "developers".

> If you want to help me, ask the developers to answer my question. only an answer from developers

In answer to your question as somebody else who contributes to the project as a developer, yes, I believe the game is completely legal.

I can tell you that, to the best of my knowledge, all assets have been provided under an appropriate licence. We maintain records of and abide by each asset's licence terms (mainly in the [Credits](https://github.com/MovingBlocks/Terasology/blob/develop/docs-pre-merge/Credits.md#soundtrack-and-sound-effects)) and we are very aware and respectful of the rights held by others. We do not incorporate, and to the best of my knowledge never have incorporated, materials (textures, sounds, music, code, etc.) derived from commercially published games, including Minecraft.

Some things may be inspired by existing games but Terasology is its own game and has no interest in copying from others. We prefer to source assets from the community and from wider permissively-licenced asset libraries across the internet (usually Creative Commons licenced). If you find any direct evidence of copyright infringement in our game, please tell us!

> For more better info for your website. Put this
> "This game not copied from minecraft!, The game Assets are made by us)

To make such a statement in a prominent place would be to implicate us of doing what we are not. If you are not violating the rights of others, then there is no need to state as such. In conversational English, sadly denial is often as telling as confession. I feel such a statement would convey the wrong impression.

**Comment by lightblue123** [comment]
Hello,
I trust what you said but honestly I have no right to play your game because every developer didn't answer the question, there are 99 graphics developers you don't know all of them and you don't know where they got the assets from or who made them.
I don't care about music because I'll always mute it, but the world of pictures and other things,
This game is illegal because there is no source about the assets.
Now you will enjoy playing this game and not worry about stealing, and later you will cry because you knew that your hands will be cut off for play illegal.
I will play any game instead of this game.
Thanks, Bye.

**Comment by engiValk** [comment]
Based on Minecrafts EULA and Usage Guidelines people are freely allowed to use textures from Minecraft to support their own original works so long as the content doesn't violate the Minecraft EULA or TOS. 

Terasology doesn't violate any of those as the stupilations or on ensuring you do not promote anything illegal and do not incite violence or hatred on others. Along with a few other things we do not do. As this is not for commercial use their rules and regulations on what we can use is also much more lax as this is a non-profit open source game. If we were to sell Terasology we'd be a lot more restricted but even still we would be entirely in the clear with the current state of the game and anything we might have taken from Mojan or Minecraft.

We also have the safety net of this being all protected under fair use anyway as we work closely with google for their "Google Summer of Code" event, which means we have a case for being a learning environment, doubly so that we are again, non profit.

Thank you for your concern, it is appreciated but at our current standings we are not violating any copyright law nor are we infringing on the rights of Mojan or Microsoft.

As was said previously by @Cervator the only content from Minecraft we have is some very old builds of the game used textures from there. Modern Terasology is entirely custom content.

https://www.minecraft.net/en-us/usage-guidelines Usage guildelines founds here.

As for the other issues of having lots of developers and artists that have all given their work, by commiting to github you are automatically agreeing to their license for any uploaded work that is assumed to be the same license as the base repo. By the very nature of them uploading the content to our git and us merging it, they consent to their work being used by us. We do not need express permission after the fact as it is in legal terms refered to as "Implied consent". If any work was found to be outside of the uploaders rights to share we would immediately comply with any requests to remove such content as per githubs Terms of Service. So far to my knowledge this has never happened but if it does I can assure you we would take it very seriously and immediately work with said artist or programmer to rectify the issue.

I hope this answers your question.
