### ISSUE TITLE
Animated block tiles

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#628]
Making an issue for this as we don't actually have one, yet we have block graphics contributed that could be animated - don't want to forget :-)

http://forum.movingblocks.net/threads/512x-new-animated-tiles-fire-and-portal-30frames.802/

Those are a tad high-res, but hey. pretty ;-)

Would probably need some sort of generic multi-texture block definition support by where blocks could associate themselves with multiple tile textures. Could also be useful for "variant" blocks (subtly different grass blocks) or "quantity" blocks (bookshelves showing differing numbers of books)

Currently water and lava animations are hard coded IIRC. Not a huge priority right now but cool when we finally get it - figuring it is one for @begla's list :-)
##

**Comment by Cervator** [comment]
Bump - old topic, but we've recently had some movement on it.

@OvermindDL1 / @MarcinSc - would you say the support for this is there now? Or is the new work on fancy meshes and working computer monitors something else?

**Comment by MarcinSc** [comment]
No, I think this is a different thing, the monitors/displays are rendered via entity, which is not good if you plan to have a lot of them. Hopefully monitors/displays will not be too common.

**Comment by OvermindDL1** [comment]
@Cervator 
Custom mesh rendering is purely for custom shapes, not textures.
Personally I would have animated blocks be on a custom layer to bind to a shader and have the shader take a set of data of how to render various texture and make a texture with x being the texture and y being the frame, just have it loop over rendering on y based on time with the framerate data and frame count for the given specific texture on the x.

If you wanted to do it how MC does it, it does it by making a giant single atlas texture that is built at run time of a size set at start-time based on what the video card supports, it does not handle non-square textures well but it handles animations by giving a single animated texture, say 'water', a single slot, then it locks that portion of the image when it needs updating and uploads the new frame in that location to the GPU.  It is efficient-enough with few animated textures, but with many textures and/or a huge texturepack it will utterly swamp the data bandwidth between the cpu/gpu.

Best efficiency and power would be a touch of a rendering system overhaul to be more like this in my opinion:
 * The actual renderable of a chunk mesh would be multi-renderable, as in a single block can render to one or more parts
 * The renderable should be generated dynamically and cleared when no block uses it, this way rendering static-texture blocks like dirt would be on one renderable type and another, say one that uses a shader-based noise generator, could use that one while also supplying some baked data to the shader at rendering time so water could render using procedurally generated noise of varying blues with intensity based on weather or so, and lava could render with reds/yellows with a darkness based on temperature or so, all with the same shader and layer.  Mods could then add their own as well, which they might do even for static blocks if they change a lot, say a redstone-like system so it can update the redstone renderable without causing the rest of the chunk to need to regenerate its mesh's.
 * When a block change takes effect, immediately calculate what rendering layers need updating and only queue those to update.

What that would do overall is provide a significant performance boost for some highly-chunk-busy blocks, allow for extremely unique rendering like water/lava, moving grass, and more, while allowing mods to register their own layer render specialties.

**Comment by Cervator** [comment]
Thanks for the enlightenment :-)

I'm nowhere near a 3D wizard so the details are beyond me, but I do what I can to push the topic along from time to time :D

I wonder if @emanuele3d would be interested. I'll be happy to have any recommendations / designs / pseudo code / etc. Just as long as it is somebody else implementing and reviewing the changes :cake:

**Comment by immortius** [comment]
Renamed to Animated block tiles for clarity

**Comment by immortius** [comment]
While I don't disagree with @OvermindDL1, mostly (he still says rendering when he means mesh generation, and we already generate multiple mesh per chunk for different effects such as water and ice, just not in a generic fashion), I feel the simpler option I mentioned above would be better than diving immediately into custom chunk mesh support (though that would still be worthwhile): animating the world atlas.

If we pick a fixed frame count like 12, we could generate 12 copies of the world texture atlas and make the main chunk shader jump or lerp between them and thus animate the entire world. For animated block tiles each of the atlases would include a different frame, while for other block tiles it would be the same frame. 12 is a convenient number as we can support a variety of smaller frame counts by repeating them (2, 3, 4, 6, 12). 

This has some limitations - everything would animate at the same rate (or a factor of it, if they used less tiles), uses more texture memory and doesn't support crazier effects, but keeps the mesh count down. We could split out just the animated blocks to a separate mesh too, which would reduce memory usage and but increase draw count. Either way it has the benefit of allowing animation to be used much more widely than would be possible with a separate mesh per effect system - you could have diamonds sparkle, furnaces flames animate, etc.

**Comment by OvermindDL1** [comment]
@immortius 
I had precisely the same idea for an engine I made a few years back and did the same with the fixed animation rate, it did not end up working well and wasted *way* too much GPU memory.  The style I described earlier is what I ended up coming up with to replace it, though never got around to implementing it...

**Comment by immortius** [comment]
Raw maths puts 12 4096x4096 atlases at 768MB, which is too much, yeah. At the same time having a mesh per type of animated tile would be to draw count heavy or preclude having simple animations (which possibly is a restriction we could live with).

Perhaps if we just used the texture switch method for animated tiles... A 16x16 tile with 60 frames of animation takes about 1/20th of a MB. So we could support a fair number of those in their own atlas. And 60 frames should be enough for decent animations. Lerping between two would also smooth the animation.

**Comment by Cervator** [comment]
@OvermindDL1: It sounds like you have an opportunity here to implement that thing you never got around to implementing last time around ... :angel: 

With some added ideas and tweaks thrown in from the nice discussion here :-)

**Comment by emanuele3d** [comment]
Just noticed I got tagged. 

At this stage I know too little about what happens in shaders and how the texture atlas is used. I now have a pretty good high-level overview of what the rendering engine does and the refactoring currently in progress will hopefully make it clearer for others too. But I just had a few furtive glances into what the shaders do. 

Off of the top of my head and just reading the discussion here I've been wondering if it'd be useful to have separate texture atlases for different frame counts. I.e. all animated textures that have 6 frames are in their own atlas, all animated textures that have 12 frames are in their own atlas and so on. Perhaps this is in line with what Immortius was saying with his 60 frames example.

For memory and bandwidth purposes the engine might only allow animated textures with specific number of frames, i.e. 2, 3, 4, 6, 9, 15, 30 and 60, disallowing anything in-between to limit the number of atlases.

Going a bit further into what is perhaps dream-land, the engine could also rank animated texture according to their weight, so that texture with fewer frames, fewer bitplanes and having a smaller area get prioritized while others get ignored during atlas-assembly because of memory constraints. Modules would then be wise to provide multiple version of the same texture, so that at least the version with smaller areas and smaller frame counts will become part of the atlas.

Also potentially in dream-land, it might be possible to reduce the number of necessary frames for a given animation if timing information can be provided alongside it. I.e. 4 frames encoded in the atlas might actually support longer animations if the engine can be informed that, say, the first frame should actually last 3 frames, the second 1 frame, the third 2 frames, the last 3 frames again, and that the whole sequence should be flipped and repeated immediately afterward: an 18 frames animation for the price of 4 frames.

**Comment by immortius** [comment]
Maybe, as long as it wasn't too prolific.  The reason for minimizing the number of texture atlases is minimizing the number of separate mesh that need to be generated per chunk, as you cannot render different parts of the same mesh with different textures (without shenanigans or texture arrays at least). Draw count is already going to be a big problem given the distances we want to support, and each additional mesh per chunk makes that worse, so having things using the same atlases where possible is best.

The engine will currently downsample provided block tiles if their is not enough room on the atlas for them given the total tile count, so I guess the same can be done for animated. And yeah, no issue with frames repeating or whatever.

**Comment by emanuele3d** [comment]
@immortius, you wrote: "as you cannot render different parts of the same mesh with different textures  (without shenanigans or texture arrays at least)"

Maybe I'm confusing OpenGL versions/features or I'm simply missing something, but wouldn't it be possible to pass an array of per-vertex arbitrary data where the data is a simple id identifying the texture to use? And regarding texture arrays, couldn't 3d textures be used in their place?

**Comment by immortius** [comment]
Yes, the method would be adding an index to the uv data to indicate texture. But a 3D texture would not work because of mipmapping - the layers would get smushed together at a distance. The advantage of a texture array is correct mipmapping behavior.

**Comment by emanuele3d** [comment]
Ah. Good point about mipmapping. 

So, say, the atlas for 12-frames animations would have to be a single flat image with all 12 frames of all animations in it, one beside another. The shader then gets an atlas ID and a texture ID alongside UV coordinates and uses it to sample the right portion of the right atlas, perhaps adding some kind of offset so that identical animations are not synchronized. Conceptually sounds... feasible.

But wait, why use multiple atlases if all frames are stored in the same image then? As long as the atlas has some shader-accessible per-texture metadata associated with it, providing information about, say, the number of frames, perhaps everything could be stored in one atlas anyway? Animated and non-animated textures?

**Comment by immortius** [comment]
That is true, you could encode animation data in the vertices, have all the frames in the atlas and animate with the shader. The limitations there are performance of the shader and the limited size of the atlas. A single texture can only be so big (hardware dependant) and fitting all the tiles and frames on there would be a challenge. Especially with higher resolution tiles. Also increases the memory required by the meshes. But that would be a way of achieving animated tiles without many limitations.

My suggestions were along the lines of animating by switching texture (so you would have 12 copies of the atlas and each would have a different frame), and having a separate atlas just for the animated tiles so those copies don't include the unchanging tiles. This is all an attempt to prevent animated tiles filling the atlas.

**Comment by emanuele3d** [comment]
I hope I'm not dragging this conversation longer than I should. It's not something I'm going to get myself into so I'll have to be happy with whatever gets actually implemented.

Regarding the points above @immortius: even though I've fully read or gone through almost 4 opengl books in the last 6 months, I feel there are so many practicalities I still don't know about or are simply not easily retrieved from my (biological) memory banks even though I might have read about it.

Of course you make a good point regarding the need for multiple atlases if anything because of the size limit on single textures. Regarding the memory increase on meshes, true, but the increase could be very small. Specifically, an ID is needed to uniquely identify the texture, ideally across multiple atlases. Furthermore, perhaps a byte could be allocated to describe an animation toggle/offset. All other texture-related metadata, (i.e. sizes, offsets number of frames, frame sequence in an animation) should be quite light and could be stored in a simple buffer that is permanently left in GPU memory.

Shader peformance: why are you worried about it? Perhaps naively I'd think it shouldn't be difficult for the shader to start from a texture ID, animation toggle/offset and look into the texture metadata to find where to sample. 

Switching textures  is, as far as I know, a fairly expensive state change if you mean binding a new texture to an active texture unit. I seem to remember reading somewhere that switching the storage underlying the texture, leaving the texture parameters unchanged (i.e. sizes, filtering) is much faster because the state doesn't need revalidation, it's just providing a new location from which to read. I imagine you knew this already.

A few more thoughts: you are rightly concerned with the number of draw calls. Are you using the term "mesh" as in the set of data that is handled by a single draw call? If that's the case the method I'm suggesting would reduce the number of draw calls as we wouldn't need separate meshes for separate textures. Also, are we taking advantage of separators in vertex index data, so that discontinuous groups of triangles can be sent to the GPU in a single stream? Finally, are we taking advantage of functions such as glBufferSubData() and glMapBuffer to surgically modify a single stream of data sent via a single draw call instead of sending many separate draw calls?

**Comment by immortius** [comment]
I agree the mesh data increases are probably not an issue. Shader
complexity is only a concern because the shader is already quite complex,
but some of these techniques could probably be used to simplify it.

With the texture switching I was suggesting, it is once a frame - which
means it is essentially free because the texture needs to be bound once a
frame anyway. That is, all mesh are rendered with this frame's atlas.

I'm not sure what you are suggesting with the rest. A chunk mesh is all the
vertices and indices for the chunk - this is stored in a buffers. Each mesh
is drawn in a single call, using the existing single texture atlas. How
would sub buffers and map buffers be useful?

**Comment by emanuele3d** [comment]
They wouldn't then. I just wasn't sure if each chunk is already a single draw call. 

Well. I guess we have added enough meat on the fire. Who's gonna cook it? =D

**Comment by Cervator** [comment]
:meat_on_bone: :poultry_leg:

I dunno! But now at least we have more material to go over for a volunteer, once we finally get to it. Guess I'll unassign @begla, alas :-)

**Comment by SoniEx2** [comment]
Options:

1. Do it the classic way. Stream texture changes, like MC does, like pre-2000s games do, etc. This is easy. This works on everything from ancient to modern hardware.
2. UV shaders. With this, you stream frame number and the shader calculates the correct UVs and stuff. I don't do shaders, someone else would have to do this. You could animate the whole game and assuming around 1024 block types, you'd be looking at 240kbytes/s for 60FPS animations (and even then, that's assuming 4-byte integers).

    It might also be possible to make the shader itself calculate the frame number, but I don't think shaders have access to time deltas? Then again, I know nothing about shaders.

**Comment by OvermindDL1** [comment]
Re @SoniEx2 option 2:

You can pass the current time in a uniform to the shader then calculate which frame should be used based on a small amount of encoded data about the frames such as framerate and such.  You could even have per block animations by encoding with their data an offset of the time frame or if it is paused or so (time multiplier).  It is pretty easy to do over all.

**Comment by SoniEx2** [comment]
@OvermindDL1 per-block is overkill. find me a good use-case if you disagree.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 per-block is overkill. find me a good use-case if you disagree.

Absolutely is overkill, but it could be baked into certain animation types, useful for, say, an animated texture on a machine, have it slow down if under powered, have it paused (0 multiplier + whatever offset) if no work, etc...  The information passed would be based on a pass and what information each pass should encode, so such things would render few and far between and as such would use little to no data in the general case.

**Comment by SoniEx2** [comment]
@OvermindDL1 Per-block is overkill. Use a special renderer. You're not supposed to have a chunk full of machines anyway.

And you don't want to update a massive VBO just to change a single machine's animation speed. You also don't wanna depend on OpenGL 4.4+, and this isn't Dolphin where you can just use vertex streaming hack.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Per-block is overkill. Use a special renderer. You're not supposed to have a chunk full of machines anyway.

Heh, you've never played a gregtech server I guess.  ^.^

And you would not need to update a massive vbo, encode the tile state information as a texture and interpolate based on the time values, you'd only need to update the 'pixel' state data for a tile when a machine state changes (and the VBO/VBA/rawWhatever does not change at all), this is a fairly fast operation and certainly does not require OpenGL 4 (easily done with OpenGL 2).  You really should learn shaders, it is a fascinating little language.  :-)

Technically you could encode every cube like that, but for that much data you'd need a higher OGL level to support the larger shaders (though with OGL3/4 with Geometry shaders you could entirely encode the tile information into a very small set of data that would be significantly faster to send to the video card, but that seems extreme and require modern hardware, though it would save a significant amount of data and bandwidth for all blocks that are cube shaped, unless you started encoding shapes in the data as well, which is also possible).

**Comment by SoniEx2** [comment]
Uh I was kinda hoping you'd google "dolphin vertex streaming hack"...

But maybe I should just leave this to you, as you seem to know shaders...

**Comment by OvermindDL1** [comment]
> Uh I was kinda hoping you'd google "dolphin vertex streaming hack"...

I'm at work so minimizing my time doing non-work things, hence my terse responses (I do apologize if they ever come off badly, it is not intended ^.^).

> But maybe I should just leave this to you, as you seem to know shaders...

They are actually not very hard, just like assembly programming but with different multi-data using instructions, you should learn it, it is fascinating.  :-)

**Comment by PS-Soundwave** [comment]
Resolved by #3481.
