### ISSUE TITLE
Standalone NUI editor

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#849]
Making an issue for this now that NUI is merged in and available, even if not totally complete yet. We had touched on the idea in the past that with most the GUI definitions in JSON you could actually work on GUI in a standalone editor without having to run the whole game.

Unsure if this would be a completely separate tool or another custom facade still having engine access. First one would probably benefit from NUI as a separate lib one day while the second one may not fully benefit from engine separation.

http://forum.terasology.org/threads/nui.869/

**Comment by rzats** [comment]
_Would the editor work better as a standalone JavaFX application (i.e. WorldViewer) or a built-in editor (i.e. Behavior Tree Editor)?_

At the moment I'm heavily leaning towards the former since the editor is supposed to be a micro-IDE of sorts, and requiring the user to run an instance of Terasology just to use the editor may be a significant turnoff. However, @flo has also mentioned the latter being a potential option as it would make displaying custom UI elements possible - if the editor is developed as a standalone application, some compromises may need to be made (e.g. the editor will attempt to draw a custom element's native parent as a placeholder).

Pinging @msteiger and @immortius regarding this.

**Comment by msteiger** [comment]
These are different things, imho. NUI works on top of a rendering engine. By default, this is LWJGL, but it also works with plain Swing. An implementation is at https://github.com/MovingBlocks/FacadeAWT - it uses simple top-down view for the in-game scenes. WorldViewer is a plain Swing/AWT application, too.

I suggest this: create a frontend (called facade) like FacadeAWT that uses engine as a basis. It could look like the behavior tree editor and maybe have some kind of internal text editor.

Maybe this is inspiring: [YouTube: Demonstration of live internationalization](https://www.youtube.com/watch?v=Ju_-Fg4XZPQ)

**Comment by Cervator** [comment]
Hey @rzats if you can think of some new follow-up issues to this that we should aim to complete feel free to submit some. Ideally with some of them being bite-sized if possible :D

Closing as completed by GSOC 2016 and made part of Alpha 4 :-)
