### ISSUE TITLE
Noise-based generation of distinguishable terrain features

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#943]
Infinite terrain worlds are typically generated by noise generators such as Perlin or simplex. While the generated patterns are aperiodic, no distinguishable terrain features are created.
Regions such as desert areas have only very little high-frequency noise while mountainous regions will have a lot. 

A first step could be to create abstract, large, high-level regions which are then refined depending on the type. Smooth transitions between such regions must be created.
##

**Comment by ar0ne** [comment]
Hi All,
Could somebody help me to understand current state of this issue?
I'm just trying to understand what have to be done... Looks like a lot of work was done since the issue has to be opened.

**Comment by Cervator** [comment]
Sure.

So for starters this issue is *very old* meaning the original intent may have been superseded or even lost by now, unless @msteiger remembers and can enlighten us :-)

It also seems somewhat open to interpretation, which for me is all about layers:

* Basic Perlin with simple noise layers just result in a one-pass effect where you get hills, depressions, etc, and it goes on like that forever
* Building another layer/pass in like @MarcinSc did results in a less granular level of noise that spreads out the repeating details, but ultimately still has them, just on a higher scale (if I understand the idea correctly)
* Going more distinct would need coming up with a way to seed a few unique (or nearly unique) features very rarely across the landscape, retaining solid form over a very large area (a full region-sized feature)

I'd be after the 3rd option there for something that would satisfy this issue. And it might relate to some of the side features from the [Sector write-up](https://forum.terasology.org/threads/new-conceptual-layer-sector-plus-musings-on-multi-world-node.1420) that got one pass during GSOC last year. 

For instance: imagine you're building a world in large segments. For a finite world you might pre-generate a full world map, for infinite you just pick a very large size aiming to add more segments to it later as needed. For Sectors and related ideas that's a world map scope that doesn't really exist at present. This layer doesn't even have chunk-level details, let alone blocks or "normal" noise. It just marks out some continents, regions, and stuff like that.

At that level you could have some sort of selector for a distinct terrain feature, like a mountain pass cutting a path through a mountain range. That feature would affect a *large* area, reshaping the mountain, leaving logical paths through the pass, and maybe offer pathfinding hints for how to calculate travel through the region. It would also need to smooth out the edges of the region, like not continuing the same look on either side if one is desert and the other is swamp, leaving a hard boundary.

I suspect my example may go a bit past the original intent of the issue, but being that the issue is a bit out of date I thought I'd come up with a present day interpretation and actual cool thing I could see working in the game :-)
